/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-07-02 18:01:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.premium;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.util.Locale;
import java.time.format.TextStyle;

public final class Analisis_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


    Connection c;
    Statement s;
    ResultSet r;
    boolean cv, cvG;
    String mo, moG, xVM, yVM, lDP, vDP, xIAlT, yIAlT;
    double x_md, x_mdG, g_h, g_hG, vt, vtG, i, sp, spG;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.time.format.TextStyle");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.util.Locale");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');

    try {
        Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
        c = DriverManager.getConnection("jdbc:mysql://localhost/PSHOP", "root", "n0m3l0");
        s = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        r = s.executeQuery("SELECT P FROM Usuario WHERE CE='"+session.getAttribute("u")+"'");
        r.next();
        if (!r.getBoolean(1)) {
            out.print("<script>alert('Lo sentimos, NO eres un Usuario PREMIUM... por lo que NO puedes hacer uso de este APARTADO...');</script>");
            out.print("<script>location.assign('../index.html');</script>");
            r.close();
        } else {
            r.close();
            r = null;
            r = s.executeQuery("SELECT TP FROM Compra WHERE V='"+session.getAttribute("u")+"' AND X=4 ORDER BY TP");
            double x, dt, md;
            x_md = x = md = g_h = vt = i = sp = 0;
            dt = 1d;
            cv = true;
            if (r.next()) {
                g_h = 1d;
                long n = 0;
                r.beforeFirst();
                while (r.next()) {
                    vt += r.getDouble(1);
                    g_h *= r.getDouble(1);
                    n = n + 1L;
                }
                x_md = x = vt / n;
                g_h = Math.pow(g_h, (1d / n));
                if ((n - 1L) % 2 == 0) {
                    r.absolute((int) ((n - 1L) / 2L));
                    md = r.getDouble(1);
                } else {
                    r.absolute(Math.floorDiv(((int) (n - 1L)), 2));
                    md = r.getDouble(1);
                    r.next();
                    md = (md + r.getDouble(1)) / 2;
                }
                r.beforeFirst();
                dt = 0;
                while (r.next()) {
                    dt += Math.pow((x_md - r.getDouble(1)), 2);
                }
                dt = Math.sqrt(dt / ((n > 30L) ? n : (n - 1L)));
                if (dt / x_md > 0.3d) {
                    cv = false;
                    x_md = md;
                    r.beforeFirst();
                    g_h = 0;
                    while (r.next()) {
                        g_h += 1d / r.getDouble(1);
                    }
                    g_h = n / g_h;
                }
            }
            r.close();
            r = null;
            r = s.executeQuery("SELECT N,Pop FROM Producto WHERE CE='"+session.getAttribute("u")+"' AND Pop>0 ORDER BY Pop DESC");
            mo = "<li>NINGUNO</li>";
            lDP = "\"Sin DATOS\"";
            vDP = "0";
            if (r.next()) {
                mo = lDP = vDP = "";
                long aux = 0;
                r.beforeFirst();
                while (r.next()) {
                    lDP += "\"" + r.getString(1) + "\",";
                    vDP += r.getLong(2) + ",";
                    aux = aux + 1L;
                }
                lDP = lDP.substring(0, (lDP.length() - 2));
                vDP = vDP.substring(0, (vDP.length() - 2));
                r.beforeFirst();
                long n, pop;
                n = pop = 0;
                while (r.next() && r.getLong(2) >= pop) {
                    n = n + 1L;
                    pop = r.getLong(2);
                    mo += "<li>"+r.getString(1)+"</li>";
                }
                if (n == 1L) {
                    sp = (x - pop) / dt;
                } else if (n == aux) {
                    mo = "<li>TODOS</li>";
                } else {
                    sp = (3d * (x - md)) / dt;
                }
            }
            r.close();
            r = null;
            xVM = yVM = xIAlT = yIAlT = "";
            for (byte m = 6; m > 0; m--) {
                r = s.executeQuery("SELECT TP FROM Compra WHERE V='"+session.getAttribute("u")+"' AND X=4 AND Fh>='"+LocalDate.now().minusMonths(m).withDayOfMonth(1).toString()+" 00:00:00' AND Fh<'"+LocalDate.now().minusMonths(m - 1).withDayOfMonth(1).toString()+" 00:00:00'");
                if (r.next()) {
                    x = 0;
                    r.beforeFirst();
                    while (r.next()) {
                        x += r.getDouble(1);
                    }
                    xVM += x + ",";
                } else {
                    xVM += "0,";
                }
                yVM += "\"" + LocalDate.now().minusMonths(m).getMonth().getDisplayName(TextStyle.FULL, Locale.forLanguageTag("es-MX")) + "\",";
                r.close();
                r = null;
            }
            xVM = xVM.substring(0, (xVM.length() - 2));
            yVM = yVM.substring(0, (yVM.length() - 2));
            x = 0;
            for (byte sm = 16; sm > 0; sm--) {
                r = s.executeQuery("SELECT TP FROM Compra WHERE V='"+session.getAttribute("u")+"' AND X=4 AND Fh>='"+LocalDate.now().minusWeeks(sm).toString()+" 00:00:00' AND Fh<'"+LocalDate.now().minusWeeks(sm - 1).toString()+" 00:00:00'");
                while (r.next()) {
                    x += r.getDouble(1);
                }
                yIAlT += x + ",";
                xIAlT += "\"-" + sm + "S\",";
                r.close();
                r = null;
            }
            xIAlT = xIAlT.substring(0, (xIAlT.length() - 2));
            yIAlT = yIAlT.substring(0, (yIAlT.length() - 2));
            r = s.executeQuery("SELECT TP FROM Compra WHERE X=4 ORDER BY TP");
            x_mdG = x = md = g_hG = vtG = spG = 0;
            dt = 1d;
            cvG = true;
            if (r.next()) {
                g_hG = 1d;
                long n = 0;
                r.beforeFirst();
                while (r.next()) {
                    vtG += r.getDouble(1);
                    g_hG *= r.getDouble(1);
                    n = n + 1L;
                }
                x_mdG = x = vtG / n;
                g_hG = Math.pow(g_hG, (1d / n));
                if ((n - 1L) % 2 == 0) {
                    r.absolute((int) ((n - 1L) / 2L));
                    md = r.getDouble(1);
                } else {
                    r.absolute(Math.floorDiv(((int) (n - 1L)), 2));
                    md = r.getDouble(1);
                    r.next();
                    md = (md + r.getDouble(1)) / 2;
                }
                r.beforeFirst();
                dt = 0;
                while (r.next()) {
                    dt += Math.pow((x_mdG - r.getDouble(1)), 2);
                }
                dt = Math.sqrt(dt / ((n > 30L) ? n : (n - 1L)));
                if (dt / x_mdG > 0.3d) {
                    cvG = false;
                    x_mdG = md;
                    r.beforeFirst();
                    g_hG = 0;
                    while (r.next()) {
                        g_hG += 1d / r.getDouble(1);
                    }
                    g_hG = n / g_hG;
                }
            }
            r.close();
            r = null;
            r = s.executeQuery("SELECT N,Pop FROM Producto WHERE Pop>0 ORDER BY Pop DESC");
            moG = "<li>NINGUNO</li>";
            if (r.next()) {
                long aux = 0;
                r.beforeFirst();
                while (r.next()) {
                    aux = aux + 1L;
                }
                moG = "";
                long n, pop;
                n = pop = 0;
                r.beforeFirst();
                while (r.next() && r.getLong(2) >= pop) {
                    n = n + 1L;
                    pop = r.getLong(2);
                    moG += "<li>"+r.getString(1)+"</li>";
                }
                if (n == 1L) {
                    spG = (x - pop) / dt;
                } else if (n == aux) {
                    moG = "<li>TODOS</li>";
                } else {
                    spG = (3d * (x - md)) / dt;
                }
            }
            r.close();
            r = null;
            r = s.executeQuery("SELECT A FROM Usuario WHERE CE='"+session.getAttribute("u")+"'");
            r.next();
            i = vt - r.getDouble(1);
            s.executeUpdate("UPDATE Usuario SET A="+vt+" WHERE CE='"+session.getAttribute("u")+"'");
            r.close();
            s.execute("COMMIT");
        }
        s.close();
        c.close();
    } catch (Exception e) {
        out.print("<script>alert('Lo sentimos, se produjo un ERROR... intentalo de NUEVO...');</script>");
        out.print("<script>history.back();</script>");
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es-MX\">\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Analisis de Datos del Usuario</title>\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"../imgs/logo.png\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" rel=\"stylesheet\">\n");
      out.write("        <style>\n");
      out.write("            body {\n");
      out.write("                background-color: #f0f0f0;\n");
      out.write("                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("            }\n");
      out.write("            .navbar-custom {\n");
      out.write("                background: linear-gradient(135deg, #2d5016 0%, #4a7c2a 100%);\n");
      out.write("                padding: 0.8rem 0;\n");
      out.write("                box-shadow: 0 2px 10px rgba(0,0,0,0.1);\n");
      out.write("            }\n");
      out.write("            .btn-custom {\n");
      out.write("                border-radius: 25px;\n");
      out.write("                font-weight: 600;\n");
      out.write("                padding: 0.6rem 1.5rem;\n");
      out.write("                transition: all 0.3s ease;\n");
      out.write("                text-decoration: none;\n");
      out.write("                display: inline-block;\n");
      out.write("                margin: 0 0.3rem;\n");
      out.write("            }\n");
      out.write("            .btn-success-custom {\n");
      out.write("                background: linear-gradient(135deg, #28a745 0%, #20c997 100%);\n");
      out.write("                border: none;\n");
      out.write("                color: white;\n");
      out.write("            }\n");
      out.write("            .btn-success-custom:hover {\n");
      out.write("                background: linear-gradient(135deg, #1e7e34 0%, #17a2b8 100%);\n");
      out.write("                transform: translateY(-2px);\n");
      out.write("                box-shadow: 0 4px 15px rgba(0,0,0,0.2);\n");
      out.write("            }\n");
      out.write("            .btn-info-custom {\n");
      out.write("                background: linear-gradient(135deg, #17a2b8 0%, #6f42c1 100%);\n");
      out.write("                border: none;\n");
      out.write("                color: white;\n");
      out.write("            }\n");
      out.write("            .btn-info-custom:hover {\n");
      out.write("                background: linear-gradient(135deg, #138496 0%, #563d7c 100%);\n");
      out.write("                transform: translateY(-2px);\n");
      out.write("                box-shadow: 0 4px 15px rgba(0,0,0,0.2);\n");
      out.write("            }\n");
      out.write("            .main-title {\n");
      out.write("                background: linear-gradient(135deg, #2d5016 0%, #4a7c2a 100%);\n");
      out.write("                color: white;\n");
      out.write("                padding: 2rem;\n");
      out.write("                border-radius: 15px;\n");
      out.write("                margin: 2rem 0;\n");
      out.write("                text-align: center;\n");
      out.write("                box-shadow: 0 5px 20px rgba(0,0,0,0.1);\n");
      out.write("            }\n");
      out.write("            .main-title h1 {\n");
      out.write("                margin: 0;\n");
      out.write("                font-size: 1.8rem;\n");
      out.write("                font-weight: 700;\n");
      out.write("            }\n");
      out.write("            .stats-table {\n");
      out.write("                background: white;\n");
      out.write("                border-radius: 15px;\n");
      out.write("                overflow: hidden;\n");
      out.write("                box-shadow: 0 5px 20px rgba(0,0,0,0.1);\n");
      out.write("                margin: 2rem 0;\n");
      out.write("            }\n");
      out.write("            .table-custom {\n");
      out.write("                margin: 0;\n");
      out.write("            }\n");
      out.write("            .table-custom thead {\n");
      out.write("                background: linear-gradient(135deg, #28a745 0%, #20c997 100%);\n");
      out.write("                color: white;\n");
      out.write("            }\n");
      out.write("            .table-custom th {\n");
      out.write("                border: none;\n");
      out.write("                padding: 1rem;\n");
      out.write("                font-weight: 600;\n");
      out.write("            }\n");
      out.write("            .table-custom td {\n");
      out.write("                padding: 1rem;\n");
      out.write("                vertical-align: middle;\n");
      out.write("                border-bottom: 1px solid #e9ecef;\n");
      out.write("                color: #495057;\n");
      out.write("            }\n");
      out.write("            .table-custom tbody tr:hover {\n");
      out.write("                background-color: rgba(40, 167, 69, 0.05);\n");
      out.write("            }\n");
      out.write("            .chart-container {\n");
      out.write("                background: white;\n");
      out.write("                border-radius: 15px;\n");
      out.write("                padding: 1.5rem;\n");
      out.write("                margin: 2rem 0;\n");
      out.write("                box-shadow: 0 5px 20px rgba(0,0,0,0.1);\n");
      out.write("            }\n");
      out.write("            .analysis-text {\n");
      out.write("                background: white;\n");
      out.write("                border-radius: 15px;\n");
      out.write("                padding: 2rem;\n");
      out.write("                margin: 2rem 0;\n");
      out.write("                box-shadow: 0 5px 20px rgba(0,0,0,0.1);\n");
      out.write("                border-left: 5px solid #28a745;\n");
      out.write("            }\n");
      out.write("            .analysis-text p {\n");
      out.write("                color: #495057;\n");
      out.write("                font-size: 1.1rem;\n");
      out.write("                line-height: 1.6;\n");
      out.write("                margin-bottom: 1rem;\n");
      out.write("                text-align: justify;\n");
      out.write("            }\n");
      out.write("            .icon-stat {\n");
      out.write("                color: #28a745;\n");
      out.write("                margin-right: 0.5rem;\n");
      out.write("            }\n");
      out.write("            .value-highlight {\n");
      out.write("                color: #2d5016;\n");
      out.write("                font-weight: 700;\n");
      out.write("            }\n");
      out.write("            .stats-header {\n");
      out.write("                background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);\n");
      out.write("                padding: 1rem;\n");
      out.write("                border-bottom: 2px solid #28a745;\n");
      out.write("                text-align: center;\n");
      out.write("            }\n");
      out.write("            .stats-header h3 {\n");
      out.write("                margin: 0;\n");
      out.write("                color: #2d5016;\n");
      out.write("                font-weight: 700;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("        <script src=\"https://cdn.plot.ly/plotly-latest.min.js\"></script>\n");
      out.write("        <script>\n");
      out.write("            document.addEventListener('DOMContentLoaded', function () {\n");
      out.write("                window.location.hash = \"no-back-button\";\n");
      out.write("                window.location.hash = \"Again-No-back-button\";\n");
      out.write("                window.onhashchange = function () {\n");
      out.write("                    window.location.hash = \"\";\n");
      out.write("                };\n");
      out.write("            });\n");
      out.write("            Plotly.newPlot(\"rVM\", [{\n");
      out.write("                x: [");
      out.print( xVM );
      out.write("],\n");
      out.write("                y: [");
      out.print( yVM );
      out.write("],\n");
      out.write("                type: \"bar\",\n");
      out.write("                orientation: \"h\",\n");
      out.write("                marker: {\n");
      out.write("                    color: \"rgba(40, 167, 69, 0.8)\",\n");
      out.write("                    line: {\n");
      out.write("                        color: \"rgba(45, 80, 22, 1)\",\n");
      out.write("                        width: 1\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            }], {\n");
      out.write("                title: {\n");
      out.write("                    text: \"Ventas por Mes\",\n");
      out.write("                    font: {\n");
      out.write("                        color: \"#2d5016\",\n");
      out.write("                        size: 18\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                xaxis: {\n");
      out.write("                    title: \"Número de Ventas\",\n");
      out.write("                    color: \"#495057\"\n");
      out.write("                },\n");
      out.write("                yaxis: { color: \"#495057\" },\n");
      out.write("                plot_bgcolor: \"rgba(0,0,0,0)\",\n");
      out.write("                paper_bgcolor: \"rgba(0,0,0,0)\"\n");
      out.write("            });\n");
      out.write("            Plotly.newPlot(\"rDP\", [{\n");
      out.write("                labels: [");
      out.print( lDP );
      out.write("],\n");
      out.write("                values: [");
      out.print( vDP );
      out.write("],\n");
      out.write("                hole: 0.35,\n");
      out.write("                type: \"pie\",\n");
      out.write("                marker: {\n");
      out.write("                    colors: ['rgba(40, 167, 69, 0.8)', 'rgba(32, 201, 151, 0.8)', 'rgba(23, 162, 184, 0.8)', 'rgba(111, 66, 193, 0.8)', 'rgba(253, 126, 20, 0.8)']\n");
      out.write("                }\n");
      out.write("            }], {\n");
      out.write("                title: {\n");
      out.write("                    text: \"Distribución por Producto\",\n");
      out.write("                    font: {\n");
      out.write("                        color: \"#2d5016\",\n");
      out.write("                        size: 18\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                plot_bgcolor: \"rgba(0,0,0,0)\",\n");
      out.write("                paper_bgcolor: \"rgba(0,0,0,0)\"\n");
      out.write("            });\n");
      out.write("            Plotly.newPlot(\"rIAlT\", [{\n");
      out.write("                x: [");
      out.print( xIAlT );
      out.write("],\n");
      out.write("                y: [");
      out.print( yIAlT );
      out.write("],\n");
      out.write("                type: \"scatter\",\n");
      out.write("                mode: \"lines+markers\",\n");
      out.write("                line: {\n");
      out.write("                    color: \"rgba(40, 167, 69, 1)\",\n");
      out.write("                    width: 3\n");
      out.write("                },\n");
      out.write("                marker: {\n");
      out.write("                    color: \"rgba(45, 80, 22, 1)\",\n");
      out.write("                    size: 6\n");
      out.write("                }\n");
      out.write("            }], {\n");
      out.write("                title: {\n");
      out.write("                    text: \"Ingresos Acumulados a lo largo del Tiempo\",\n");
      out.write("                    font: {\n");
      out.write("                        color: \"#2d5016\",\n");
      out.write("                        size: 18\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                xaxis: {\n");
      out.write("                    title: \"Semanas\",\n");
      out.write("                    color: \"#495057\"\n");
      out.write("                },\n");
      out.write("                yaxis: {\n");
      out.write("                    title: \"Ingresos Acumulados\",\n");
      out.write("                    color: \"#495057\"\n");
      out.write("                },\n");
      out.write("                plot_bgcolor: \"rgba(0,0,0,0)\",\n");
      out.write("                paper_bgcolor: \"rgba(0,0,0,0)\"\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-custom\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"ms-auto\">\n");
      out.write("                    <a href=\"../Premium.jsp\" class=\"btn btn-custom btn-success-custom\">\n");
      out.write("                        <i class=\"fas fa-arrow-left\"></i>REGRESAR\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"ChatBot.jsp\" class=\"btn btn-custom btn-info-custom\">\n");
      out.write("                        <i class=\"fas fa-robot\"></i>Basil.IA\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"main-title\">\n");
      out.write("                <h1><i class=\"fas fa-chart-line me-3\"></i>Analista Estadístico-Predictivo de PlantiSHOP</h1>\n");
      out.write("                <p class=\"mb-0 mt-2\">Análisis de tus Actividades Comerciales y del Mercado Botánico General</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"stats-table\">\n");
      out.write("                <div class=\"stats-header\">\n");
      out.write("                    <h3><i class=\"fas fa-table me-2\"></i>Estadísticas Comparativas</h3>\n");
      out.write("                </div>\n");
      out.write("                <table class=\"table table-custom\">\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th scope=\"col\"></th>\n");
      out.write("                            <th scope=\"col\"><i class=\"fas fa-user icon-stat\"></i>Tus Medidas</th>\n");
      out.write("                            <th scope=\"col\"><i class=\"fas fa-globe icon-stat\"></i>Mercado General</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <th scope=\"row\"><i class=\"fas fa-dollar-sign icon-stat\"></i>Ventas Totales:</th>\n");
      out.write("                            <td class=\"value-highlight\">$ ");
      out.print( vt );
      out.write("</td>\n");
      out.write("                            <td class=\"value-highlight\">$ ");
      out.print( vtG );
      out.write("</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <th scope=\"row\"><i class=\"fas fa-crown icon-stat\"></i>Producto(s) más Vendido(s):</th>\n");
      out.write("                            <td>\n");
      out.write("                                <ul class=\"list-unstyled mb-0\">\n");
      out.write("                                    ");
      out.print( mo );
      out.write("\n");
      out.write("                                </ul>\n");
      out.write("                            </td>\n");
      out.write("                            <td>\n");
      out.write("                                <ul class=\"list-unstyled mb-0\">\n");
      out.write("                                    ");
      out.print( moG );
      out.write("\n");
      out.write("                                </ul>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <th scope=\"row\"><i class=\"fas fa-chart-up icon-stat\"></i>Ingresos:</th>\n");
      out.write("                            <td class=\"value-highlight\">+$ ");
      out.print( i );
      out.write("</td>\n");
      out.write("                            <td></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <th scope=\"row\"><i class=\"fas fa-calculator icon-stat\"></i>Promedio de Ventas:</th>\n");
      out.write("                            <td class=\"value-highlight\">$ ");
      out.print( x_md );
      out.write("</td>\n");
      out.write("                            <td class=\"value-highlight\">$ ");
      out.print( x_mdG );
      out.write("</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <th scope=\"row\"><i class=\"fas fa-balance-scale icon-stat\"></i>2° Promedio de Ventas:</th>\n");
      out.write("                            <td class=\"value-highlight\">$ ");
      out.print( g_h + (cv ? " (Geométrico)" : " (Armónico)") );
      out.write("</td>\n");
      out.write("                            <td class=\"value-highlight\">$ ");
      out.print( g_hG + (cvG ? " (Geométrico)" : " (Armónico)") );
      out.write("</td>\n");
      out.write("                        </tr>\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-12\">\n");
      out.write("                    <div class=\"chart-container\">\n");
      out.write("                        <div id=\"rVM\"></div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-6\">\n");
      out.write("                    <div class=\"chart-container\">\n");
      out.write("                        <div id=\"rDP\"></div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-6\">\n");
      out.write("                    <div class=\"chart-container\">\n");
      out.write("                        <div id=\"rIAlT\"></div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"analysis-text\">\n");
      out.write("                <h4><i class=\"fas fa-lightbulb icon-stat\"></i>Análisis Predictivo</h4>\n");
      out.write("                ");

                    if (sp > 0) {
                        out.print("<p>La Distribución de tus Ventas tiene una Tendencia Positiva, por lo que tus Índices de Venta son Altos y, probablemente, si Continúas con la Metodología Comercial que has estado Implementando, seguirás Obteniendo Buenas Ganancias en el Futuro Cercano 🌱</p>");
                    } else if (sp == 0) {
                        out.print("<p>La Distribución de tus Ventas es Normal y tus Índices de Venta están dentro de lo Ordinario, por lo que no hay Tendencias Significativas, así que tal vez Deberías de Revisar tu Metodología Comercial para que, de esta manera, Mejores tus Ganancias en el Futuro 🌿</p>");
                    } else {
                        out.print("<p>La Distribución de tus Ventas tiene una Tendencia Negativa, por lo que tus Índices de Venta son Bajos, así que Debes de Modificar tu Metodología Comercial Actual, tal vez Debas de Publicar otro Tipo de Productos, Hacerlos más Atractivos o Regular los Precios de tu Mercancía Actual, de esta manera, probablemente, Mejores tus Ganancias en el Futuro Cercano 📈</p>");
                    }
                    if (spG > 0) {
                        out.print("<p>En tanto, el Mercado de PlantiSHOP cuenta con Índices de Venta Altos, por lo que se Prevé que la Actividad Comercial del Futuro Cercano probablemente sea Segura y Productiva, así que Trata de Imitar las Tendencias del Mercado 🚀</p>");
                    } else if (spG == 0) {
                        out.print("<p>En tanto, el Mercado de PlantiSHOP presenta Índices de Venta Ordinarios, por lo que la Actividad Comercial se ha Mantenido Estable, Moderada y sin Tendencias Significativas, pero te Sugerimos Mantenerte Pendiente 👀</p>");
                    } else {
                        out.print("<p>En tanto, el Mercado de PlantiSHOP cuenta con Índices de Venta Bajos, por lo que se Prevé que la Actividad Comercial del Futuro Cercano probablemente sea Escasa e Inestable, así que, en la medida de lo posible, Cuida de tus Ingresos y Trata de Diseñar Metodologías de Venta que Impulsen tu Negocio, como Publicar Productos más Atractivos o Regular los Precios de tus Actuales Mercancías ⚠️</p>");
                    }
                
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
