/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-07-02 18:02:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.premium;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;

public final class ChatBot_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


    Connection c;
    Statement s;
    ResultSet r;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');

    try {
        Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
        c = DriverManager.getConnection("jdbc:mysql://localhost/PSHOP", "root", "n0m3l0");
        s = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        r = s.executeQuery("SELECT P FROM Usuario WHERE CE='"+session.getAttribute("u")+"'");
        r.next();
        if (!r.getBoolean(1)) {
            out.print("<script>alert('Lo sentimos, NO eres un Usuario PREMIUM... por lo que NO puedes hacer uso de este APARTADO...');</script>");
            out.print("<script>location.assign('../index.html');</script>");
        }
        r.close();
        s.close();
        c.close();
    } catch (Exception e) {
        out.print("<script>alert('Lo sentimos, se produjo un ERROR... intentalo de NUEVO...');</script>");
        out.print("<script>history.back();</script>");
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es-MX\">\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>IA</title>\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"../imgs/logo.png\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("        <style>\n");
      out.write("            :root {\n");
      out.write("                --primary-green: #2d5016;\n");
      out.write("                --secondary-green: #4a7c28;\n");
      out.write("                --accent-green: #6ca83c;\n");
      out.write("                --light-green: #8bc34a;\n");
      out.write("                --pale-green: #c8e6c9;\n");
      out.write("                --earth-brown: #5d4037;\n");
      out.write("                --warm-beige: #8d6e63;\n");
      out.write("                --background-color: #f0f0f0;\n");
      out.write("                --ai-cyan: #00bcd4;\n");
      out.write("                --ai-cyan-dark: #0097a7;\n");
      out.write("                --analytics-orange: #ff9800;\n");
      out.write("                --analytics-orange-dark: #f57c00;\n");
      out.write("            }\n");
      out.write("            body {\n");
      out.write("                background-color: var(--background-color) !important;\n");
      out.write("                font-family: 'Poppins', sans-serif;\n");
      out.write("                color: var(--primary-green);\n");
      out.write("                min-height: 100vh;\n");
      out.write("            }\n");
      out.write("            .navigation-bar {\n");
      out.write("                background: linear-gradient(135deg, var(--primary-green) 0%, var(--secondary-green) 100%);\n");
      out.write("                padding: 1rem 0;\n");
      out.write("                margin-bottom: 2rem;\n");
      out.write("                box-shadow: 0 4px 15px rgba(45, 80, 22, 0.3);\n");
      out.write("            }\n");
      out.write("            .btn-nav {\n");
      out.write("                background: linear-gradient(135deg, var(--accent-green) 0%, var(--light-green) 100%);\n");
      out.write("                border: none;\n");
      out.write("                color: white;\n");
      out.write("                font-weight: 600;\n");
      out.write("                padding: 0.75rem 1.5rem;\n");
      out.write("                border-radius: 25px;\n");
      out.write("                transition: all 0.3s ease;\n");
      out.write("                box-shadow: 0 4px 15px rgba(108, 168, 60, 0.4);\n");
      out.write("                margin: 0 0.5rem;\n");
      out.write("            }\n");
      out.write("            .btn-nav:hover {\n");
      out.write("                background: linear-gradient(135deg, var(--light-green) 0%, var(--accent-green) 100%);\n");
      out.write("                transform: translateY(-2px);\n");
      out.write("                box-shadow: 0 6px 20px rgba(108, 168, 60, 0.6);\n");
      out.write("                color: white;\n");
      out.write("            }\n");
      out.write("            .btn-analytics {\n");
      out.write("                background: linear-gradient(135deg, var(--analytics-orange) 0%, var(--analytics-orange-dark) 100%);\n");
      out.write("                box-shadow: 0 4px 15px rgba(255, 152, 0, 0.4);\n");
      out.write("            }\n");
      out.write("            .btn-analytics:hover {\n");
      out.write("                background: linear-gradient(135deg, var(--analytics-orange-dark) 0%, #e65100 100%);\n");
      out.write("                box-shadow: 0 6px 20px rgba(255, 152, 0, 0.6);\n");
      out.write("            }\n");
      out.write("            .basil-header {\n");
      out.write("                background: linear-gradient(135deg, var(--ai-cyan) 0%, var(--ai-cyan-dark) 100%);\n");
      out.write("                color: white;\n");
      out.write("                padding: 2rem;\n");
      out.write("                border-radius: 20px;\n");
      out.write("                margin-bottom: 2rem;\n");
      out.write("                box-shadow: 0 8px 25px rgba(0, 188, 212, 0.3);\n");
      out.write("                text-align: center;\n");
      out.write("            }\n");
      out.write("            .basil-avatar {\n");
      out.write("                width: 150px;\n");
      out.write("                height: 150px;\n");
      out.write("                border-radius: 50%;\n");
      out.write("                border: 5px solid white;\n");
      out.write("                box-shadow: 0 8px 25px rgba(0, 0, 0, 0.2);\n");
      out.write("                margin-bottom: 1rem;\n");
      out.write("                object-fit: cover;\n");
      out.write("            }\n");
      out.write("            .basil-title {\n");
      out.write("                font-size: 2.5rem;\n");
      out.write("                font-weight: 700;\n");
      out.write("                margin-bottom: 0.5rem;\n");
      out.write("                text-shadow: 2px 2px 4px rgba(0,0,0,0.3);\n");
      out.write("            }\n");
      out.write("            .basil-subtitle {\n");
      out.write("                font-size: 1.2rem;\n");
      out.write("                opacity: 0.9;\n");
      out.write("                margin-bottom: 0;\n");
      out.write("            }\n");
      out.write("            .chat-container {\n");
      out.write("                background: white;\n");
      out.write("                border-radius: 20px;\n");
      out.write("                padding: 2rem;\n");
      out.write("                margin-bottom: 2rem;\n");
      out.write("                box-shadow: 0 8px 25px rgba(45, 80, 22, 0.1);\n");
      out.write("                border: 2px solid var(--pale-green);\n");
      out.write("            }\n");
      out.write("            .basil-response {\n");
      out.write("                background: linear-gradient(135deg, #e0f7fa 0%, #b2ebf2 100%);\n");
      out.write("                border-left: 5px solid var(--ai-cyan);\n");
      out.write("                border-radius: 15px;\n");
      out.write("                padding: 1.5rem;\n");
      out.write("                margin-bottom: 2rem;\n");
      out.write("                font-size: 1.1rem;\n");
      out.write("                line-height: 1.6;\n");
      out.write("                position: relative;\n");
      out.write("            }\n");
      out.write("            .basil-response::before {\n");
      out.write("                content: \"\\f4ad\";\n");
      out.write("                font-family: \"Bootstrap Icons\";\n");
      out.write("                position: absolute;\n");
      out.write("                top: -10px;\n");
      out.write("                left: 20px;\n");
      out.write("                background: var(--ai-cyan);\n");
      out.write("                color: white;\n");
      out.write("                padding: 8px;\n");
      out.write("                border-radius: 50%;\n");
      out.write("                font-size: 1rem;\n");
      out.write("            }\n");
      out.write("            .input-section {\n");
      out.write("                background: white;\n");
      out.write("                border-radius: 20px;\n");
      out.write("                padding: 2rem;\n");
      out.write("                margin-bottom: 2rem;\n");
      out.write("                box-shadow: 0 8px 25px rgba(45, 80, 22, 0.1);\n");
      out.write("                border: 2px solid var(--pale-green);\n");
      out.write("            }\n");
      out.write("            .form-control {\n");
      out.write("                border: 2px solid var(--pale-green);\n");
      out.write("                border-radius: 15px;\n");
      out.write("                padding: 1rem;\n");
      out.write("                font-size: 1rem;\n");
      out.write("                transition: all 0.3s ease;\n");
      out.write("                resize: vertical;\n");
      out.write("                min-height: 120px;\n");
      out.write("            }\n");
      out.write("            .form-control:focus {\n");
      out.write("                border-color: var(--ai-cyan);\n");
      out.write("                box-shadow: 0 0 0 0.2rem rgba(0, 188, 212, 0.25);\n");
      out.write("            }\n");
      out.write("            .btn-send {\n");
      out.write("                background: linear-gradient(135deg, var(--ai-cyan) 0%, var(--ai-cyan-dark) 100%);\n");
      out.write("                border: none;\n");
      out.write("                color: white;\n");
      out.write("                font-weight: 600;\n");
      out.write("                padding: 1rem 2rem;\n");
      out.write("                border-radius: 50px;\n");
      out.write("                font-size: 1.1rem;\n");
      out.write("                transition: all 0.3s ease;\n");
      out.write("                box-shadow: 0 4px 15px rgba(0, 188, 212, 0.4);\n");
      out.write("                width: 100%;\n");
      out.write("                margin-top: 1rem;\n");
      out.write("            }\n");
      out.write("            .btn-send:hover {\n");
      out.write("                background: linear-gradient(135deg, var(--ai-cyan-dark) 0%, #006064 100%);\n");
      out.write("                transform: translateY(-2px);\n");
      out.write("                box-shadow: 0 6px 20px rgba(0, 188, 212, 0.6);\n");
      out.write("                color: white;\n");
      out.write("            }\n");
      out.write("            .image-search-section {\n");
      out.write("                background: white;\n");
      out.write("                border-radius: 20px;\n");
      out.write("                padding: 2rem;\n");
      out.write("                box-shadow: 0 8px 25px rgba(45, 80, 22, 0.1);\n");
      out.write("                border: 2px solid var(--pale-green);\n");
      out.write("            }\n");
      out.write("            .file-input-container {\n");
      out.write("                background: linear-gradient(135deg, var(--pale-green) 0%, #e8f5e8 100%);\n");
      out.write("                border: 3px dashed var(--accent-green);\n");
      out.write("                border-radius: 15px;\n");
      out.write("                padding: 2rem;\n");
      out.write("                text-align: center;\n");
      out.write("                margin-bottom: 1.5rem;\n");
      out.write("                transition: all 0.3s ease;\n");
      out.write("            }\n");
      out.write("            .file-input-container:hover {\n");
      out.write("                background: linear-gradient(135deg, var(--light-green) 0%, var(--accent-green) 100%);\n");
      out.write("                color: white;\n");
      out.write("            }\n");
      out.write("            .form-control[type=\"file\"] {\n");
      out.write("                border: none;\n");
      out.write("                background: transparent;\n");
      out.write("                padding: 1rem;\n");
      out.write("                font-size: 1rem;\n");
      out.write("                color: var(--primary-green);\n");
      out.write("                font-weight: 500;\n");
      out.write("            }\n");
      out.write("            .btn-plant-search {\n");
      out.write("                background: linear-gradient(135deg, var(--accent-green) 0%, var(--light-green) 100%);\n");
      out.write("                border: none;\n");
      out.write("                color: white;\n");
      out.write("                font-weight: 600;\n");
      out.write("                padding: 1rem 2rem;\n");
      out.write("                border-radius: 50px;\n");
      out.write("                font-size: 1.1rem;\n");
      out.write("                transition: all 0.3s ease;\n");
      out.write("                box-shadow: 0 4px 15px rgba(108, 168, 60, 0.4);\n");
      out.write("                width: 100%;\n");
      out.write("            }\n");
      out.write("            .btn-plant-search:hover {\n");
      out.write("                background: linear-gradient(135deg, var(--light-green) 0%, var(--accent-green) 100%);\n");
      out.write("                transform: translateY(-2px);\n");
      out.write("                box-shadow: 0 6px 20px rgba(108, 168, 60, 0.6);\n");
      out.write("                color: white;\n");
      out.write("            }\n");
      out.write("            .section-title {\n");
      out.write("                color: var(--primary-green);\n");
      out.write("                font-weight: 700;\n");
      out.write("                margin-bottom: 1rem;\n");
      out.write("                display: flex;\n");
      out.write("                align-items: center;\n");
      out.write("                gap: 0.5rem;\n");
      out.write("            }\n");
      out.write("            .feature-icon {\n");
      out.write("                font-size: 1.5rem;\n");
      out.write("                color: var(--ai-cyan);\n");
      out.write("            }\n");
      out.write("            .plant-icon {\n");
      out.write("                font-size: 1.5rem;\n");
      out.write("                color: var(--accent-green);\n");
      out.write("            }\n");
      out.write("            @media (max-width: 768px) {\n");
      out.write("                .basil-title {\n");
      out.write("                    font-size: 2rem;\n");
      out.write("                }\n");
      out.write("                .basil-avatar {\n");
      out.write("                    width: 120px;\n");
      out.write("                    height: 120px;\n");
      out.write("                }\n");
      out.write("                .btn-nav {\n");
      out.write("                    font-size: 0.9rem;\n");
      out.write("                    padding: 0.5rem 1rem;\n");
      out.write("                    margin: 0.25rem;\n");
      out.write("                }\n");
      out.write("                .chat-container,\n");
      out.write("                .input-section,\n");
      out.write("                .image-search-section {\n");
      out.write("                    padding: 1.5rem;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("        <script>\n");
      out.write("            document.addEventListener('DOMContentLoaded', function () {\n");
      out.write("                window.location.hash = \"no-back-button\";\n");
      out.write("                window.location.hash = \"Again-No-back-button\";\n");
      out.write("                window.onhashchange = function () {\n");
      out.write("                    window.location.hash = \"\";\n");
      out.write("                };\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <div class=\"navigation-bar\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"text-end\">\n");
      out.write("                        <button class=\"btn btn-nav\" onclick=\"location.assign('../Premium.jsp')\">\n");
      out.write("                            <i class=\"bi bi-arrow-left me-2\">REGRESAR</i>\n");
      out.write("                        </button>\n");
      out.write("                        <button class=\"btn btn-nav btn-analytics\" onclick=\"location.assign('Analisis.jsp')\">\n");
      out.write("                            <i class=\"bi bi-graph-up me-2\">IR AL ANALISTA</i>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"basil-header\">\n");
      out.write("                    <img src=\"../imgs/ia.jpg\" alt=\"Basil.IA\" class=\"basil-avatar\"/>\n");
      out.write("                    <h1 class=\"basil-title\">Basil.IA</h1>\n");
      out.write("                    <p class=\"basil-subtitle\">Tu Asistente Personal de Jardinería</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"chat-container\">\n");
      out.write("                    <div class=\"basil-response\">\n");
      out.write("                        ");

                            if (session.getAttribute("rIA") == null) {
                                out.print("¡Hola! Soy Basil.IA, tu Asistente Personal de Jardinería... Dime ¿En qué te puedo Ayudar?");
                            } else {
                                out.print(session.getAttribute("rIA"));
                                session.removeAttribute("rIA");
                            }
                        
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-lg-6 mb-4\">\n");
      out.write("                        <div class=\"input-section\">\n");
      out.write("                            <h3 class=\"section-title\">\n");
      out.write("                                <i class=\"bi bi-chat-dots feature-icon\">Preguntas o Solicitudes a Basil.IA</i>\n");
      out.write("                            </h3>\n");
      out.write("                            <form action=\"../BasilIA\" method=\"post\">\n");
      out.write("                                <input name=\"x\" type=\"hidden\" value=\"true\">\n");
      out.write("                                <div class=\"mb-3\">\n");
      out.write("                                    <label for=\"question\" class=\"form-label\">Haz una consulta sobre Jardinería:</label>\n");
      out.write("                                    <textarea id=\"question\" name=\"req\" class=\"form-control\"\n");
      out.write("                                              placeholder=\"¿Cómo Cuidar mis Plantas?&NewLine;¿Qué Fertilizante debo Usar?&NewLine;¿Cuándo hay que Regar?\"\n");
      out.write("                                              required></textarea>\n");
      out.write("                                </div>\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-send\">\n");
      out.write("                                    <i class=\"bi bi-send me-2\">ENVIAR</i>\n");
      out.write("                                </button>\n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-6 mb-4\">\n");
      out.write("                        <div class=\"image-search-section\">\n");
      out.write("                            <h3 class=\"section-title\">\n");
      out.write("                                <i class=\"bi bi-camera plant-icon\">Identificación de Plantas mediante Imagenes</i>\n");
      out.write("                            </h3>\n");
      out.write("                            <form action=\"../BasilIA\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("                                <input name=\"x\" type=\"hidden\" value=\"false\">\n");
      out.write("                                <div class=\"mb-3\">\n");
      out.write("                                    <label for=\"plantImage\" class=\"form-label\">Sube una imagen de la Planta:</label>\n");
      out.write("                                    <div class=\"file-input-container\">\n");
      out.write("                                        <i class=\"bi bi-cloud-upload plant-icon mb-2\"></i>\n");
      out.write("                                        <p class=\"mb-2\">Selecciona una Imagen JPEG</p>\n");
      out.write("                                        <input id=\"plantImage\" name=\"img\" type=\"file\" class=\"form-control\"\n");
      out.write("                                               accept=\"image/jpeg\" required>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-plant-search\">\n");
      out.write("                                    <i class=\"bi bi-search me-2\">BUSCAR</i>\n");
      out.write("                                </button>\n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row mt-4\">\n");
      out.write("                    <div class=\"col-12\">\n");
      out.write("                        <div class=\"chat-container\">\n");
      out.write("                            <div class=\"row text-center\">\n");
      out.write("                                <div class=\"col-md-4 mb-3\">\n");
      out.write("                                    <i class=\"bi bi-lightbulb feature-icon mb-2\"></i>\n");
      out.write("                                    <h5 style=\"color: var(--primary-green);\">Consejos Personalizados</h5>\n");
      out.write("                                    <p class=\"text-muted\">Recibe recomendaciones específicas para tus Plantas :3</p>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-md-4 mb-3\">\n");
      out.write("                                    <i class=\"bi bi-camera feature-icon mb-2\"></i>\n");
      out.write("                                    <h5 style=\"color: var(--primary-green);\">Identificación Visual</h5>\n");
      out.write("                                    <p class=\"text-muted\">Identifica plantas mediante Fotografías JPEG</p>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-md-4 mb-3\">\n");
      out.write("                                    <i class=\"bi bi-chat-heart feature-icon mb-2\"></i>\n");
      out.write("                                    <h5 style=\"color: var(--primary-green);\">Asistencia 24/7</h5>\n");
      out.write("                                    <p class=\"text-muted\">Disponible cuando lo necesites ;3</p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
