/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-07-02 17:58:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import auxs.Cortes;
import auxs.Epistula;
import auxs.Hash;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.io.File;
import java.io.FileWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public final class Interfaz_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


    Connection c;
    Statement s;
    ResultSet r;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(11);
    _jspx_imports_classes.add("auxs.Cortes");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("auxs.Hash");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.io.FileWriter");
    _jspx_imports_classes.add("java.time.LocalDateTime");
    _jspx_imports_classes.add("auxs.Epistula");
    _jspx_imports_classes.add("java.sql.DriverManager");
    _jspx_imports_classes.add("java.io.File");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es-MX\">\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>O</title>\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"imgs/logo.png\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" rel=\"stylesheet\">\n");
      out.write("        <style>\n");
      out.write("            body {\n");
      out.write("                background-image: url(imgs/fondo2.jpg);\n");
      out.write("                min-height: 100vh;\n");
      out.write("                display: flex;\n");
      out.write("                align-items: center;\n");
      out.write("                justify-content: center;\n");
      out.write("                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("                margin: 0;\n");
      out.write("                padding: 20px;\n");
      out.write("                box-sizing: border-box;\n");
      out.write("            }\n");
      out.write("            .success-container {\n");
      out.write("                background: white;\n");
      out.write("                border-radius: 20px;\n");
      out.write("                box-shadow: 0 15px 35px rgba(0, 0, 0, 0.1);\n");
      out.write("                padding: 40px;\n");
      out.write("                max-width: 800px;\n");
      out.write("                width: 100%;\n");
      out.write("                transform: translateY(0);\n");
      out.write("                animation: slideUp 0.6s ease-out;\n");
      out.write("                border: 1px solid #e9ecef;\n");
      out.write("            }\n");
      out.write("            @keyframes slideUp {\n");
      out.write("                from {\n");
      out.write("                    opacity: 0;\n");
      out.write("                    transform: translateY(30px);\n");
      out.write("                }\n");
      out.write("                to {\n");
      out.write("                    opacity: 1;\n");
      out.write("                    transform: translateY(0);\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            .success-content {\n");
      out.write("                display: flex;\n");
      out.write("                align-items: center;\n");
      out.write("                gap: 30px;\n");
      out.write("            }\n");
      out.write("            .success-text {\n");
      out.write("                flex: 1;\n");
      out.write("            }\n");
      out.write("            .success-title {\n");
      out.write("                color: #495057;\n");
      out.write("                font-weight: 600;\n");
      out.write("                font-size: 2.5rem;\n");
      out.write("                margin: 0;\n");
      out.write("                white-space: nowrap;\n");
      out.write("                line-height: 1.2;\n");
      out.write("            }\n");
      out.write("            .success-subtitle {\n");
      out.write("                color: #6c757d;\n");
      out.write("                font-weight: 500;\n");
      out.write("                font-size: 1.4rem;\n");
      out.write("                margin: 15px 0 0 0;\n");
      out.write("                white-space: nowrap;\n");
      out.write("            }\n");
      out.write("            .success-image {\n");
      out.write("                max-width: 200px;\n");
      out.write("                height: auto;\n");
      out.write("                border-radius: 15px;\n");
      out.write("                box-shadow: 0 8px 25px rgba(0, 0, 0, 0.15);\n");
      out.write("                transition: transform 0.3s ease;\n");
      out.write("            }\n");
      out.write("            .success-image:hover {\n");
      out.write("                transform: scale(1.05);\n");
      out.write("            }\n");
      out.write("            .success-container::before {\n");
      out.write("                content: '';\n");
      out.write("                position: absolute;\n");
      out.write("                top: -1px;\n");
      out.write("                left: -1px;\n");
      out.write("                right: -1px;\n");
      out.write("                bottom: -1px;\n");
      out.write("                background: linear-gradient(135deg, #6c757d, #adb5bd);\n");
      out.write("                border-radius: 21px;\n");
      out.write("                z-index: -1;\n");
      out.write("                opacity: 0.3;\n");
      out.write("            }\n");
      out.write("            .success-container {\n");
      out.write("                position: relative;\n");
      out.write("            }\n");
      out.write("            @media (max-width: 768px) {\n");
      out.write("                .success-content {\n");
      out.write("                    flex-direction: column;\n");
      out.write("                    text-align: center;\n");
      out.write("                    gap: 20px;\n");
      out.write("                }\n");
      out.write("                .success-title {\n");
      out.write("                    font-size: 1.8rem;\n");
      out.write("                    white-space: normal;\n");
      out.write("                }\n");
      out.write("                .success-subtitle {\n");
      out.write("                    font-size: 1.2rem;\n");
      out.write("                    white-space: normal;\n");
      out.write("                }\n");
      out.write("                .success-image {\n");
      out.write("                    max-width: 150px;\n");
      out.write("                }\n");
      out.write("                .success-container {\n");
      out.write("                    padding: 30px 20px;\n");
      out.write("                    max-width: 90%;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            @media (max-width: 480px) {\n");
      out.write("                .success-title {\n");
      out.write("                    font-size: 1.5rem;\n");
      out.write("                    white-space: normal;\n");
      out.write("                }\n");
      out.write("                .success-subtitle {\n");
      out.write("                    font-size: 1.1rem;\n");
      out.write("                    white-space: normal;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            .success-container::after {\n");
      out.write("                content: '';\n");
      out.write("                position: absolute;\n");
      out.write("                top: 20px;\n");
      out.write("                right: 20px;\n");
      out.write("                width: 80px;\n");
      out.write("                height: 80px;\n");
      out.write("                background: radial-gradient(circle, rgba(108, 117, 125, 0.1) 0%, transparent 70%);\n");
      out.write("                border-radius: 50%;\n");
      out.write("                z-index: -1;\n");
      out.write("            }\n");
      out.write("            .verification-container {\n");
      out.write("                min-height: 100vh;\n");
      out.write("                display: flex;\n");
      out.write("                align-items: center;\n");
      out.write("                justify-content: center;\n");
      out.write("            }\n");
      out.write("            .verification-card {\n");
      out.write("                max-width: 600px;\n");
      out.write("                width: 100%;\n");
      out.write("                padding: 3rem;\n");
      out.write("                border-radius: 15px;\n");
      out.write("                box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);\n");
      out.write("                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("                color: white;\n");
      out.write("            }\n");
      out.write("            .verification-title {\n");
      out.write("                font-size: 1.5rem;\n");
      out.write("                font-weight: 600;\n");
      out.write("                margin-bottom: 2rem;\n");
      out.write("                text-align: center;\n");
      out.write("                line-height: 1.4;\n");
      out.write("            }\n");
      out.write("            .code-input {\n");
      out.write("                font-size: 1.2rem;\n");
      out.write("                padding: 1rem;\n");
      out.write("                border: none;\n");
      out.write("                border-radius: 10px;\n");
      out.write("                text-align: center;\n");
      out.write("                letter-spacing: 0.2em;\n");
      out.write("                font-weight: 500;\n");
      out.write("                margin-bottom: 2rem;\n");
      out.write("                box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);\n");
      out.write("                transition: all 0.3s ease;\n");
      out.write("            }\n");
      out.write("            .code-input:focus {\n");
      out.write("                outline: none;\n");
      out.write("                box-shadow: 0 8px 25px rgba(255, 255, 255, 0.2);\n");
      out.write("                transform: translateY(-2px);\n");
      out.write("            }\n");
      out.write("            .submit-btn {\n");
      out.write("                font-size: 1.1rem;\n");
      out.write("                font-weight: 600;\n");
      out.write("                padding: 1rem 2rem;\n");
      out.write("                border: none;\n");
      out.write("                border-radius: 10px;\n");
      out.write("                background: linear-gradient(45deg, #ff6b6b, #ee5a24);\n");
      out.write("                color: white;\n");
      out.write("                text-transform: uppercase;\n");
      out.write("                letter-spacing: 0.5px;\n");
      out.write("                transition: all 0.3s ease;\n");
      out.write("                box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);\n");
      out.write("            }\n");
      out.write("            .submit-btn:hover {\n");
      out.write("                transform: translateY(-3px);\n");
      out.write("                box-shadow: 0 8px 25px rgba(0, 0, 0, 0.3);\n");
      out.write("                background: linear-gradient(45deg, #ee5a24, #ff6b6b);\n");
      out.write("            }\n");
      out.write("            .submit-btn:active {\n");
      out.write("                transform: translateY(-1px);\n");
      out.write("            }\n");
      out.write("            @media (max-width: 768px) {\n");
      out.write("                .verification-card {\n");
      out.write("                    padding: 2rem;\n");
      out.write("                    margin: 1rem;\n");
      out.write("                }\n");
      out.write("                .verification-title {\n");
      out.write("                    font-size: 1.3rem;\n");
      out.write("                }\n");
      out.write("                .code-input {\n");
      out.write("                    font-size: 1rem;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("        <script>\n");
      out.write("            document.addEventListener('DOMContentLoaded', function () {\n");
      out.write("                window.location.hash = \"no-back-button\";\n");
      out.write("                window.location.hash = \"Again-No-back-button\";\n");
      out.write("                window.onhashchange = function () {\n");
      out.write("                    window.location.hash = \"no-back-button\";\n");
      out.write("                };\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");

            try {
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
                c = DriverManager.getConnection("jdbc:mysql://localhost/PSHOP", "root", "n0m3l0");
                s = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                switch (request.getParameter("x")) {
                    case "C": {
                        r = s.executeQuery("SELECT CE FROM Usuario WHERE CE='"+request.getParameter("ce")+"'");
                        if (r.next()) {
                            out.print("<div class='success-container'>");
                                out.print("<div class='success-content'>");
                                    out.print("<h1 class='success-title'>Registro INVALIDO</h1>");
                                    out.print("<img src='imgs/err.png' alt='E' class='success-image'/>");
                                out.print("</div>");
                            out.print("</div>");
                            out.print("<script>setTimeout(function () { location.assign('Registro.jsp'); }, 5000);</script>");
                        } else {
                            Epistula e = new Epistula();
                            e.eMail(request.getParameter("ce"), "Nuevo REGISTRO", "¡Bienvenido a PlantiSHOP!");
                            Hash h = new Hash();
                            s.executeUpdate("INSERT INTO Usuario(CE,C1,C2,N,AP,AM,U) VALUES ('"+request.getParameter("ce")+"','"+h.hashSHA256(request.getParameter("c1"))+"','"+h.hashSHA256(request.getParameter("c2"))+"','"+request.getParameter("n")+"','"+request.getParameter("ap")+"','"+request.getParameter("am")+"','"+request.getParameter("u")+"')");
                            out.print("<div class='success-container'>");
                                out.print("<div class='success-content'>");
                                    out.print("<h1 class='success-title'>Usuario correctamente REGISTRADO</h1>");
                                    out.print("<img src='imgs/csql.png' alt='C' class='success-image'/>");
                                out.print("</div>");
                            out.print("</div>");
                            out.print("<script>setTimeout(function () { location.assign('Sesion.html'); }, 5000);</script>");
                            s.execute("COMMIT");
                        }
                        r.close();
                    } break;
                    case "Cj": {
                        r = s.executeQuery("SELECT Id FROM Jardin WHERE CE='"+session.getAttribute("u")+"' AND N='"+request.getParameter("n")+"'");
                        if (r.next()) {
                            out.print("<div class='success-container'>");
                                out.print("<div class='success-content'>");
                                    out.print("<h1 class='success-title'>Registro INVALIDO</h1>");
                                    out.print("<img src='imgs/err.png' alt='E' class='success-image'/>");
                                out.print("</div>");
                            out.print("</div>");
                        } else {
                            s.executeUpdate("INSERT INTO Jardin(CE,N,T,C,L,P) VALUES ('"+session.getAttribute("u")+"','"+request.getParameter("n")+"','"+request.getParameter("t")+"',"+((request.getParameter("txt") == null) ? "NULL" : "'"+request.getParameter("txt")+"'")+","+request.getParameter("l")+","+request.getParameter("p")+")");
                            out.print("<div class='success-container'>");
                                out.print("<div class='success-content'>");
                                    out.print("<h1 class='success-title'>Elemento correctamente REGISTRADO</h1>");
                                    out.print("<img src='imgs/csql.png' alt='C' class='success-image'/>");
                                out.print("</div>");
                            out.print("</div>");
                            s.execute("COMMIT");
                        }
                        out.print("<script>setTimeout(function () { location.assign('Jardin.jsp'); }, 5000);</script>");
                        r.close();
                    } break;
                    case "R": {
                        r = s.executeQuery("SELECT FhN1,FhN2,I1,I2,C1,C2,FfS FROM Usuario WHERE CE='"+request.getParameter("ce")+"'");
                        if (r.next() && !r.next()) {
                            r.first();
                            if (r.getTimestamp(1) != null) { if (r.getTimestamp(1).toLocalDateTime().isBefore(LocalDateTime.now())) { s.executeUpdate("UPDATE Usuario SET I1=5,FhN1=NULL WHERE CE='"+request.getParameter("ce")+"'"); } }
                            if (r.getTimestamp(2) != null) { if (r.getTimestamp(2).toLocalDateTime().isBefore(LocalDateTime.now())) { s.executeUpdate("UPDATE Usuario SET I2=2,FhN2=NULL WHERE CE='"+request.getParameter("ce")+"'"); } }
                            if (r.getDate(7) != null) { if (r.getDate(7).toLocalDate().isBefore(LocalDateTime.now().toLocalDate())) { s.executeUpdate("UPDATE Usuario SET P=FALSE,FfS=NULL WHERE CE='"+request.getParameter("ce")+"'"); } }
                            if (r.getByte(3) > 0 && r.getByte(4) > 0) {
                                Hash h = new Hash();
                                if (r.getString(5).equals(h.hashSHA256(request.getParameter("c1"))) && r.getString(6).equals(h.hashSHA256(request.getParameter("c2")))) {
                                    Cortes v = new Cortes();
                                    String cV = v.cV();
                                    s.executeUpdate("UPDATE Usuario SET CV='"+cV+"' WHERE CE='"+request.getParameter("ce")+"'");
                                    Epistula e = new Epistula();
                                    e.eMail(request.getParameter("ce"), "Código de Verificación", cV);
                                    out.print("<div class='container-fluid verification-container'>");
                                        out.print("<div class='verification-card'>");
                                            out.print("<form action='Interfaz.jsp' method='post' class='text-center'>");
                                                out.print("<input name='x' type='hidden' value='R2'>");
                                                out.print("<input name='ce' type='hidden' value='"+request.getParameter("ce")+"'>");
                                                out.print("<h1 class='verification-title'>Para Acceder, ingresa el Codigo de Verificación de 10 Digitos que enviamos a tu Correo Electronico:</h1>");
                                                out.print("<div class='mb-4'><input name='cv' class='form-control code-input' type='text' pattern='[0-9+.*/A-Z]{10}' maxlength='10' placeholder='----------' required></div>");
                                                out.print("<div class='d-grid'><input type='submit' value='ACCEDER' class='btn submit-btn'></div>");
                                            out.print("</form>");
                                        out.print("</div>");
                                    out.print("</div>");
                                } else {
                                    if (r.getByte(3) == 1) { s.executeUpdate("UPDATE Usuario SET FhN1='"+LocalDateTime.now().plusDays(1L).format(DateTimeFormatter.ofPattern("uuuu-MM-dd HH:mm:ss"))+"' WHERE CE='"+request.getParameter("ce")+"'"); }
                                    byte menos = ((byte) (r.getByte(3) - 1));
                                    s.executeUpdate("UPDATE Usuario SET I1="+menos+" WHERE CE='"+request.getParameter("ce")+"'");
                                    out.print("<div class='success-container'>");
                                        out.print("<div class='success-content'>");
                                            out.print("<div class='success-text'>");
                                                out.print("<h1 class='success-title'>Contraseña(s) INCORRECTA(S)</h1>");
                                                out.print("<h3 class='success-subtitle'>Intentos RESTANTES: "+menos+"</h3>");
                                            out.print("</div>");
                                            out.print("<img src='imgs/err.png' alt='E' class='success-image'/>");
                                        out.print("</div>");
                                    out.print("</div>");
                                    out.print("<script>setTimeout(function () { location.assign('Sesion.html'); }, 5000);</script>");
                                }
                                s.execute("COMMIT");
                            } else {
                                out.print("<div class='success-container'>");
                                    out.print("<div class='success-content'>");
                                        out.print("<h1 class='success-title'>Usuario INVALIDO</h1>");
                                        out.print("<img src='imgs/err.png' alt='E' class='success-image'/>");
                                    out.print("</div>");
                                out.print("</div>");
                                out.print("<script>setTimeout(function () { location.assign('Sesion.html'); }, 5000);</script>");
                            }
                        } else {
                            out.print("<div class='success-container'>");
                                out.print("<div class='success-content'>");
                                    out.print("<h1 class='success-title'>Usuario No REGISTRADO</h1>");
                                    out.print("<img src='imgs/err.png' alt='E' class='success-image'/>");
                                out.print("</div>");
                            out.print("</div>");
                            out.print("<script>setTimeout(function () { location.assign('Sesion.html'); }, 5000);</script>");
                        }
                        r.close();
                    } break;
                    case "R2": {
                        r = s.executeQuery("SELECT CV,I2 FROM Usuario WHERE CE='"+request.getParameter("ce")+"'");
                        r.next();
                        if (request.getParameter("cv").equals(r.getString(1))) {
                            session.setAttribute("u", request.getParameter("ce"));
                            s.executeUpdate("UPDATE Usuario SET CV=NULL,I1=5,FhN1=NULL,I2=2,FhN2=NULL WHERE CE='"+request.getParameter("ce")+"'");
                            out.print("<div class='success-container'>");
                                out.print("<div class='success-content'>");
                                    out.print("<h1 class='success-title'>¡Bienvenido a PlantiSHOP!</h1>");
                                    out.print("<img src='imgs/rsql.png' alt='R' class='success-image'/>");
                                out.print("</div>");
                            out.print("</div>");
                            out.print("<script>setTimeout(function () { location.assign('"+((!request.getParameter("ce").equals("alonmc237@gmail.com") && !request.getParameter("ce").equals("fernandomarlon2007.1976@gmail.com") && !request.getParameter("ce").equals("juanpagon16@gmail.com") && !request.getParameter("ce").equals("agarciagael93@gmail.com")) ? "Perfil.jsp" : "premium/control/AdministracionGeneral.jsp")+"'); }, 5000);</script>");
                        } else {
                            if (r.getByte(2) == 1) { s.executeUpdate("UPDATE Usuario SET FhN2='"+LocalDateTime.now().plusDays(2L).format(DateTimeFormatter.ofPattern("uuuu-MM-dd HH:mm:ss"))+"' WHERE CE='"+request.getParameter("ce")+"'"); }
                            byte menos = ((byte) (r.getByte(2) - 1));
                            s.executeUpdate("UPDATE Usuario SET CV=NULL,I2="+menos+" WHERE CE='"+request.getParameter("ce")+"'");
                            out.print("<div class='success-container'>");
                                out.print("<div class='success-content'>");
                                    out.print("<div class='success-text'>");
                                        out.print("<h1 class='success-title'>Verificación INCORRECTA</h1>");
                                        out.print("<h3 class='success-subtitle'>Intentos RESTANTES: "+menos+"</h3>");
                                    out.print("</div>");
                                    out.print("<img src='imgs/err.png' alt='E' class='success-image'/>");
                                out.print("</div>");
                            out.print("</div>");
                            out.print("<script>setTimeout(function () { location.assign('Sesion.html'); }, 5000);</script>");
                        }
                        r.close();
                        s.execute("COMMIT");
                    } break;
                    case "M": {
                        Epistula e = new Epistula();
                        e.eMail("ecobyte.sw@gmail.com", ((String) session.getAttribute("u")), request.getParameter("em"));
                        out.print("<div class='success-container'>");
                            out.print("<div class='success-content'>");
                                out.print("<h1 class='success-title'>Mensaje correctamente ENVIADO</h1>");
                                out.print("<img src='imgs/csql.png' alt='OK' class='success-image'/>");
                            out.print("</div>");
                        out.print("</div>");
                        out.print("<script>setTimeout(function () { location.assign('FAQ.html'); }, 5000);</script>");
                    } break;
                    case "U0": {
                        r = s.executeQuery("SELECT C1,C2 FROM Usuario WHERE CE='"+session.getAttribute("u")+"'");
                        r.next();
                        Hash h = new Hash();
                        if (r.getString(1).equals(h.hashSHA256(request.getParameter("c1"))) && r.getString(2).equals(h.hashSHA256(request.getParameter("c2")))) {
                            s.executeUpdate("UPDATE Usuario SET C1='"+h.hashSHA256(request.getParameter("nc1"))+"',C2='"+h.hashSHA256(request.getParameter("nc2"))+"' WHERE CE='"+session.getAttribute("u")+"'");
                            session.removeAttribute("u");
                            out.print("<div class='success-container'>");
                                out.print("<div class='success-content'>");
                                    out.print("<h1 class='success-title'>Usuario correctamente ACTUALIZADO</h1>");
                                    out.print("<img src='imgs/usql.png' alt='U' class='success-image'/>");
                                out.print("</div>");
                            out.print("</div>");
                            out.print("<script>setTimeout(function () { location.assign('Sesion.html'); }, 5000);</script>");
                            s.execute("COMMIT");
                        } else {
                            out.print("<div class='success-container'>");
                                out.print("<div class='success-content'>");
                                    out.print("<h1 class='success-title'>Actualización DENEGADA</h1>");
                                    out.print("<img src='imgs/err.png' alt='E' class='success-image'/>");
                                out.print("</div>");
                            out.print("</div>");
                            out.print("<script>setTimeout(function () { location.assign('Perfil.jsp'); }, 5000);</script>");
                        }
                        r.close();
                    } break;
                    case "U1": {
                        r = s.executeQuery("SELECT C1,C2 FROM Usuario WHERE CE='"+session.getAttribute("u")+"'");
                        r.next();
                        Hash h = new Hash();
                        if (r.getString(1).equals(h.hashSHA256(request.getParameter("c1"))) && r.getString(2).equals(h.hashSHA256(request.getParameter("c2")))) {
                            s.executeUpdate("UPDATE Usuario SET C1='"+h.hashSHA256(request.getParameter("nc1"))+"' WHERE CE='"+session.getAttribute("u")+"'");
                            session.removeAttribute("u");
                            out.print("<div class='success-container'>");
                                out.print("<div class='success-content'>");
                                    out.print("<h1 class='success-title'>Usuario correctamente ACTUALIZADO</h1>");
                                    out.print("<img src='imgs/usql.png' alt='U' class='success-image'/>");
                                out.print("</div>");
                            out.print("</div>");
                            out.print("<script>setTimeout(function () { location.assign('Sesion.html'); }, 5000);</script>");
                            s.execute("COMMIT");
                        } else {
                            out.print("<div class='success-container'>");
                                out.print("<div class='success-content'>");
                                    out.print("<h1 class='success-title'>Actualización DENEGADA</h1>");
                                    out.print("<img src='imgs/err.png' alt='E' class='success-image'/>");
                                out.print("</div>");
                            out.print("</div>");
                            out.print("<script>setTimeout(function () { location.assign('Perfil.jsp'); }, 5000);</script>");
                        }
                        r.close();
                    } break;
                    case "U2": {
                        r = s.executeQuery("SELECT C1,C2 FROM Usuario WHERE CE='"+session.getAttribute("u")+"'");
                        r.next();
                        Hash h = new Hash();
                        if (r.getString(1).equals(h.hashSHA256(request.getParameter("c1"))) && r.getString(2).equals(h.hashSHA256(request.getParameter("c2")))) {
                            s.executeUpdate("UPDATE Usuario SET C2='"+h.hashSHA256(request.getParameter("nc2"))+"' WHERE CE='"+session.getAttribute("u")+"'");
                            session.removeAttribute("u");
                            out.print("<div class='success-container'>");
                                out.print("<div class='success-content'>");
                                    out.print("<h1 class='success-title'>Usuario correctamente ACTUALIZADO</h1>");
                                    out.print("<img src='imgs/usql.png' alt='U' class='success-image'/>");
                                out.print("</div>");
                            out.print("</div>");
                            out.print("<script>setTimeout(function () { location.assign('Sesion.html'); }, 5000);</script>");
                            s.execute("COMMIT");
                        } else {
                            out.print("<div class='success-container'>");
                                out.print("<div class='success-content'>");
                                    out.print("<h1 class='success-title'>Actualización DENEGADA</h1>");
                                    out.print("<img src='imgs/err.png' alt='E' class='success-image'/>");
                                out.print("</div>");
                            out.print("</div>");
                            out.print("<script>setTimeout(function () { location.assign('Perfil.jsp'); }, 5000);</script>");
                        }
                        r.close();
                    } break;
                    case "D": {
                        r = s.executeQuery("SELECT C1,C2 FROM Usuario WHERE CE='"+session.getAttribute("u")+"'");
                        r.next();
                        Hash h = new Hash();
                        if (r.getString(1).equals(h.hashSHA256(request.getParameter("c1"))) && r.getString(2).equals(h.hashSHA256(request.getParameter("c2")))) {
                            r.close();
                            r = null;
                            r = s.executeQuery("SELECT Img FROM Producto WHERE CE='"+session.getAttribute("u")+"'");
                            while (r.next()) {
                                (new File("C:\\Users\\Marlon\\PlantiSHOP\\src\\main\\webapp\\imgs\\prods\\"+r.getString(1))).delete();
                            }
                            r.close();
                            s.executeUpdate("DELETE FROM Usuario WHERE CE='"+session.getAttribute("u")+"'");
                            session.removeAttribute("u");
                            out.print("<div class='success-container'>");
                                out.print("<div class='success-content'>");
                                    out.print("<h1 class='success-title'>Usuario correctamente ELIMINADO</h1>");
                                    out.print("<img src='imgs/dsql.png' alt='D' class='success-image'/>");
                                out.print("</div>");
                            out.print("</div>");
                            out.print("<script>setTimeout(function () { location.assign('index.html'); }, 5000);</script>");
                            s.execute("COMMIT");
                        } else {
                            r.close();
                            out.print("<div class='success-container'>");
                                out.print("<div class='success-content'>");
                                    out.print("<h1 class='success-title'>Eliminación DENEGADA</h1>");
                                    out.print("<img src='imgs/err.png' alt='E' class='success-image'/>");
                                out.print("</div>");
                            out.print("</div>");
                            out.print("<script>setTimeout(function () { location.assign('Perfil.jsp'); }, 5000);</script>");
                        }
                    } break;
                    case "Un": {
                        s.executeUpdate("UPDATE Usuario SET N='"+request.getParameter("n")+"' WHERE CE='"+session.getAttribute("u")+"'");
                        out.print("<script>location.assign('Perfil.jsp');</script>");
                        s.execute("COMMIT");
                    } break;
                    case "Uap": {
                        s.executeUpdate("UPDATE Usuario SET AP='"+request.getParameter("ap")+"' WHERE CE='"+session.getAttribute("u")+"'");
                        out.print("<script>location.assign('Perfil.jsp');</script>");
                        s.execute("COMMIT");
                    } break;
                    case "Uam": {
                        s.executeUpdate("UPDATE Usuario SET AM='"+request.getParameter("am")+"' WHERE CE='"+session.getAttribute("u")+"'");
                        out.print("<script>location.assign('Perfil.jsp');</script>");
                        s.execute("COMMIT");
                    } break;
                    case "Uu": {
                        s.executeUpdate("UPDATE Usuario SET U='"+request.getParameter("u")+"' WHERE CE='"+session.getAttribute("u")+"'");
                        out.print("<script>location.assign('Perfil.jsp');</script>");
                        s.execute("COMMIT");
                    } break;
                    case "Utxtj": {
                        s.executeUpdate("UPDATE Jardin SET C="+((request.getParameter("txt") == null) ? "NULL" : "'"+request.getParameter("txt")+"'")+" WHERE Id="+request.getParameter("id"));
                        out.print("<script>location.assign('Jardin.jsp');</script>");
                        s.execute("COMMIT");
                    } break;
                    case "Ulj": {
                        s.executeUpdate("UPDATE Jardin SET L="+request.getParameter("l")+" WHERE Id="+request.getParameter("id"));
                        out.print("<script>location.assign('Jardin.jsp');</script>");
                        s.execute("COMMIT");
                    } break;
                    case "Upj": {
                        s.executeUpdate("UPDATE Jardin SET P="+request.getParameter("p")+" WHERE Id="+request.getParameter("id"));
                        out.print("<script>location.assign('Jardin.jsp');</script>");
                        s.execute("COMMIT");
                    } break;
                    case "Upv": {
                        s.executeUpdate("UPDATE Producto SET P="+request.getParameter("p")+" WHERE Id="+request.getParameter("id"));
                        out.print("<script>location.assign('Ventas.jsp');</script>");
                        s.execute("COMMIT");
                    } break;
                    case "Ucv": {
                        s.executeUpdate("UPDATE Producto SET Cupo="+request.getParameter("c")+" WHERE Id="+request.getParameter("id"));
                        out.print("<script>location.assign('Ventas.jsp');</script>");
                        s.execute("COMMIT");
                    } break;
                    case "Utxtv": {
                        s.executeUpdate("UPDATE Producto SET D="+((request.getParameter("txt") == null) ? "NULL" : "'"+request.getParameter("txt")+"'")+" WHERE Id="+request.getParameter("id"));
                        out.print("<script>location.assign('Ventas.jsp');</script>");
                        s.execute("COMMIT");
                    } break;
                    case "D2": {
                        if (request.getParameter("t").equals("Producto")) {
                            r = s.executeQuery("SELECT Img FROM Producto WHERE Id="+request.getParameter("id"));
                            r.next();
                            (new File("C:\\Users\\Marlon\\PlantiSHOP\\src\\main\\webapp\\imgs\\prods\\"+r.getString(1))).delete();
                            r.close();
                        }
                        s.executeUpdate("DELETE FROM "+request.getParameter("t")+" WHERE Id="+request.getParameter("id"));
                        out.print("<script>location.assign('Perfil.jsp');</script>");
                        s.execute("COMMIT");
                    } break;
                    case "B": {
                        r = s.executeQuery("SELECT CE,N,D,P,Img,Cupo FROM Producto WHERE Id="+request.getParameter("id"));
                        r.next();
                        String[] $v = {r.getString(1), r.getString(2), r.getString(3), String.valueOf(r.getFloat(4)), r.getString(5)};
                        int cupo = r.getInt(6);
                        s.executeUpdate("INSERT INTO Compra(V,C,NP,DP,PP,ImgP,X,LP) VALUES ('"+$v[0]+"','"+session.getAttribute("u")+"','"+$v[1]+"',"+(($v[2] == null) ? "NULL" : "'"+$v[2]+"'")+","+$v[3]+",'"+$v[4]+"',1,"+((cupo < 100) ? cupo : 0)+")");
                        out.print("<div class='success-container'>");
                            out.print("<div class='success-content'>");
                                out.print("<h1 class='success-title'>Compra REALIZADA</h1>");
                                out.print("<img src='imgs/csql.png' alt='C' class='success-image'/>");
                            out.print("</div>");
                        out.print("</div>");
                        out.print("<script>setTimeout(function () { location.assign('Mercado.jsp'); }, 5000);</script>");
                        r.close();
                        s.execute("COMMIT");
                    } break;
                    case "B1": {
                        s.executeUpdate("UPDATE Compra SET X=2,LP="+request.getParameter("n")+",TP="+request.getParameter("pt")+",U='"+request.getParameter("u")+"',Fh='"+LocalDateTime.parse(request.getParameter("fh"), DateTimeFormatter.ofPattern("uuuu-MM-dd HH:mm:ss")).toString()+"' WHERE Id="+request.getParameter("id"));
                        out.print("<div class='success-container'>");
                            out.print("<div class='success-content'>");
                                out.print("<h1 class='success-title'>Notificación ENVIADA</h1>");
                                out.print("<img src='imgs/usql.png' alt='U' class='success-image'/>");
                            out.print("</div>");
                        out.print("</div>");
                        out.print("<script>setTimeout(function () { location.assign('Mensajeria.jsp'); }, 5000);</script>");
                        s.execute("COMMIT");
                    } break;
                    case "B2": {
                        if (Boolean.parseBoolean(request.getParameter("sn"))) {
                            s.executeUpdate("UPDATE Compra SET X=3,BMsg=FALSE WHERE Id="+request.getParameter("id"));
                            out.print("<div class='success-container'>");
                                out.print("<div class='success-content'>");
                                    out.print("<h1 class='success-title'>Oferta ACEPTADA</h1>");
                                    out.print("<img src='imgs/usql.png' alt='U' class='success-image'/>");
                                out.print("</div>");
                            out.print("</div>");
                        } else {
                            s.executeUpdate("UPDATE Compra SET X=1,LP=0,TP=0.00,U=NULL,Fh=NULL,BMsg=TRUE WHERE Id="+request.getParameter("id"));
                            out.print("<div class='success-container'>");
                                out.print("<div class='success-content'>");
                                    out.print("<h1 class='success-title'>Oferta RECHAZADA</h1>");
                                    out.print("<img src='imgs/bnot.png' alt='NB' class='success-image'/>");
                                out.print("</div>");
                            out.print("</div>");
                        }
                        out.print("<script>setTimeout(function () { location.assign('Mensajeria.jsp#tV'); }, 5000);</script>");
                        s.execute("COMMIT");
                    } break;
                    case "B3": {
                        r = s.executeQuery("SELECT N,AP,AM FROM Usuario WHERE CE='"+session.getAttribute("u")+"'");
                        r.next();
                        String[] $c = {r.getString(1), r.getString(2), r.getString(3)};
                        r.close();
                        r = null;
                        r = s.executeQuery("SELECT Producto.Pop,Producto.Id,Usuario.CE,Usuario.N,Usuario.AP,Usuario.AM,Compra.NP,Compra.LP,Compra.TP,Compra.Fh,Compra.U,Producto.Cupo FROM Producto (INNER JOIN Usuario ON Producto.CE=Usuario.CE (INNER JOIN Compra ON Usuario.CE=Compra.V)) WHERE Compra.C='"+session.getAttribute("u")+"' AND Compra.Id="+request.getParameter("id"));
                        r.next();
                        String[] inner = {String.valueOf(r.getLong(1) + 1L), String.valueOf(r.getLong(2)), r.getString(3), (r.getString(4)+" "+r.getString(5)+" "+r.getString(6)), r.getString(7), String.valueOf(r.getInt(12) - r.getByte(8)), String.valueOf(r.getByte(8)), String.valueOf(r.getFloat(9)), r.getString(10), r.getString(11)};
                        if (Boolean.parseBoolean(request.getParameter("sn"))) {
                            s.executeUpdate("UPDATE Compra SET X=4,DP=NULL,PP=0.00,LP=0,U=NULL,BMsg=NULL WHERE Id="+request.getParameter("id"));
                            s.executeUpdate("UPDATE Producto SET Pop="+inner[0]+",Cupo="+inner[5]+" WHERE Id="+inner[1]);
                            s.executeUpdate("INSERT INTO Notificacion(V,C,APC,AMC,N,P,LP,TP,Fh,U) VALUES ('"+inner[2]+"','"+$c[0]+"','"+$c[1]+"','"+$c[2]+"',TRUE,'"+inner[4]+"',"+inner[6]+","+inner[7]+",'"+inner[8]+"','"+inner[9]+"')");
                            File f = new File("D:\\C"+request.getParameter("id")+".txt");
                            f.createNewFile();
                            FileWriter w = new FileWriter(f);
                            w.write("Registro Comercial\n\nProducto: "+inner[4]+"\nVendedor: "+inner[3]+"\nComprador: "+$c[0]+" "+$c[1]+" "+$c[2]+"\nNo. de Lotes: "+inner[6]+"\nCosto: $"+inner[7]+"\nFecha y Hora: "+LocalDateTime.parse(inner[8], DateTimeFormatter.ofPattern("d / MMM / uuuu -- h:mm a"))+"\nUbicacion: "+inner[9]);
                            w.close();
                            out.print("<div class='success-container'>");
                                out.print("<div class='success-content'>");
                                    out.print("<h1 class='success-title'>Compra FINALIZADA</h1>");
                                    out.print("<img src='imgs/byes.png' alt='YB' class='success-image'/>");
                                out.print("</div>");
                            out.print("</div>");
                        } else {
                            s.executeUpdate("INSERT INTO Notificacion(V,C,APC,AMC,N,P) VALUES ('"+inner[2]+"','"+$c[0]+"','"+$c[1]+"','"+$c[2]+"',FALSE,'"+inner[4]+"')");
                            s.executeUpdate("DELETE FROM Compra WHERE Id="+request.getParameter("id"));
                            out.print("<div class='success-container'>");
                                out.print("<div class='success-content'>");
                                    out.print("<h1 class='success-title'>Compra CANCELADA</h1>");
                                    out.print("<img src='imgs/dsql.png' alt='D' class='success-image'/>");
                                out.print("</div>");
                            out.print("</div>");
                        }
                        out.print("<script>setTimeout(function () { location.assign('Mensajeria.jsp'); }, 5000);</script>");
                        r.close();
                        s.execute("COMMIT");
                    } break;
                    case "E": {
                        session.removeAttribute("u");
                        out.print("<script>location.assign('index.html');</script>");
                    } break;
                }
                r = null;
                s.close();
                c.close();
            } catch (Exception e) {
                out.print("<script>alert('Lo sentimos, se produjo un ERROR... intentalo de NUEVO...');</script>");
                out.print("<script>history.back();</script>");
            }
        
      out.write("\n");
      out.write("        \n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
