/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-07-02 18:00:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;

public final class Jardin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


    Connection c;
    Statement s;
    ResultSet r;
    String na;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');

    try {
        Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
        c = DriverManager.getConnection("jdbc:mysql://localhost/PSHOP", "root", "n0m3l0");
        s = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        r = s.executeQuery("SELECT N,AP,AM FROM Usuario WHERE CE='"+session.getAttribute("u")+"'");
        r.next();
        na = r.getString(1) + " " + r.getString(2) + " " + r.getString(3);
        r.close();
        r = null;
    } catch (Exception e) {
        out.print("<script>alert('Lo sentimos, se produjo un ERROR... intentalo de NUEVO...');</script>");
        out.print("<script>history.back();</script>");
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es-MX\">\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Jardin Personal</title>\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"imgs/logo.png\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <style>\n");
      out.write("            body {\n");
      out.write("              background: #f0f0f0;\n");
      out.write("              background-size: cover;\n");
      out.write("              font-family: 'Segoe UI', sans-serif;\n");
      out.write("            }\n");
      out.write("            .section-title {\n");
      out.write("              color: #14532d;\n");
      out.write("            }\n");
      out.write("            .plant-block {\n");
      out.write("              border: 2px solid #ccc;\n");
      out.write("              border-radius: 10px;\n");
      out.write("              padding: 1rem;\n");
      out.write("              background-color: rgba(255, 255, 255, 0.9);\n");
      out.write("              margin-bottom: 2rem;\n");
      out.write("            }\n");
      out.write("            .plant-image {\n");
      out.write("              width: 100%;\n");
      out.write("              height: auto;\n");
      out.write("              max-height: 150px;\n");
      out.write("              object-fit: contain;\n");
      out.write("            }\n");
      out.write("            .btn-eliminar {\n");
      out.write("              background-color: #dc3545;\n");
      out.write("              color: white;\n");
      out.write("            }\n");
      out.write("            .btn-eliminar:hover {\n");
      out.write("              background-color: #c82333;\n");
      out.write("            }\n");
      out.write("            .btn-cambiar {\n");
      out.write("              background-color: #198754;\n");
      out.write("              color: white;\n");
      out.write("            }\n");
      out.write("            .btn-cambiar:hover {\n");
      out.write("              background-color: #157347;\n");
      out.write("            }\n");
      out.write("            .filtro-btn {\n");
      out.write("              background-color: #198754;\n");
      out.write("              color: white;\n");
      out.write("            }\n");
      out.write("            .hidden {\n");
      out.write("              display: none !important;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("        <script>\n");
      out.write("            document.addEventListener('DOMContentLoaded', function () {\n");
      out.write("                window.location.hash = \"no-back-button\";\n");
      out.write("                window.location.hash = \"Again-No-back-button\";\n");
      out.write("                window.onhashchange = function () {\n");
      out.write("                    window.location.hash = \"\";\n");
      out.write("                };\n");
      out.write("            });\n");
      out.write("            function filtrar(tipo) {\n");
      out.write("                document.querySelectorAll('.plant-section').forEach(sec => {\n");
      out.write("                    if (tipo === 'TODOS' || sec.dataset.tipo === tipo) {\n");
      out.write("                        sec.classList.remove('hidden');\n");
      out.write("                    } else {\n");
      out.write("                        sec.classList.add('hidden');\n");
      out.write("                    }\n");
      out.write("                });\n");
      out.write("            }\n");
      out.write("        </script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div class=\"container py-4\">\n");
      out.write("            <h1 class=\"text-center section-title\">Jardín Virtual Personal de ");
      out.print( na );
      out.write("</h1>\n");
      out.write("            <div class=\"text-center mb-3\">\n");
      out.write("                <a class=\"btn btn-outline-success\" href=\"Perfil.jsp\">Regresar al Perfil</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"text-center mb-4\">\n");
      out.write("                <label class=\"form-label\">Filtrar:</label>\n");
      out.write("                <select class=\"form-select w-auto d-inline\" onchange=\"filtrar(this.value)\">\n");
      out.write("                    <option value=\"TODOS\">Mostrar TODO</option>\n");
      out.write("                    <option value=\"PD\">Plantas Decorativas</option>\n");
      out.write("                    <option value=\"PH\">Plantas de Huerto</option>\n");
      out.write("                    <option value=\"PA\">Plantas Acuáticas</option>\n");
      out.write("                    <option value=\"A\">Árbol</option>\n");
      out.write("                    <option value=\"AH\">Algas y/u Hongos</option>\n");
      out.write("                </select>\n");
      out.write("            </div>\n");
      out.write("            <form action=\"Interfaz.jsp\" method=\"post\" class=\"mb-5\">\n");
      out.write("                <input name=\"x\" type=\"hidden\" value=\"Cj\">\n");
      out.write("                <div class=\"card shadow p-4\">\n");
      out.write("                    <h2 class=\"section-title text-center\">Registro de Nuevas Plantaciones</h2>\n");
      out.write("                    <div class=\"mb-3\">\n");
      out.write("                        <label class=\"form-label\">Nombre:</label>\n");
      out.write("                        <input name=\"n\" type=\"text\" pattern=\"[A-Za-z0-9\\s']+\" maxlength=\"25\" class=\"form-control\" required>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mb-3\">\n");
      out.write("                        <label class=\"form-label\">Tipo:</label>\n");
      out.write("                        <select name=\"t\" class=\"form-select\" required>\n");
      out.write("                            <option value=\"PD\">Planta Decorativa</option>\n");
      out.write("                            <option value=\"PH\">Planta de Huerto</option>\n");
      out.write("                            <option value=\"PA\">Planta Acuática</option>\n");
      out.write("                            <option value=\"A\">Árbol</option>\n");
      out.write("                            <option value=\"AH\">Alga / Hongo</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mb-3\">\n");
      out.write("                        <label class=\"form-label\">Consideraciones:</label>\n");
      out.write("                        <textarea name=\"txt\" pattern=\"[A-Za-z0-9\\s,';.]+\" maxlength=\"250\" class=\"form-control\"></textarea>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"row g-3\">\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <label class=\"form-label\">Porcentaje de Luz:</label>\n");
      out.write("                            <input name=\"l\" type=\"number\" min=\"0\" max=\"100\" class=\"form-control\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <label class=\"form-label\">Nivel de Prioridad:</label>\n");
      out.write("                            <input name=\"p\" type=\"number\" min=\"1\" max=\"10\" step=\"1\" class=\"form-control\" required>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"text-center mt-4\">\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-success\">REGISTRAR</button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("            <hr>\n");
      out.write("            ");

                try {
                    String[] tipo = {"PD", "PH", "PA", "A", "AH"};
                    String[] titulo = {"Plantas Decorativas", "Plantas de Huerto", "Plantas Acuaticas", "Arboles", "Algas y/u Hongos"};
                    for (byte t = 0; t < 5; t++) {
                        r = s.executeQuery("SELECT Id,N,C,L,P FROM Jardin WHERE CE='"+session.getAttribute("u")+"' AND T='"+tipo[t]+"' ORDER BY P DESC");
                        if (r.next()) {
                            out.print("<div class='plant-section' data-tipo='"+tipo[t]+"'>");
                                out.print("<h3 class='section-title'>"+titulo[t]+"</h3>");
                                r.beforeFirst();
                                while (r.next()) {
                                    out.print("<div class='row plant-block'>");
                                        out.print("<div class='col-md-4 text-center'>");
                                            out.print("<img src='imgs/"+tipo[t]+".png' alt='"+titulo[t]+"' class='plant-image'/>");
                                            out.print("<a class='btn btn-eliminar mt-2' href='Interfaz.jsp?x=D2&t=Jardin&id="+r.getLong(1)+"'>ELIMINAR</a>");
                                        out.print("</div>");
                                        out.print("<div class='col-md-8'>");
                                            out.print("<h4>"+r.getString(2)+"</h4>");
                                            out.print("<form action='Interfaz.jsp' method='post' class='mb-2'>");
                                                out.print("<input name='x' type='hidden' value='Utxtj'><input name='id' type='hidden' value='"+r.getLong(1)+"'>");
                                                out.print("<textarea name='txt' class='form-control mb-2' pattern=\"[A-Za-z0-9\\s,';.]+\" maxlength='200'>"+r.getString(3)+"</textarea>");
                                                out.print("<button class='btn btn-cambiar'>CAMBIAR esta Consideración</button>");
                                            out.print("</form>");
                                            out.print("<form action='Interfaz.jsp' method='post' class='mb-2'>");
                                                out.print("<input name='x' type='hidden' value='Ulj'><input name='id' type='hidden' value='"+r.getLong(1)+"'>");
                                                out.print("<div class='input-group'><span class='input-group-text'>Porcentaje de Luz:</span><input name='l' type='number' min='0' max='100' value='"+r.getByte(4)+"' class='form-control' required><button class='btn btn-cambiar'>CAMBIAR</button></div>");
                                            out.print("</form>");
                                            out.print("<form action='Interfaz.jsp' method='post' class='mb-2'>");
                                                out.print("<input name='x' type='hidden' value='Upj'><input name='id' type='hidden' value='"+r.getLong(1)+"'>");
                                                out.print("<div class='input-group'><span class='input-group-text'>Nivel de Prioridad:</span><input name='p' type='number' min='1' max='10' step='1' value='"+r.getByte(5)+"' class='form-control' required><button class='btn btn-cambiar'>CAMBIAR</button></div>");
                                            out.print("</form>");
                                        out.print("</div>");
                                    out.print("</div>");
                                }
                            out.print("</div>");
                        }
                        r.close();
                        r = null;
                    }
                    s.close();
                    c.close();
                } catch (Exception e) {
                    out.print("<script>alert('Lo sentimos, se produjo un ERROR... intentalo de NUEVO...');</script>");
                    out.print("<script>history.back();</script>");
                }
            
      out.write("\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
