/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-07-02 18:00:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import auxs.Llavero;
import java.io.File;
import java.io.FileWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public final class Mensajeria_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


    Connection c;
    Statement s;
    ResultSet r;
    long i;
    String na, u;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/imgs/navbar.jsp", Long.valueOf(1751388600522L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(9);
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("auxs.Llavero");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.io.FileWriter");
    _jspx_imports_classes.add("java.time.LocalDateTime");
    _jspx_imports_classes.add("java.sql.DriverManager");
    _jspx_imports_classes.add("java.io.File");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');

    try {
        Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
        c = DriverManager.getConnection("jdbc:mysql://localhost/PSHOP", "root", "n0m3l0");
        s = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        r = s.executeQuery("SELECT N,AP,AM,U FROM Usuario WHERE CE='"+session.getAttribute("u")+"'");
        r.next();
        na = r.getString(1) + " " + r.getString(2) + " " + r.getString(3);
        u = r.getString(4);
        r.close();
        r = null;
    } catch (Exception e) {
        out.print("<script>alert('Lo sentimos, se produjo un ERROR... intentalo de NUEVO...');</script>");
        out.print("<script>history.back();</script>");
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es-MX\">\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Mensajeria Comercial</title>\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"imgs/logo.png\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css\" rel=\"stylesheet\">\n");
      out.write("        <style>\n");
      out.write("            body { background-color: #f0f0f0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; }\n");
      out.write("            .product-card { background: white; border-radius: 15px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); margin-bottom: 20px; }\n");
      out.write("            .product-img { width: 100%; height: 200px; object-fit: cover; border-radius: 15px 15px 0 0; }\n");
      out.write("            .status-pending { border-left: 5px solid #ffc107; }\n");
      out.write("            .status-accepted { border-left: 5px solid #28a745; }\n");
      out.write("            .status-waiting { border-left: 5px solid #17a2b8; }\n");
      out.write("            .map-container { height: 300px; border-radius: 10px; }\n");
      out.write("            .btn-custom-green { background-color: #28a745; border-color: #28a745; }\n");
      out.write("            .btn-custom-blue { background-color: #007bff; border-color: #007bff; }\n");
      out.write("            .btn-custom-red { background-color: #dc3545; border-color: #dc3545; }\n");
      out.write("        </style>\n");
      out.write("        <script src=\"https://maps.googleapis.com/maps/api/js?key=");
      out.print( Llavero.getApiGoogleMaps() );
      out.write("&callback=initMap&v=weekly\" defer></script>\n");
      out.write("        <script>\n");
      out.write("            document.addEventListener('DOMContentLoaded', function () {\n");
      out.write("                window.location.hash = \"no-back-button\";\n");
      out.write("                window.location.hash = \"Again-No-back-button\";\n");
      out.write("                window.onhashchange = function () {\n");
      out.write("                    window.location.hash = \"\";\n");
      out.write("                };\n");
      out.write("            });\n");
      out.write("            window.initMap = function () {\n");
      out.write("                let latd, lngd;\n");
      out.write("                (new google.maps.Geocoder()).geocode({ address: \"");
      out.print( u );
      out.write("\" }).then(function (r) {\n");
      out.write("                    latd = r.results[0].geometry.location.lat;\n");
      out.write("                    lngd = r.results[0].geometry.location.lng;\n");
      out.write("                });\n");
      out.write("                ");

                    try {
                        r = s.executeQuery("SELECT Compra.X FROM Compra INNER JOIN Usuario ON Compra.V=Usuario.CE WHERE Compra.C='"+session.getAttribute("u")+"' ORDER BY Compra.X DESC, Compra.Fh ASC");
                        i = 1L;
                        while (r.next()) {
                            if (r.getByte(1) == 1) {
                                out.print("(new google.maps.Map(document.getElementById('gMap'"+i+"), { center: { lat: (latd ?? 19.4326077), lng: (lngd ?? -99.133208) }, zoom: 8, mapTypeControl: false })).addListener('click', function (ev) { (new google.maps.Geocoder()).geocode({ location: ev.latLng }).then(function (r) { document.getElementById('m'"+i+").value = r.results[0].formatted_address; }, function (er) { alert('Lo sentimos, se produjo un ERROR:\n'+er); }); });");
                            }
                            i = i + 1L;
                        }
                        r.close();
                        r = null;
                    } catch (Exception e) {
                        out.print("alert('Lo sentimos, se produjo un ERROR... intentalo de NUEVO...');");
                        out.print("history.back();");
                    }
                
      out.write("\n");
      out.write("            };\n");
      out.write("        </script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
      out.write("<style>\n");
      out.write("    body {\n");
      out.write("        font-family: 'Inter', sans-serif;\n");
      out.write("        margin: 0;\n");
      out.write("        padding-top: 120px;\n");
      out.write("        background-color: #f8f9fa;\n");
      out.write("    }\n");
      out.write("    iframe {\n");
      out.write("        width: 100%;\n");
      out.write("        height: calc(100vh - 120px);\n");
      out.write("        border: none;\n");
      out.write("    }\n");
      out.write("    .navbar-top {\n");
      out.write("        background-color: #198754;\n");
      out.write("    }\n");
      out.write("    .navbar-bottom {\n");
      out.write("        background-color: #000;\n");
      out.write("        z-index: 0;\n");
      out.write("    }\n");
      out.write("    .navbar-brand img {\n");
      out.write("        width: 2em;\n");
      out.write("        height: 2em;\n");
      out.write("        margin-right: 0.5rem;\n");
      out.write("    }\n");
      out.write("    .nav-link {\n");
      out.write("        color: white !important;\n");
      out.write("    }\n");
      out.write("    .nav-link:hover {\n");
      out.write("        color: #a4f3b5 !important;\n");
      out.write("    }\n");
      out.write("    .dropdown-menu a:hover {\n");
      out.write("        background-color: #198754;\n");
      out.write("        color: white !important;\n");
      out.write("    }\n");
      out.write("    .dropdown-toggle::after {\n");
      out.write("        margin-left: 0.4em;\n");
      out.write("    }\n");
      out.write("    @media (max-width: 768px) {\n");
      out.write("        body {\n");
      out.write("            padding-top: 170px;\n");
      out.write("        }\n");
      out.write("        iframe {\n");
      out.write("            height: calc(100vh - 170px);\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("    .navbar-bottom .navbar-nav {\n");
      out.write("        display: flex;\n");
      out.write("        justify-content: space-between;\n");
      out.write("        width: 100%;\n");
      out.write("    }\n");
      out.write("    .navbar-bottom .nav-item {\n");
      out.write("        flex-grow: 1;\n");
      out.write("        text-align: center;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("<script>\n");
      out.write("    document.addEventListener('DOMContentLoaded', function () {\n");
      out.write("        window.location.hash = \"no-back-button\";\n");
      out.write("        window.location.hash = \"Again-No-back-button\";\n");
      out.write("        window.onhashchange = function () {\n");
      out.write("            window.location.hash = \"\";\n");
      out.write("        };\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("<body style='background-color: #e9e9e9;'>\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark navbar-top fixed-top shadow-sm\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <a class=\"navbar-brand d-flex align-items-center\" href=\"#\">\n");
      out.write("            <img src=\"imgs/logo.png\" alt=\"Logo\">\n");
      out.write("            <span class=\"fw\">PlantiSHOP</span>\n");
      out.write("        </a>\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#topNavbar\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <ul class=\"navbar-nav ms-auto\">\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"Ventas.jsp\">Tus Ventas</a></li>\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mensajeria.jsp\">Tus Compras y Pedidos</a></li>\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"FAQ.html\">FAQ</a></li>\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"Premium.jsp\">PREMIUM</a></li>\n");
      out.write("        </ul>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"topNavbar\">\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\n");
      out.write("                <li class=\"nav-item dropdown\">\n");
      out.write("                    <a class=\"nav-link dropdown-toggle d-flex align-items-center\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\">\n");
      out.write("                        <img src=\"imgs/perfil.jpg\" alt=\"Perfil\" class=\"rounded-circle me-2\" style=\"width: 2em; height: 2em;\">\n");
      out.write("                        Perfil\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-end\">\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"Perfil.jsp\">Tu Perfil</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"Jardin.jsp\">Tu Jardín</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"Interfaz.jsp?x=E\">Cerrar Sesión</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark navbar-bottom fixed-top shadow-sm\" style=\"top: 56px;\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#bottomNavbar\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"bottomNavbar\">\n");
      out.write("            <ul class=\"navbar-nav\">\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#PD\">Plantas Decorativas</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#PH\">Plantas de Huerto</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#PA\">Plantas Acuáticas</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#A\">Árboles</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#AH\">Algas y Hongos</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#F\">Fertilizantes</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#H\">Herramientas</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>");
      out.write("\n");
      out.write("        \n");
      out.write("        <div class=\"container mt-4\">\n");
      out.write("            <h1 class=\"text-center mb-4\"><i class=\"bi bi-bag-check\"></i> Pedidos de ");
      out.print( na );
      out.write("</h1>\n");
      out.write("            ");

                try {
                    r = s.executeQuery("SELECT Compra.ImgP,Compra.NP,Compra.PP,Compra.DP,Usuario.N,Usuario.AP,Usuario.AM,Compra.X,Compra.BMsg,Compra.Id,Compra.LP FROM Compra INNER JOIN Usuario ON Compra.V=Usuario.CE WHERE Compra.C='"+session.getAttribute("u")+"' ORDER BY Compra.X DESC, Compra.Fh ASC");
                    if (r.next()) {
                        i = 1L;
                        String minFH = LocalDateTime.now().plusDays(1L).format(DateTimeFormatter.ofPattern("uuuu-MM-ddTHH:mm"));
                        r.beforeFirst();
                        while (r.next()) {
                            String statusClass = "";
                            switch (r.getByte(8)) {
                                case 1: { statusClass = "status-pending"; } break;
                                case 2: { statusClass = "status-waiting"; } break;
                                case 3: { statusClass = "status-accepted"; } break;
                            }
                            out.print("<div class='product-card "+statusClass+"'>");
                                out.print("<div class='row g-0'>");
                                    out.print("<div class='col-md-3'>");
                                        out.print("<img src='imgs/prods/"+r.getString(1)+"' class='product-img' alt='Producto'/>");
                                    out.print("</div>");
                                    out.print("<div class='col-md-9'>");
                                        out.print("<div class='card-body'>");
                                            out.print("<h3 class='card-title'>"+r.getString(2)+"</h3>");
                                            out.print("<h4 class='text-success'>$ "+r.getFloat(3)+" <small class='text-muted'>(c / LOTE)</small></h4>");
                                            out.print("<p class='card-text'>"+r.getString(4)+"</p>");
                                            out.print("<p class='text-muted'><i class='bi bi-person-circle'></i> Vendedor: "+r.getString(5)+" "+r.getString(6)+" "+r.getString(7)+"</p>");
                                            switch (r.getByte(8)) {
                                                case 1: {
                                                    if (r.getBoolean(9)) { out.print("<div class='alert alert-warning'><i class='bi bi-exclamation-triangle'></i> El Vendedor ha Rechazado tu Solicitud... inténtalo de NUEVO...</div>"); }
                                                    out.print("<form action='Interfaz.jsp' method='post'>");
                                                        out.print("<input name='x' type='hidden' value='B1'>");
                                                        out.print("<div class='row'>");
                                                            out.print("<div class='col-md-6'>");
                                                                out.print("<div class='mb-3'>");
                                                                    out.print("<label class='form-label'>Número de Lotes:</label><input name='n' type='number' min='1' max='"+((r.getByte(11) == 0) ? 100 : r.getByte(11))+"' step='1' onchange=\"document.getElementById('t"+i+"').value = Number.parseFloat(this.value) * "+r.getFloat(3)+"\" class='form-control' value='1' required>");
                                                                out.print("</div>");
                                                                out.print("<div class='mb-3'>");
                                                                    out.print("<label class='form-label'>Precio Total:</label><input id='t"+i+"' name='pt' type='number' min='1' max='500000000' class='form-control' readonly value='"+r.getFloat(3)+"' required>");
                                                                out.print("</div>");
                                                                out.print("<div class='mb-3'>");
                                                                    out.print("<label class='form-label'>Lugar de la Compra:</label><input id='m"+i+"' name='u' type='text' class='form-control' readonly value='"+u+"' required>");
                                                                out.print("</div>");
                                                                out.print("<div class='mb-3'>");
                                                                    out.print("<label class='form-label'>Fecha y Hora:</label><input name='fh' type='datetime-local' class='form-control' min='"+minFH+"' required>");
                                                                out.print("</div>");
                                                                out.print("<button type='submit' class='btn btn-custom-green text-white'><i class='bi bi-send'></i> COMUNICAR AL VENDEDOR</button>");
                                                            out.print("</div>");
                                                            out.print("<div class='col-md-6'>");
                                                                out.print("<div id='gMap"+i+"' class='map-container'></div>");
                                                            out.print("</div>");
                                                        out.print("</div>");
                                                    out.print("</form>");
                                                } break;
                                                case 2: {
                                                    out.print("<div class='alert alert-info'><i class='bi bi-hourglass-split'></i> Esperando a que el Vendedor analice tu Solicitud...</div>");
                                                } break;
                                                case 3: {
                                                    out.print("<div class='alert alert-success'><i class='bi bi-check-circle'></i> ¡El Vendedor ha Aceptado tu Solicitud!</div>");
                                                    out.print("<div class='d-flex gap-2'>");
                                                        out.print("<button class='btn btn-custom-blue text-white' onclick=\"location.assign('Interfaz.jsp?x=B3&sn=true&id="+r.getLong(10)+"')\"><i class='bi bi-check'></i> FINALIZAR LA SOLICITUD</button><button class='btn btn-custom-red text-white' onclick=\"location.assign('Interfaz.jsp?x=B3&sn=false&id="+r.getLong(10)+"')\"><i class='bi bi-x'></i> CANCELAR EL PEDIDO</button>");
                                                    out.print("</div>");
                                                } break;
                                            }
                                        out.print("</div>");
                                    out.print("</div>");
                                out.print("</div>");
                            out.print("</div>");
                            i = i + 1L;
                        }
                    } else {
                        out.print("<div class='alert alert-info text-center'><i class='bi bi-info-circle'></i> Sin Pedidos de Compra registrados en tu Cuenta Personal...</div>");
                    }
                    r.close();
                    r = null;
                } catch (Exception e) {
                    out.print("<script>alert('Lo sentimos, se produjo un ERROR... intentalo de NUEVO...');</script>");
                    out.print("<script>history.back();</script>");
                }
            
      out.write("\n");
      out.write("            <hr class=\"my-5\">\n");
      out.write("            <h1 class=\"text-center mb-4\" id=\"tV\"><i class=\"bi bi-currency-dollar\"></i> Ofertas de Venta</h1>\n");
      out.write("            ");

                try {
                    r = s.executeQuery("SELECT Compra.ImgP,Compra.NP,Compra.PP,Compra.DP,Usuario.N,Usuario.AP,Usuario.AM,Compra.X,Compra.LP,Compra.TP,Compra.Fh,Compra.U,Compra.Id FROM Compra INNER JOIN Usuario ON Compra.C=Usuario.CE WHERE Compra.V='"+session.getAttribute("u")+"' AND Compra.X>1 AND Compra.X<4 ORDER BY Compra.X, Compra.Fh");
                    if (r.next()) {
                        r.beforeFirst();
                        while (r.next()) {
                            out.print("<div class='product-card'>");
                                out.print("<div class='row g-0'>");
                                    out.print("<div class='col-md-3'>");
                                        out.print("<img src='imgs/prods/"+r.getString(1)+"' class='product-img' alt='Producto'/>");
                                    out.print("</div>");
                                    out.print("<div class='col-md-9'>");
                                        out.print("<div class='card-body'>");
                                            out.print("<h3 class='card-title'>"+r.getString(2)+"</h3>");
                                            out.print("<h4 class='text-success'>$ "+r.getFloat(3)+" <small class='text-muted'>(c / LOTE)</small></h4>");
                                            out.print("<p class='card-text'>"+r.getString(4)+"</p>");
                                            out.print("<p class='text-muted'><i class='bi bi-person-circle'></i> Comprador: "+r.getString(5)+" "+r.getString(6)+" "+r.getString(7)+"</p>");
                                            if (r.getByte(8) == 2) {
                                                out.print("<div class='row mb-3'>");
                                                    out.print("<div class='col-md-6'>");
                                                        out.print("<p><strong>Lotes:</strong> "+r.getByte(9)+"</p>");
                                                        out.print("<p><strong>Total:</strong> $"+r.getFloat(10)+"</p>");
                                                    out.print("</div>");
                                                    out.print("<div class='col-md-6'>");
                                                        out.print("<p><strong>Fecha y Hora:</strong> "+r.getTimestamp(11).toLocalDateTime().format(DateTimeFormatter.ofPattern("d / MMM / uuuu -- h:mm a")).toUpperCase()+"</p>");
                                                        out.print("<p><strong>Lugar:</strong> "+r.getString(12)+"</p>");
                                                    out.print("</div>");
                                                out.print("</div>");
                                                out.print("<div class='d-flex gap-2'>");
                                                    out.print("<button class='btn btn-custom-green text-white' onclick=\"location.assign('Interfaz.jsp?x=B2&sn=true&id="+r.getLong(13)+"')\"><i class='bi bi-check'></i> ACEPTAR LA SOLICITUD</button><button class='btn btn-custom-blue text-white' onclick=\"location.assign('Interfaz.jsp?x=B2&sn=false&id="+r.getLong(13)+"')\"><i class='bi bi-x'></i> RECHAZAR LA SOLICITUD</button>");
                                                out.print("</div>");
                                            } else {
                                                out.print("<div class='alert alert-info'><i class='bi bi-hourglass-split'></i> Esperando a que el Comprador analice tu Respuesta...</div>");
                                            }
                                        out.print("</div>");
                                    out.print("</div>");
                                out.print("</div>");
                            out.print("</div>");
                        }
                    } else {
                        out.print("<div class='alert alert-info text-center'><i class='bi bi-info-circle'></i> Sin Ofertas de Venta para TI...</div>");
                    }
                    r.close();
                    r = null;
                    r = s.executeQuery("SELECT * FROM Notificacion WHERE V='"+session.getAttribute("u")+"'");
                    File f;
                    FileWriter w;
                    while (r.next()) {
                        out.print("<script>alert('"+r.getString(3)+" "+r.getString(4)+" "+r.getString(5)+" ha "+(r.getBoolean(6) ? "ACEPTADO" : "CANCELADO")+" este Pedido: "+r.getString(7)+"');</script>");
                        if (r.getBoolean(6)) {
                            f = new File("D:\\V"+r.getLong(1)+".txt");
                            f.createNewFile();
                            w = new FileWriter(f);
                            w.write("Registro Comercial\n\nProducto: "+r.getString(7)+"\nVendedor: "+na+"\nComprador: "+r.getString(3)+" "+r.getString(4)+" "+r.getString(5)+"\nNo. de Lotes: "+r.getByte(8)+"\nCosto: $"+r.getFloat(9)+"\nFecha y Hora: "+r.getTimestamp(10).toLocalDateTime().format(DateTimeFormatter.ofPattern("d / MMM / uuuu -- h:mm a")).toUpperCase()+"\nUbicacion: "+r.getString(11));
                            w.close();
                            w = null;
                        }
                    }
                    if (r.first()) {
                        s.executeUpdate("DELETE FROM Notificacion WHERE V='"+session.getAttribute("u")+"'");
                        s.execute("COMMIT");
                    }
                    r.close();
                    s.close();
                    c.close();
                } catch (Exception e) {
                    out.print("<script>alert('Lo sentimos, se produjo un ERROR... intentalo de NUEVO...');</script>");
                    out.print("<script>history.back();</script>");
                }
            
      out.write("\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
