/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-07-02 18:01:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;

public final class Mercado_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


    Connection c;
    Statement s;
    ResultSet r;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/imgs/navbar.jsp", Long.valueOf(1751388600522L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');

    try {
        Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
        c = DriverManager.getConnection("jdbc:mysql://localhost/PSHOP", "root", "n0m3l0");
        s = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
    } catch (Exception e) {
        out.print("<script>alert('Lo sentimos, se produjo un ERROR... intentalo de NUEVO...');</script>");
        out.print("<script>history.back();</script>");
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es-MX\">\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Mercado</title>\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"imgs/logo.png\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <!-- Font Awesome Icons -->\n");
      out.write("        <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" rel=\"stylesheet\">\n");
      out.write("        <!-- Google Fonts -->\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&family=Playfair+Display:wght@400;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("        \n");
      out.write("        <style>\n");
      out.write("            :root {\n");
      out.write("                --primary-green: #2d5016;\n");
      out.write("                --secondary-green: #4a7c59;\n");
      out.write("                --accent-green: #8fbc8f;\n");
      out.write("                --light-green: #e8f5e8;\n");
      out.write("                --earth-brown: #8b4513;\n");
      out.write("                --warm-orange: #ff8c42;\n");
      out.write("                --soft-yellow: #f9e784;\n");
      out.write("                --cream: #f5f5dc;\n");
      out.write("                --dark-text: #2c3e50;\n");
      out.write("                --light-text: #6c757d;\n");
      out.write("            }\n");
      out.write("            body {\n");
      out.write("                font-family: 'Poppins', sans-serif;\n");
      out.write("                background: #f0f0f0;\n");
      out.write("                color: var(--dark-text);\n");
      out.write("                min-height: 100vh;\n");
      out.write("            }\n");
      out.write("            .hero-section {\n");
      out.write("                background: linear-gradient(rgba(45, 80, 22, 0.8), rgba(45, 80, 22, 0.8)), url(imgs/fondo3.png) center/cover;\n");
      out.write("                color: white;\n");
      out.write("                padding: 4rem 0;\n");
      out.write("                margin-bottom: 3rem;\n");
      out.write("                border-radius: 0 0 50px 50px;\n");
      out.write("            }\n");
      out.write("            .hero-title {\n");
      out.write("                font-family: 'Playfair Display', serif;\n");
      out.write("                font-size: 3.5rem;\n");
      out.write("                font-weight: 700;\n");
      out.write("                text-shadow: 2px 2px 4px rgba(0,0,0,0.3);\n");
      out.write("                margin-bottom: 1rem;\n");
      out.write("            }\n");
      out.write("            .hero-subtitle {\n");
      out.write("                font-size: 1.2rem;\n");
      out.write("                opacity: 0.9;\n");
      out.write("                margin-bottom: 0;\n");
      out.write("            }\n");
      out.write("            .category-section {\n");
      out.write("                margin-bottom: 3rem;\n");
      out.write("                background: white;\n");
      out.write("                border-radius: 20px;\n");
      out.write("                box-shadow: 0 10px 30px rgba(0,0,0,0.1);\n");
      out.write("                overflow: hidden;\n");
      out.write("                transition: transform 0.3s ease, box-shadow 0.3s ease;\n");
      out.write("            }\n");
      out.write("            .category-section:hover {\n");
      out.write("                transform: translateY(-5px);\n");
      out.write("                box-shadow: 0 15px 40px rgba(0,0,0,0.15);\n");
      out.write("            }\n");
      out.write("            .category-header {\n");
      out.write("                padding: 1.5rem 2rem;\n");
      out.write("                font-family: 'Playfair Display', serif;\n");
      out.write("                font-size: 1.8rem;\n");
      out.write("                font-weight: 600;\n");
      out.write("                color: white;\n");
      out.write("                margin: 0;\n");
      out.write("                display: flex;\n");
      out.write("                align-items: center;\n");
      out.write("                gap: 15px;\n");
      out.write("            }\n");
      out.write("            .category-decorative { background: linear-gradient(135deg, var(--secondary-green), var(--accent-green)); }\n");
      out.write("            .category-garden { background: linear-gradient(135deg, var(--earth-brown), var(--warm-orange)); }\n");
      out.write("            .category-aquatic { background: linear-gradient(135deg, #4682b4, #87ceeb); }\n");
      out.write("            .category-trees { background: linear-gradient(135deg, var(--primary-green), var(--secondary-green)); }\n");
      out.write("            .category-algae { background: linear-gradient(135deg, #228b22, #90ee90); }\n");
      out.write("            .category-fertilizers { background: linear-gradient(135deg, var(--warm-orange), var(--soft-yellow)); }\n");
      out.write("            .category-tools { background: linear-gradient(135deg, #696969, #a9a9a9); }\n");
      out.write("            .products-container {\n");
      out.write("                padding: 2rem;\n");
      out.write("            }\n");
      out.write("            .product-card {\n");
      out.write("                background: white;\n");
      out.write("                border-radius: 15px;\n");
      out.write("                box-shadow: 0 5px 15px rgba(0,0,0,0.08);\n");
      out.write("                margin-bottom: 2rem;\n");
      out.write("                overflow: hidden;\n");
      out.write("                transition: all 0.3s ease;\n");
      out.write("                border: 1px solid rgba(0,0,0,0.05);\n");
      out.write("            }\n");
      out.write("            .product-card:hover {\n");
      out.write("                transform: translateY(-3px);\n");
      out.write("                box-shadow: 0 8px 25px rgba(0,0,0,0.15);\n");
      out.write("            }\n");
      out.write("            .product-image {\n");
      out.write("                width: 100%;\n");
      out.write("                height: 180px;\n");
      out.write("                object-fit: cover;\n");
      out.write("                border-radius: 10px;\n");
      out.write("                margin-bottom: 1rem;\n");
      out.write("            }\n");
      out.write("            .product-title {\n");
      out.write("                font-family: 'Playfair Display', serif;\n");
      out.write("                font-size: 1.4rem;\n");
      out.write("                font-weight: 600;\n");
      out.write("                color: var(--primary-green);\n");
      out.write("                margin-bottom: 0.5rem;\n");
      out.write("            }\n");
      out.write("            .product-price {\n");
      out.write("                font-size: 1.5rem;\n");
      out.write("                font-weight: 700;\n");
      out.write("                color: var(--earth-brown);\n");
      out.write("                margin-bottom: 1rem;\n");
      out.write("            }\n");
      out.write("            .product-description {\n");
      out.write("                color: var(--light-text);\n");
      out.write("                font-size: 0.95rem;\n");
      out.write("                line-height: 1.5;\n");
      out.write("                margin-bottom: 1rem;\n");
      out.write("            }\n");
      out.write("            .seller-info {\n");
      out.write("                background: var(--light-green);\n");
      out.write("                padding: 1rem;\n");
      out.write("                border-radius: 10px;\n");
      out.write("                margin-bottom: 1rem;\n");
      out.write("            }\n");
      out.write("            .seller-name {\n");
      out.write("                font-weight: 600;\n");
      out.write("                color: var(--primary-green);\n");
      out.write("                font-size: 0.9rem;\n");
      out.write("                margin-bottom: 0.3rem;\n");
      out.write("            }\n");
      out.write("            .stock-info {\n");
      out.write("                font-size: 0.85rem;\n");
      out.write("                color: var(--secondary-green);\n");
      out.write("                font-weight: 500;\n");
      out.write("            }\n");
      out.write("            .buy-btn {\n");
      out.write("                background: linear-gradient(135deg, var(--secondary-green), var(--accent-green));\n");
      out.write("                border: none;\n");
      out.write("                color: white;\n");
      out.write("                padding: 12px 0;\n");
      out.write("                font-weight: 600;\n");
      out.write("                border-radius: 10px;\n");
      out.write("                width: 100%;\n");
      out.write("                transition: all 0.3s ease;\n");
      out.write("                text-transform: uppercase;\n");
      out.write("                letter-spacing: 0.5px;\n");
      out.write("                font-size: 0.9rem;\n");
      out.write("            }\n");
      out.write("            .buy-btn:hover {\n");
      out.write("                background: linear-gradient(135deg, var(--accent-green), var(--secondary-green));\n");
      out.write("                transform: translateY(-2px);\n");
      out.write("                box-shadow: 0 5px 15px rgba(74, 124, 89, 0.4);\n");
      out.write("                color: white;\n");
      out.write("            }\n");
      out.write("            .no-products {\n");
      out.write("                text-align: center;\n");
      out.write("                padding: 3rem 2rem;\n");
      out.write("                color: var(--light-text);\n");
      out.write("                font-style: italic;\n");
      out.write("            }\n");
      out.write("            .category-icon {\n");
      out.write("                font-size: 1.5rem;\n");
      out.write("            }\n");
      out.write("            @media (max-width: 768px) {\n");
      out.write("                .hero-title {\n");
      out.write("                    font-size: 2.5rem;\n");
      out.write("                }\n");
      out.write("                .category-header {\n");
      out.write("                    font-size: 1.5rem;\n");
      out.write("                    padding: 1rem 1.5rem;\n");
      out.write("                }\n");
      out.write("                .products-container {\n");
      out.write("                    padding: 1rem;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("        <script>\n");
      out.write("            document.addEventListener('DOMContentLoaded', function () {\n");
      out.write("                window.location.hash = \"no-back-button\";\n");
      out.write("                window.location.hash = \"Again-No-back-button\";\n");
      out.write("                window.onhashchange = function () {\n");
      out.write("                    window.location.hash = \"\";\n");
      out.write("                };\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
      out.write("<style>\n");
      out.write("    body {\n");
      out.write("        font-family: 'Inter', sans-serif;\n");
      out.write("        margin: 0;\n");
      out.write("        padding-top: 120px;\n");
      out.write("        background-color: #f8f9fa;\n");
      out.write("    }\n");
      out.write("    iframe {\n");
      out.write("        width: 100%;\n");
      out.write("        height: calc(100vh - 120px);\n");
      out.write("        border: none;\n");
      out.write("    }\n");
      out.write("    .navbar-top {\n");
      out.write("        background-color: #198754;\n");
      out.write("    }\n");
      out.write("    .navbar-bottom {\n");
      out.write("        background-color: #000;\n");
      out.write("        z-index: 0;\n");
      out.write("    }\n");
      out.write("    .navbar-brand img {\n");
      out.write("        width: 2em;\n");
      out.write("        height: 2em;\n");
      out.write("        margin-right: 0.5rem;\n");
      out.write("    }\n");
      out.write("    .nav-link {\n");
      out.write("        color: white !important;\n");
      out.write("    }\n");
      out.write("    .nav-link:hover {\n");
      out.write("        color: #a4f3b5 !important;\n");
      out.write("    }\n");
      out.write("    .dropdown-menu a:hover {\n");
      out.write("        background-color: #198754;\n");
      out.write("        color: white !important;\n");
      out.write("    }\n");
      out.write("    .dropdown-toggle::after {\n");
      out.write("        margin-left: 0.4em;\n");
      out.write("    }\n");
      out.write("    @media (max-width: 768px) {\n");
      out.write("        body {\n");
      out.write("            padding-top: 170px;\n");
      out.write("        }\n");
      out.write("        iframe {\n");
      out.write("            height: calc(100vh - 170px);\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("    .navbar-bottom .navbar-nav {\n");
      out.write("        display: flex;\n");
      out.write("        justify-content: space-between;\n");
      out.write("        width: 100%;\n");
      out.write("    }\n");
      out.write("    .navbar-bottom .nav-item {\n");
      out.write("        flex-grow: 1;\n");
      out.write("        text-align: center;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("<script>\n");
      out.write("    document.addEventListener('DOMContentLoaded', function () {\n");
      out.write("        window.location.hash = \"no-back-button\";\n");
      out.write("        window.location.hash = \"Again-No-back-button\";\n");
      out.write("        window.onhashchange = function () {\n");
      out.write("            window.location.hash = \"\";\n");
      out.write("        };\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("<body style='background-color: #e9e9e9;'>\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark navbar-top fixed-top shadow-sm\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <a class=\"navbar-brand d-flex align-items-center\" href=\"#\">\n");
      out.write("            <img src=\"imgs/logo.png\" alt=\"Logo\">\n");
      out.write("            <span class=\"fw\">PlantiSHOP</span>\n");
      out.write("        </a>\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#topNavbar\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <ul class=\"navbar-nav ms-auto\">\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"Ventas.jsp\">Tus Ventas</a></li>\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mensajeria.jsp\">Tus Compras y Pedidos</a></li>\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"FAQ.html\">FAQ</a></li>\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"Premium.jsp\">PREMIUM</a></li>\n");
      out.write("        </ul>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"topNavbar\">\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\n");
      out.write("                <li class=\"nav-item dropdown\">\n");
      out.write("                    <a class=\"nav-link dropdown-toggle d-flex align-items-center\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\">\n");
      out.write("                        <img src=\"imgs/perfil.jpg\" alt=\"Perfil\" class=\"rounded-circle me-2\" style=\"width: 2em; height: 2em;\">\n");
      out.write("                        Perfil\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-end\">\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"Perfil.jsp\">Tu Perfil</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"Jardin.jsp\">Tu Jardín</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"Interfaz.jsp?x=E\">Cerrar Sesión</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark navbar-bottom fixed-top shadow-sm\" style=\"top: 56px;\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#bottomNavbar\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"bottomNavbar\">\n");
      out.write("            <ul class=\"navbar-nav\">\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#PD\">Plantas Decorativas</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#PH\">Plantas de Huerto</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#PA\">Plantas Acuáticas</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#A\">Árboles</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#AH\">Algas y Hongos</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#F\">Fertilizantes</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#H\">Herramientas</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>");
      out.write("\n");
      out.write("        \n");
      out.write("        <div class=\"hero-section\">\n");
      out.write("            <div class=\"container text-center\">\n");
      out.write("                <h1 class=\"hero-title\">\n");
      out.write("                    <i class=\"fas fa-leaf me-3\"></i>\n");
      out.write("                    Mercado Verde\n");
      out.write("                </h1>\n");
      out.write("                <p class=\"hero-subtitle\">Tu destino para Plantas, Jardinería y Vida Natural</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"category-section\">\n");
      out.write("                <div class=\"category-header category-decorative\">\n");
      out.write("                    <i class=\"fas fa-seedling category-icon\"></i>\n");
      out.write("                    Plantas Decorativas\n");
      out.write("                </div>\n");
      out.write("                <div class=\"products-container\" id=\"PD\">\n");
      out.write("                    ");

                        try {
                            r = s.executeQuery("SELECT Producto.Img,Producto.Id,Producto.N,Producto.P,Producto.D,Usuario.N,Usuario.AP,Usuario.AM,Producto.Cupo FROM Producto INNER JOIN Usuario ON Producto.CE=Usuario.CE WHERE Producto.T='PD' AND Producto.Cupo>0 AND Producto.CE!='"+session.getAttribute("u")+"' ORDER BY Producto.Pop DESC, Producto.Cupo DESC");
                            if (r.next()) {
                                r.beforeFirst();
                                while (r.next()) {
                                    out.print("<div class='row mb-4'>");
                                        out.print("<div class='col-lg-3 col-md-4 col-sm-6 mb-3'>");
                                            out.print("<div class='text-center'>");
                                                out.print("<img src='imgs/prods/"+r.getString(1)+"' alt='Planta Decorativa' class='product-image'/>");
                                                out.print("<button class='btn buy-btn' onclick=\"location.assign('Interfaz.jsp?x=B&id="+r.getLong(2)+"')\"><i class='fas fa-shopping-cart me-2'></i>COMPRAR</button>");
                                            out.print("</div>");
                                        out.print("</div>");
                                        out.print("<div class='col-lg-9 col-md-8 col-sm-6'>");
                                            out.print("<div class='product-card h-100'>");
                                                out.print("<div class='p-3'>");
                                                    out.print("<h3 class='product-title'>"+r.getString(3)+"</h3>");
                                                    out.print("<div class='product-price'>$ "+r.getFloat(4)+"</div>");
                                                    out.print("<p class='product-description'>"+r.getString(5)+"</p>");
                                                    out.print("<div class='seller-info'>");
                                                        out.print("<div class='seller-name'><i class='fas fa-user me-2'></i>Vendedor: "+r.getString(6)+" "+r.getString(7)+" "+r.getString(8)+"</div>");
                                                        out.print("<div class='stock-info'><i class='fas fa-box me-2'></i>Cupo: "+r.getInt(9)+"</div>");
                                                    out.print("</div>");
                                                out.print("</div>");
                                            out.print("</div>");
                                        out.print("</div>");
                                    out.print("</div>");
                                }
                            } else {
                                out.print("<div class='no-products'><i class='fas fa-leaf fa-3x mb-3 opacity-50'></i><p>Lo sentimos... NO hay Ofertas en este apartado!</p></div>");
                            }
                            r.close();
                            r = null;
                        } catch (Exception e) {
                            out.print("<script>alert('Lo sentimos, se produjo un ERROR... intentalo de NUEVO...');</script>");
                            out.print("<script>history.back();</script>");
                        }
                    
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"category-section\">\n");
      out.write("                <div class=\"category-header category-garden\">\n");
      out.write("                    <i class=\"fas fa-carrot category-icon\"></i>\n");
      out.write("                    Plantas de Huerto\n");
      out.write("                </div>\n");
      out.write("                <div class=\"products-container\" id=\"PH\">\n");
      out.write("                    ");

                        try {
                            r = s.executeQuery("SELECT Producto.Img,Producto.Id,Producto.N,Producto.P,Producto.D,Usuario.N,Usuario.AP,Usuario.AM,Producto.Cupo FROM Producto INNER JOIN Usuario ON Producto.CE=Usuario.CE WHERE Producto.T='PH' AND Producto.Cupo>0 AND Producto.CE!='"+session.getAttribute("u")+"' ORDER BY Producto.Pop DESC, Producto.Cupo DESC");
                            if (r.next()) {
                                r.beforeFirst();
                                while (r.next()) {
                                    out.print("<div class='row mb-4'>");
                                        out.print("<div class='col-lg-3 col-md-4 col-sm-6 mb-3'>");
                                            out.print("<div class='text-center'>");
                                                out.print("<img src='imgs/prods/"+r.getString(1)+"' alt='Planta de Huerto' class='product-image'/>");
                                                out.print("<button class='btn buy-btn' onclick=\"location.assign('Interfaz.jsp?x=B&id="+r.getLong(2)+"')\"><i class='fas fa-shopping-cart me-2'></i>COMPRAR</button>");
                                            out.print("</div>");
                                        out.print("</div>");
                                        out.print("<div class='col-lg-9 col-md-8 col-sm-6'>");
                                            out.print("<div class='product-card h-100'>");
                                                out.print("<div class='p-3'>");
                                                    out.print("<h3 class='product-title'>"+r.getString(3)+"</h3>");
                                                    out.print("<div class='product-price'>$ "+r.getFloat(4)+"</div>");
                                                    out.print("<p class='product-description'>"+r.getString(5)+"</p>");
                                                    out.print("<div class='seller-info'>");
                                                        out.print("<div class='seller-name'><i class='fas fa-user me-2'></i>Vendedor: "+r.getString(6)+" "+r.getString(7)+" "+r.getString(8)+"</div>");
                                                        out.print("<div class='stock-info'><i class='fas fa-box me-2'></i>Cupo: "+r.getInt(9)+"</div>");
                                                    out.print("</div>");
                                                out.print("</div>");
                                            out.print("</div>");
                                        out.print("</div>");
                                    out.print("</div>");
                                }
                            } else {
                                out.print("<div class='no-products'><i class='fas fa-carrot fa-3x mb-3 opacity-50'></i><p>Lo sentimos... NO hay Ofertas en este apartado!</p></div>");
                            }
                            r.close();
                            r = null;
                        } catch (Exception e) {
                            out.print("<script>alert('Lo sentimos, se produjo un ERROR... intentalo de NUEVO...');</script>");
                            out.print("<script>history.back();</script>");
                        }
                    
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"category-section\">\n");
      out.write("                <div class=\"category-header category-aquatic\">\n");
      out.write("                    <i class=\"fas fa-water category-icon\"></i>\n");
      out.write("                    Plantas Acuáticas\n");
      out.write("                </div>\n");
      out.write("                <div class=\"products-container\" id=\"PA\">\n");
      out.write("                    ");

                        try {
                            r = s.executeQuery("SELECT Producto.Img,Producto.Id,Producto.N,Producto.P,Producto.D,Usuario.N,Usuario.AP,Usuario.AM,Producto.Cupo FROM Producto INNER JOIN Usuario ON Producto.CE=Usuario.CE WHERE Producto.T='PA' AND Producto.Cupo>0 AND Producto.CE!='"+session.getAttribute("u")+"' ORDER BY Producto.Pop DESC, Producto.Cupo DESC");
                            if (r.next()) {
                                r.beforeFirst();
                                while (r.next()) {
                                    out.print("<div class='row mb-4'>");
                                        out.print("<div class='col-lg-3 col-md-4 col-sm-6 mb-3'>");
                                            out.print("<div class='text-center'>");
                                                out.print("<img src='imgs/prods/"+r.getString(1)+"' alt='Planta Acuatica' class='product-image'/>");
                                                out.print("<button class='btn buy-btn' onclick=\"location.assign('Interfaz.jsp?x=B&id="+r.getLong(2)+"')\"><i class='fas fa-shopping-cart me-2'></i>COMPRAR</button>");
                                            out.print("</div>");
                                        out.print("</div>");
                                        out.print("<div class='col-lg-9 col-md-8 col-sm-6'>");
                                            out.print("<div class='product-card h-100'>");
                                                out.print("<div class='p-3'>");
                                                    out.print("<h3 class='product-title'>"+r.getString(3)+"</h3>");
                                                    out.print("<div class='product-price'>$ "+r.getFloat(4)+"</div>");
                                                    out.print("<p class='product-description'>"+r.getString(5)+"</p>");
                                                    out.print("<div class='seller-info'>");
                                                        out.print("<div class='seller-name'><i class='fas fa-user me-2'></i>Vendedor: "+r.getString(6)+" "+r.getString(7)+" "+r.getString(8)+"</div>");
                                                        out.print("<div class='stock-info'><i class='fas fa-box me-2'></i>Cupo: "+r.getInt(9)+"</div>");
                                                    out.print("</div>");
                                                out.print("</div>");
                                            out.print("</div>");
                                        out.print("</div>");
                                    out.print("</div>");
                                }
                            } else {
                                out.print("<div class='no-products'><i class='fas fa-water fa-3x mb-3 opacity-50'></i><p>Lo sentimos... NO hay Ofertas en este apartado!</p></div>");
                            }
                            r.close();
                            r = null;
                        } catch (Exception e) {
                            out.print("<script>alert('Lo sentimos, se produjo un ERROR... intentalo de NUEVO...');</script>");
                            out.print("<script>history.back();</script>");
                        }
                    
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"category-section\">\n");
      out.write("                <div class=\"category-header category-trees\">\n");
      out.write("                    <i class=\"fas fa-tree category-icon\"></i>\n");
      out.write("                    Árboles\n");
      out.write("                </div>\n");
      out.write("                <div class=\"products-container\" id=\"A\">\n");
      out.write("                    ");

                        try {
                            r = s.executeQuery("SELECT Producto.Img,Producto.Id,Producto.N,Producto.P,Producto.D,Usuario.N,Usuario.AP,Usuario.AM,Producto.Cupo FROM Producto INNER JOIN Usuario ON Producto.CE=Usuario.CE WHERE Producto.T='A' AND Producto.Cupo>0 AND Producto.CE!='"+session.getAttribute("u")+"' ORDER BY Producto.Pop DESC, Producto.Cupo DESC");
                            if (r.next()) {
                                r.beforeFirst();
                                while (r.next()) {
                                    out.print("<div class='row mb-4'>");
                                        out.print("<div class='col-lg-3 col-md-4 col-sm-6 mb-3'>");
                                            out.print("<div class='text-center'>");
                                                out.print("<img src='imgs/prods/"+r.getString(1)+"' alt='Arbol' class='product-image'/>");
                                                out.print("<button class='btn buy-btn' onclick=\"location.assign('Interfaz.jsp?x=B&id="+r.getLong(2)+"')\"><i class='fas fa-shopping-cart me-2'></i>COMPRAR</button>");
                                            out.print("</div>");
                                        out.print("</div>");
                                        out.print("<div class='col-lg-9 col-md-8 col-sm-6'>");
                                            out.print("<div class='product-card h-100'>");
                                                out.print("<div class='p-3'>");
                                                    out.print("<h3 class='product-title'>"+r.getString(3)+"</h3>");
                                                    out.print("<div class='product-price'>$ "+r.getFloat(4)+"</div>");
                                                    out.print("<p class='product-description'>"+r.getString(5)+"</p>");
                                                    out.print("<div class='seller-info'>");
                                                        out.print("<div class='seller-name'><i class='fas fa-user me-2'></i>Vendedor: "+r.getString(6)+" "+r.getString(7)+" "+r.getString(8)+"</div>");
                                                        out.print("<div class='stock-info'><i class='fas fa-box me-2'></i>Cupo: "+r.getInt(9)+"</div>");
                                                    out.print("</div>");
                                                out.print("</div>");
                                            out.print("</div>");
                                        out.print("</div>");
                                    out.print("</div>");
                                }
                            } else {
                                out.print("<div class='no-products'><i class='fas fa-tree fa-3x mb-3 opacity-50'></i><p>Lo sentimos... NO hay Ofertas en este apartado!</p></div>");
                            }
                            r.close();
                            r = null;
                        } catch (Exception e) {
                            out.print("<script>alert('Lo sentimos, se produjo un ERROR... intentalo de NUEVO...');</script>");
                            out.print("<script>history.back();</script>");
                        }
                    
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"category-section\">\n");
      out.write("                <div class=\"category-header category-algae\">\n");
      out.write("                    <i class=\"fas fa-microscope category-icon\"></i>\n");
      out.write("                    Algas y Hongos\n");
      out.write("                </div>\n");
      out.write("                <div class=\"products-container\" id=\"AH\">\n");
      out.write("                    ");

                        try {
                            r = s.executeQuery("SELECT Producto.Img,Producto.Id,Producto.N,Producto.P,Producto.D,Usuario.N,Usuario.AP,Usuario.AM,Producto.Cupo FROM Producto INNER JOIN Usuario ON Producto.CE=Usuario.CE WHERE Producto.T='AH' AND Producto.Cupo>0 AND Producto.CE!='"+session.getAttribute("u")+"' ORDER BY Producto.Pop DESC, Producto.Cupo DESC");
                            if (r.next()) {
                                r.beforeFirst();
                                while (r.next()) {
                                    out.print("<div class='row mb-4'>");
                                        out.print("<div class='col-lg-3 col-md-4 col-sm-6 mb-3'>");
                                            out.print("<div class='text-center'>");
                                                out.print("<img src='imgs/prods/"+r.getString(1)+"' alt='Alga / Hongo' class='product-image'/>");
                                                out.print("<button class='btn buy-btn' onclick=\"location.assign('Interfaz.jsp?x=B&id="+r.getLong(2)+"')\"><i class='fas fa-shopping-cart me-2'></i>COMPRAR</button>");
                                            out.print("</div>");
                                        out.print("</div>");
                                        out.print("<div class='col-lg-9 col-md-8 col-sm-6'>");
                                            out.print("<div class='product-card h-100'>");
                                                out.print("<div class='p-3'>");
                                                    out.print("<h3 class='product-title'>"+r.getString(3)+"</h3>");
                                                    out.print("<div class='product-price'>$ "+r.getFloat(4)+"</div>");
                                                    out.print("<p class='product-description'>"+r.getString(5)+"</p>");
                                                    out.print("<div class='seller-info'>");
                                                        out.print("<div class='seller-name'><i class='fas fa-user me-2'></i>Vendedor: "+r.getString(6)+" "+r.getString(7)+" "+r.getString(8)+"</div>");
                                                        out.print("<div class='stock-info'><i class='fas fa-box me-2'></i>Cupo: "+r.getInt(9)+"</div>");
                                                    out.print("</div>");
                                                out.print("</div>");
                                            out.print("</div>");
                                        out.print("</div>");
                                    out.print("</div>");
                                }
                            } else {
                                out.print("<div class='no-products'><i class='fas fa-microscope fa-3x mb-3 opacity-50'></i><p>Lo sentimos... NO hay Ofertas en este apartado!</p></div>");
                            }
                            r.close();
                            r = null;
                        } catch (Exception e) {
                            out.print("<script>alert('Lo sentimos, se produjo un ERROR... intentalo de NUEVO...');</script>");
                            out.print("<script>history.back();</script>");
                        }
                    
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"category-section\">\n");
      out.write("                <div class=\"category-header category-fertilizers\">\n");
      out.write("                    <i class=\"fas fa-flask category-icon\"></i>\n");
      out.write("                    Fertilizantes\n");
      out.write("                </div>\n");
      out.write("                <div class=\"products-container\" id=\"F\">\n");
      out.write("                    ");

                        try {
                            r = s.executeQuery("SELECT Producto.Img,Producto.Id,Producto.N,Producto.P,Producto.D,Usuario.N,Usuario.AP,Usuario.AM,Producto.Cupo FROM Producto INNER JOIN Usuario ON Producto.CE=Usuario.CE WHERE Producto.T='F' AND Producto.Cupo>0 AND Producto.CE!='"+session.getAttribute("u")+"' ORDER BY Producto.Pop DESC, Producto.Cupo DESC");
                            if (r.next()) {
                                r.beforeFirst();
                                while (r.next()) {
                                    out.print("<div class='row mb-4'>");
                                        out.print("<div class='col-lg-3 col-md-4 col-sm-6 mb-3'>");
                                            out.print("<div class='text-center'>");
                                                out.print("<img src='imgs/prods/"+r.getString(1)+"' alt='Fertilizante' class='product-image'/>");
                                                out.print("<button class='btn buy-btn' onclick=\"location.assign('Interfaz.jsp?x=B&id="+r.getLong(2)+"')\"><i class='fas fa-shopping-cart me-2'></i>COMPRAR</button>");
                                            out.print("</div>");
                                        out.print("</div>");
                                        out.print("<div class='col-lg-9 col-md-8 col-sm-6'>");
                                            out.print("<div class='product-card h-100'>");
                                                out.print("<div class='p-3'>");
                                                    out.print("<h3 class='product-title'>"+r.getString(3)+"</h3>");
                                                    out.print("<div class='product-price'>$ "+r.getFloat(4)+"</div>");
                                                    out.print("<p class='product-description'>"+r.getString(5)+"</p>");
                                                    out.print("<div class='seller-info'>");
                                                        out.print("<div class='seller-name'><i class='fas fa-user me-2'></i>Vendedor: "+r.getString(6)+" "+r.getString(7)+" "+r.getString(8)+"</div>");
                                                        out.print("<div class='stock-info'><i class='fas fa-box me-2'></i>Cupo: "+r.getInt(9)+"</div>");
                                                    out.print("</div>");
                                                out.print("</div>");
                                            out.print("</div>");
                                        out.print("</div>");
                                    out.print("</div>");
                                }
                            } else {
                                out.print("<div class='no-products'><i class='fas fa-flask fa-3x mb-3 opacity-50'></i><p>Lo sentimos... NO hay Ofertas en este apartado!</p></div>");
                            }
                            r.close();
                            r = null;
                        } catch (Exception e) {
                            out.print("<script>alert('Lo sentimos, se produjo un ERROR... intentalo de NUEVO...');</script>");
                            out.print("<script>history.back();</script>");
                        }
                    
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"category-section\">\n");
      out.write("                <div class=\"category-header category-tools\">\n");
      out.write("                    <i class=\"fas fa-tools category-icon\"></i>\n");
      out.write("                    Herramientas\n");
      out.write("                </div>\n");
      out.write("                <div class=\"products-container\" id=\"H\">\n");
      out.write("                    ");

                        try {
                            r = s.executeQuery("SELECT Producto.Img,Producto.Id,Producto.N,Producto.P,Producto.D,Usuario.N,Usuario.AP,Usuario.AM,Producto.Cupo FROM Producto INNER JOIN Usuario ON Producto.CE=Usuario.CE WHERE Producto.T='H' AND Producto.Cupo>0 AND Producto.CE!='"+session.getAttribute("u")+"' ORDER BY Producto.Pop DESC, Producto.Cupo DESC");
                            if (r.next()) {
                                r.beforeFirst();
                                while (r.next()) {
                                    out.print("<div class='row mb-4'>");
                                        out.print("<div class='col-lg-3 col-md-4 col-sm-6 mb-3'>");
                                            out.print("<div class='text-center'>");
                                                out.print("<img src='imgs/prods/"+r.getString(1)+"' alt='Herramienta' class='product-image'/>");
                                                out.print("<button class='btn buy-btn' onclick=\"location.assign('Interfaz.jsp?x=B&id="+r.getLong(2)+"')\"><i class='fas fa-shopping-cart me-2'></i>COMPRAR</button>");
                                            out.print("</div>");
                                        out.print("</div>");
                                        out.print("<div class='col-lg-9 col-md-8 col-sm-6'>");
                                            out.print("<div class='product-card h-100'>");
                                                out.print("<div class='p-3'>");
                                                    out.print("<h3 class='product-title'>"+r.getString(3)+"</h3>");
                                                    out.print("<div class='product-price'>$ "+r.getFloat(4)+"</div>");
                                                    out.print("<p class='product-description'>"+r.getString(5)+"</p>");
                                                    out.print("<div class='seller-info'>");
                                                        out.print("<div class='seller-name'><i class='fas fa-user me-2'></i>Vendedor: "+r.getString(6)+" "+r.getString(7)+" "+r.getString(8)+"</div>");
                                                        out.print("<div class='stock-info'><i class='fas fa-box me-2'></i>Cupo: "+r.getInt(9)+"</div>");
                                                    out.print("</div>");
                                                out.print("</div>");
                                            out.print("</div>");
                                        out.print("</div>");
                                    out.print("</div>");
                                }
                            } else {
                                out.print("<div class='no-products'><i class='fas fa-tools fa-3x mb-3 opacity-50'></i><p>Lo sentimos... NO hay Ofertas en este apartado!</p></div>");
                            }
                            r.close();
                            s.close();
                            c.close();
                        } catch (Exception e) {
                            out.print("<script>alert('Lo sentimos, se produjo un ERROR... intentalo de NUEVO...');</script>");
                            out.print("<script>history.back();</script>");
                        }
                    
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
