/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-07-02 18:01:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.time.format.DateTimeFormatter;

public final class Premium_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


    Connection c;
    Statement s;
    ResultSet r;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/imgs/navbar.jsp", Long.valueOf(1751388600522L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.time.temporal.ChronoUnit");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es-MX\">\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Premium</title>\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"imgs/logo.png\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("        <style>\n");
      out.write("            :root {\n");
      out.write("                --primary-green: #2d5016;\n");
      out.write("                --secondary-green: #4a7c28;\n");
      out.write("                --accent-green: #6ca83c;\n");
      out.write("                --light-green: #8bc34a;\n");
      out.write("                --pale-green: #c8e6c9;\n");
      out.write("                --earth-brown: #5d4037;\n");
      out.write("                --warm-beige: #8d6e63;\n");
      out.write("                --background-color: #f0f0f0;\n");
      out.write("            }\n");
      out.write("            body {\n");
      out.write("                background-color: var(--background-color) !important;\n");
      out.write("                font-family: 'Poppins', sans-serif;\n");
      out.write("                color: var(--primary-green);\n");
      out.write("                min-height: 100vh;\n");
      out.write("            }\n");
      out.write("            .premium-header {\n");
      out.write("                background: linear-gradient(135deg, var(--primary-green) 0%, var(--secondary-green) 100%);\n");
      out.write("                color: white;\n");
      out.write("                padding: 2rem 0;\n");
      out.write("                margin-bottom: 2rem;\n");
      out.write("                border-radius: 0 0 20px 20px;\n");
      out.write("                box-shadow: 0 4px 15px rgba(45, 80, 22, 0.3);\n");
      out.write("            }\n");
      out.write("            .premium-title {\n");
      out.write("                font-weight: 700;\n");
      out.write("                font-size: 2.5rem;\n");
      out.write("                margin-bottom: 1rem;\n");
      out.write("                text-shadow: 2px 2px 4px rgba(0,0,0,0.3);\n");
      out.write("            }\n");
      out.write("            .premium-description {\n");
      out.write("                font-size: 1.1rem;\n");
      out.write("                opacity: 0.95;\n");
      out.write("                line-height: 1.6;\n");
      out.write("            }\n");
      out.write("            .feature-card {\n");
      out.write("                background: white;\n");
      out.write("                border-radius: 15px;\n");
      out.write("                padding: 2rem;\n");
      out.write("                margin-bottom: 1.5rem;\n");
      out.write("                box-shadow: 0 8px 25px rgba(45, 80, 22, 0.1);\n");
      out.write("                border: 2px solid var(--pale-green);\n");
      out.write("                transition: all 0.3s ease;\n");
      out.write("            }\n");
      out.write("            .feature-card:hover {\n");
      out.write("                transform: translateY(-5px);\n");
      out.write("                box-shadow: 0 12px 35px rgba(45, 80, 22, 0.15);\n");
      out.write("            }\n");
      out.write("            .btn-premium {\n");
      out.write("                background: linear-gradient(135deg, var(--accent-green) 0%, var(--light-green) 100%);\n");
      out.write("                border: none;\n");
      out.write("                color: white;\n");
      out.write("                font-weight: 600;\n");
      out.write("                padding: 1rem 2rem;\n");
      out.write("                border-radius: 50px;\n");
      out.write("                font-size: 1.1rem;\n");
      out.write("                transition: all 0.3s ease;\n");
      out.write("                box-shadow: 0 4px 15px rgba(108, 168, 60, 0.4);\n");
      out.write("            }\n");
      out.write("            .btn-premium:hover {\n");
      out.write("                background: linear-gradient(135deg, var(--light-green) 0%, var(--accent-green) 100%);\n");
      out.write("                transform: translateY(-2px);\n");
      out.write("                box-shadow: 0 6px 20px rgba(108, 168, 60, 0.6);\n");
      out.write("                color: white;\n");
      out.write("            }\n");
      out.write("            .btn-basil {\n");
      out.write("                background: linear-gradient(135deg, #00bcd4 0%, #0097a7 100%);\n");
      out.write("                box-shadow: 0 4px 15px rgba(0, 188, 212, 0.4);\n");
      out.write("            }\n");
      out.write("            .btn-basil:hover {\n");
      out.write("                background: linear-gradient(135deg, #0097a7 0%, #006064 100%);\n");
      out.write("                box-shadow: 0 6px 20px rgba(0, 188, 212, 0.6);\n");
      out.write("            }\n");
      out.write("            .btn-analytics {\n");
      out.write("                background: linear-gradient(135deg, #ff9800 0%, #f57c00 100%);\n");
      out.write("                box-shadow: 0 4px 15px rgba(255, 152, 0, 0.4);\n");
      out.write("            }\n");
      out.write("            .btn-analytics:hover {\n");
      out.write("                background: linear-gradient(135deg, #f57c00 0%, #e65100 100%);\n");
      out.write("                box-shadow: 0 6px 20px rgba(255, 152, 0, 0.6);\n");
      out.write("            }\n");
      out.write("            .subscription-form {\n");
      out.write("                background: white;\n");
      out.write("                border-radius: 20px;\n");
      out.write("                padding: 2.5rem;\n");
      out.write("                box-shadow: 0 10px 30px rgba(45, 80, 22, 0.1);\n");
      out.write("                border: 3px solid var(--pale-green);\n");
      out.write("            }\n");
      out.write("            .form-control {\n");
      out.write("                border: 2px solid var(--pale-green);\n");
      out.write("                border-radius: 10px;\n");
      out.write("                padding: 0.75rem 1rem;\n");
      out.write("                font-size: 1rem;\n");
      out.write("                transition: all 0.3s ease;\n");
      out.write("            }\n");
      out.write("            .form-control:focus {\n");
      out.write("                border-color: var(--accent-green);\n");
      out.write("                box-shadow: 0 0 0 0.2rem rgba(108, 168, 60, 0.25);\n");
      out.write("            }\n");
      out.write("            .form-select {\n");
      out.write("                border: 2px solid var(--pale-green);\n");
      out.write("                border-radius: 10px;\n");
      out.write("                padding: 0.75rem 1rem;\n");
      out.write("                background-color: var(--pale-green);\n");
      out.write("                font-weight: 500;\n");
      out.write("            }\n");
      out.write("            .form-select:focus {\n");
      out.write("                border-color: var(--accent-green);\n");
      out.write("                box-shadow: 0 0 0 0.2rem rgba(108, 168, 60, 0.25);\n");
      out.write("                background-color: white;\n");
      out.write("            }\n");
      out.write("            .form-label {\n");
      out.write("                font-weight: 600;\n");
      out.write("                color: var(--primary-green);\n");
      out.write("                margin-bottom: 0.5rem;\n");
      out.write("            }\n");
      out.write("            .subscription-title {\n");
      out.write("                color: var(--primary-green);\n");
      out.write("                font-weight: 700;\n");
      out.write("                margin-bottom: 1.5rem;\n");
      out.write("            }\n");
      out.write("            .subscription-info {\n");
      out.write("                background: linear-gradient(135deg, var(--pale-green) 0%, #e8f5e8 100%);\n");
      out.write("                border-radius: 15px;\n");
      out.write("                padding: 1.5rem;\n");
      out.write("                margin-bottom: 2rem;\n");
      out.write("                border-left: 5px solid var(--accent-green);\n");
      out.write("            }\n");
      out.write("            .expiration-warning {\n");
      out.write("                background: linear-gradient(135deg, #fff3cd 0%, #ffeaa7 100%);\n");
      out.write("                border: 2px solid #f39c12;\n");
      out.write("                border-radius: 15px;\n");
      out.write("                padding: 1rem;\n");
      out.write("                margin-top: 1rem;\n");
      out.write("            }\n");
      out.write("            .checkbox-container {\n");
      out.write("                background: #f8f9fa;\n");
      out.write("                border-radius: 10px;\n");
      out.write("                padding: 1.5rem;\n");
      out.write("                border: 2px solid var(--pale-green);\n");
      out.write("                margin: 1.5rem 0;\n");
      out.write("            }\n");
      out.write("            .feature-icon {\n");
      out.write("                font-size: 3rem;\n");
      out.write("                color: var(--accent-green);\n");
      out.write("                margin-bottom: 1rem;\n");
      out.write("            }\n");
      out.write("            .divider {\n");
      out.write("                height: 3px;\n");
      out.write("                background: linear-gradient(135deg, var(--primary-green) 0%, var(--accent-green) 100%);\n");
      out.write("                border: none;\n");
      out.write("                border-radius: 2px;\n");
      out.write("                margin: 2rem 0;\n");
      out.write("            }\n");
      out.write("            @media (max-width: 768px) {\n");
      out.write("                .premium-title {\n");
      out.write("                    font-size: 2rem;\n");
      out.write("                }\n");
      out.write("                .btn-premium {\n");
      out.write("                    font-size: 1rem;\n");
      out.write("                    padding: 0.75rem 1.5rem;\n");
      out.write("                }\n");
      out.write("                .feature-card {\n");
      out.write("                    padding: 1.5rem;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("        <script>\n");
      out.write("            document.addEventListener('DOMContentLoaded', function () {\n");
      out.write("                window.location.hash = \"no-back-button\";\n");
      out.write("                window.location.hash = \"Again-No-back-button\";\n");
      out.write("                window.onhashchange = function () {\n");
      out.write("                    window.location.hash = \"\";\n");
      out.write("                };\n");
      out.write("            });\n");
      out.write("            function sM(bol) {\n");
      out.write("                if (bol) {\n");
      out.write("                    document.getElementById('sm').disabled = false;\n");
      out.write("                } else {\n");
      out.write("                    document.getElementById('sm').disabled = true;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        </script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
      out.write("<style>\n");
      out.write("    body {\n");
      out.write("        font-family: 'Inter', sans-serif;\n");
      out.write("        margin: 0;\n");
      out.write("        padding-top: 120px;\n");
      out.write("        background-color: #f8f9fa;\n");
      out.write("    }\n");
      out.write("    iframe {\n");
      out.write("        width: 100%;\n");
      out.write("        height: calc(100vh - 120px);\n");
      out.write("        border: none;\n");
      out.write("    }\n");
      out.write("    .navbar-top {\n");
      out.write("        background-color: #198754;\n");
      out.write("    }\n");
      out.write("    .navbar-bottom {\n");
      out.write("        background-color: #000;\n");
      out.write("        z-index: 0;\n");
      out.write("    }\n");
      out.write("    .navbar-brand img {\n");
      out.write("        width: 2em;\n");
      out.write("        height: 2em;\n");
      out.write("        margin-right: 0.5rem;\n");
      out.write("    }\n");
      out.write("    .nav-link {\n");
      out.write("        color: white !important;\n");
      out.write("    }\n");
      out.write("    .nav-link:hover {\n");
      out.write("        color: #a4f3b5 !important;\n");
      out.write("    }\n");
      out.write("    .dropdown-menu a:hover {\n");
      out.write("        background-color: #198754;\n");
      out.write("        color: white !important;\n");
      out.write("    }\n");
      out.write("    .dropdown-toggle::after {\n");
      out.write("        margin-left: 0.4em;\n");
      out.write("    }\n");
      out.write("    @media (max-width: 768px) {\n");
      out.write("        body {\n");
      out.write("            padding-top: 170px;\n");
      out.write("        }\n");
      out.write("        iframe {\n");
      out.write("            height: calc(100vh - 170px);\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("    .navbar-bottom .navbar-nav {\n");
      out.write("        display: flex;\n");
      out.write("        justify-content: space-between;\n");
      out.write("        width: 100%;\n");
      out.write("    }\n");
      out.write("    .navbar-bottom .nav-item {\n");
      out.write("        flex-grow: 1;\n");
      out.write("        text-align: center;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("<script>\n");
      out.write("    document.addEventListener('DOMContentLoaded', function () {\n");
      out.write("        window.location.hash = \"no-back-button\";\n");
      out.write("        window.location.hash = \"Again-No-back-button\";\n");
      out.write("        window.onhashchange = function () {\n");
      out.write("            window.location.hash = \"\";\n");
      out.write("        };\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("<body style='background-color: #e9e9e9;'>\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark navbar-top fixed-top shadow-sm\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <a class=\"navbar-brand d-flex align-items-center\" href=\"#\">\n");
      out.write("            <img src=\"imgs/logo.png\" alt=\"Logo\">\n");
      out.write("            <span class=\"fw\">PlantiSHOP</span>\n");
      out.write("        </a>\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#topNavbar\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <ul class=\"navbar-nav ms-auto\">\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"Ventas.jsp\">Tus Ventas</a></li>\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mensajeria.jsp\">Tus Compras y Pedidos</a></li>\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"FAQ.html\">FAQ</a></li>\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"Premium.jsp\">PREMIUM</a></li>\n");
      out.write("        </ul>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"topNavbar\">\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\n");
      out.write("                <li class=\"nav-item dropdown\">\n");
      out.write("                    <a class=\"nav-link dropdown-toggle d-flex align-items-center\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\">\n");
      out.write("                        <img src=\"imgs/perfil.jpg\" alt=\"Perfil\" class=\"rounded-circle me-2\" style=\"width: 2em; height: 2em;\">\n");
      out.write("                        Perfil\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-end\">\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"Perfil.jsp\">Tu Perfil</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"Jardin.jsp\">Tu Jardín</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"Interfaz.jsp?x=E\">Cerrar Sesión</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark navbar-bottom fixed-top shadow-sm\" style=\"top: 56px;\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#bottomNavbar\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"bottomNavbar\">\n");
      out.write("            <ul class=\"navbar-nav\">\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#PD\">Plantas Decorativas</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#PH\">Plantas de Huerto</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#PA\">Plantas Acuáticas</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#A\">Árboles</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#AH\">Algas y Hongos</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#F\">Fertilizantes</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#H\">Herramientas</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>");
      out.write("\n");
      out.write("        \n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <div class=\"premium-header text-center\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <i class=\"bi bi-gem feature-icon\"></i>\n");
      out.write("                    <h1 class=\"premium-title\">PREMIUM</h1>\n");
      out.write("                    <p class=\"premium-description\">\n");
      out.write("                        ¡Pon a tu Disposición una Programación Especial de PlantiSHOP; y ten Acceso a nuestro ChatBot \"Basil.IA\", \n");
      out.write("                        tu nuevo Asistente Personal de Jardinería, y a un Analista Estadístico-Predictivo de tus Actividades \n");
      out.write("                        Comerciales en la Aplicación y del Mercado Botánico de PlantiSHOP!\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"container\">\n");
      out.write("                ");

                    try {
                        if (session.getAttribute("msg") != null) {
                            out.print("<script>alert('"+session.getAttribute("msg")+"');</script>");
                            session.removeAttribute("msg");
                        }
                        Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
                        c = DriverManager.getConnection("jdbc:mysql://localhost/PSHOP", "root", "n0m3l0");
                        s = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                        r = s.executeQuery("SELECT P,FfS,N,AP,AM FROM Usuario WHERE CE='"+session.getAttribute("u")+"'");
                        r.next();
                        if (r.getBoolean(1)) {
                            out.print("<div class='row'>");
                                out.print("<div class='col-md-6 mb-4'>");
                                    out.print("<div class='feature-card text-center'>");
                                        out.print("<i class='bi bi-robot feature-icon' style='color: #00bcd4;'></i>");
                                        out.print("<h3 class='mb-3' style='color: var(--primary-green);'>Basil.IA</h3>");
                                        out.print("<p class='text-muted mb-4'>Tu Asistente Personal de Jardinería con Inteligencia Artificial</p>");
                                        out.print("<button class='btn btn-premium btn-basil w-100' onclick=\"location.assign('premium/ChatBot.jsp')\"><i class='bi bi-chat-dots me-2'></i>Acceder a Basil.IA</button>");
                                    out.print("</div>");
                                out.print("</div>");
                                out.print("<div class='col-md-6 mb-4'>");
                                    out.print("<div class='feature-card text-center'>");
                                        out.print("<i class='bi bi-graph-up feature-icon' style='color: #ff9800;'></i>");
                                        out.print("<h3 class='mb-3' style='color: var(--primary-green);'>Analisis de Datos</h3>");
                                        out.print("<p class='text-muted mb-4'>Estadísticas y Predicciones de tus Actividades Comerciales</p>");
                                        out.print("<button class='btn btn-premium btn-analytics w-100' onclick=\"location.assign('premium/Analisis.jsp')\"><i class='bi bi-bar-chart me-2'></i>Ver ANÁLISIS</button>");
                                    out.print("</div>");
                                out.print("</div>");
                            out.print("</div>");
                            out.print("<div class='subscription-info text-center'>");
                                out.print("<h2 class='subscription-title'><i class='bi bi-calendar-check me-2'></i>Tu Suscripción termina el "+r.getDate(2).toLocalDate().format(DateTimeFormatter.ofPattern("E, d / MMM / uuuu")).toUpperCase()+"</h2>");
                                if (LocalDate.now().until(r.getDate(2).toLocalDate(), ChronoUnit.DAYS) <= 8L) {
                                    out.print("<div class='expiration-warning'><i class='bi bi-exclamation-triangle me-2'></i><strong>¡Faltan "+LocalDate.now().until(r.getDate(2).toLocalDate(), ChronoUnit.DAYS)+" días para que termine tu Suscripción!</strong></div>");
                                }
                            out.print("</div>");
                        } else {
                            out.print("<div class='row justify-content-center'>");
                                out.print("<div class='col-lg-8 col-xl-6'>");
                                    out.print("<div class='subscription-form'>");
                                        out.print("<div class='text-center mb-4'><i class='bi bi-star-fill feature-icon'></i><h2 class='subscription-title'>¡Suscríbete a PlantiSHOP!</h2></div>");
                                        out.print("<form action='UpSuscripciones' method='post'>");
                                            out.print("<div class='subscription-info text-center'><p class='mb-0'><strong>"+session.getAttribute("u")+"</strong></p></div>");
                                            out.print("<div class='mb-3'>");
                                                out.print("<label for='i1' class='form-label'><i class='bi bi-credit-card me-2'></i>Clave Bancaria Estandarizada (CLABE) de tu Cuenta Bancaria:</label>");
                                                out.print("<input id='i1' name='CLABE' type='password' class='form-control' pattern='[0-9]{18}' maxlength='18' placeholder='Ingresa tu CLABE de 18 dígitos :3' required>");
                                            out.print("</div>");
                                            out.print("<div class='mb-3'>");
                                                out.print("<label for='i2' class='form-label'><i class='bi bi-telephone me-2'></i>Número de Teléfono asociado a la Cuenta:</label>");
                                                out.print("<input id='i2' name='tf' type='tel' class='form-control' maxlength='10' placeholder='10 dígitos :3' required>");
                                            out.print("</div>");
                                            out.print("<div class='mb-4'>");
                                                out.print("<label for='i3' class='form-label'><i class='bi bi-calendar me-2'></i>Plan de Suscripción:</label>");
                                                out.print("<select id='i3' name='ps' class='form-select' required>");
                                                    out.print("<option value='25.00' selected>Mensual (30 días) - $25.00</option>");
                                                    out.print("<option value='75.00'>Trimestral (3 meses) - $75.00</option>");
                                                    out.print("<option value='150.00'>Semestral (6 meses) - $150.00</option>");
                                                    out.print("<option value='300.00'>Anual (365 días) - $300.00</option>");
                                                out.print("</select>");
                                            out.print("</div>");
                                            out.print("<div class='checkbox-container'>");
                                                out.print("<div class='form-check'>");
                                                    out.print("<input class='form-check-input' type='checkbox' id='agreement' name='SI' onclick='sM(this.checked)' value='Yo, "+r.getString(3)+" "+r.getString(4)+" "+r.getString(5)+" ("+session.getAttribute("u")+"), Acepto y Confirmo esta Transferencia Bancaria a EcoByte, realizada el día "+LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/uuuu"))+", para el uso del Apartado PREMIUM de PlantiSHOP' required>");
                                                    out.print("<label class='form-check-label' for='agreement'><small>Yo, <strong>"+r.getString(3)+" "+r.getString(4)+" "+r.getString(5)+"</strong> (<strong>"+session.getAttribute("u")+"</strong>), Acepto y Confirmo esta Transferencia Bancaria a EcoByte, realizada el día <strong>"+LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/uuuu"))+"</strong>, para el uso del Apartado PREMIUM de PlantiSHOP</small></label>");
                                                out.print("</div>");
                                            out.print("</div>");
                                            out.print("<div class='text-center'><button id='sm' type='submit' class='btn btn-premium btn-lg' disabled><i class='bi bi-check-circle me-2'></i>SUSCRIBIRSE</button></div>");
                                        out.print("</form>");
                                    out.print("</div>");
                                out.print("</div>");
                            out.print("</div>");
                        }
                        r.close();
                        s.close();
                        c.close();
                    } catch (Exception e) {
                        out.print("<script>alert('Lo sentimos, se produjo un ERROR... intentalo de NUEVO...');</script>");
                        out.print("<script>history.back();</script>");
                    }
                
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
