/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-07-02 17:58:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import auxs.Llavero;

public final class Registro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("auxs.Llavero");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es-MX\">\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Registro de Usuario</title>\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"imgs/logo.png\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <style>\n");
      out.write("            @font-face {\n");
      out.write("                font-family: 'Coco Gothic';\n");
      out.write("                src: url(fonts/CocoGothic.ttf);\n");
      out.write("            }\n");
      out.write("            @font-face {\n");
      out.write("                font-family: 'Agrandir';\n");
      out.write("                src: url(fonts/Agrandir.otf);\n");
      out.write("            }\n");
      out.write("            body {\n");
      out.write("                background-image: url(imgs/fondo.png);\n");
      out.write("                background-size: cover;\n");
      out.write("                background-attachment: fixed;\n");
      out.write("                background-position: center;\n");
      out.write("                background-repeat: no-repeat;\n");
      out.write("                font-family: 'Coco Gothic', sans-serif;\n");
      out.write("                min-height: 100vh;\n");
      out.write("            }\n");
      out.write("            .register-card {\n");
      out.write("                width: 95%;\n");
      out.write("                max-width: 850px;\n");
      out.write("                background-color: rgba(255, 255, 255, 0.95);\n");
      out.write("                border-radius: 20px;\n");
      out.write("                padding: 2.5em;\n");
      out.write("                margin: 2em auto;\n");
      out.write("                box-shadow: 0 0 25px rgba(0, 0, 0, 0.2);\n");
      out.write("            }\n");
      out.write("            h1 {\n");
      out.write("                text-align: center;\n");
      out.write("                font-family: 'Agrandir', sans-serif;\n");
      out.write("                color: whitesmoke;\n");
      out.write("                font-size: 5vw;\n");
      out.write("                margin-top: 1rem;\n");
      out.write("            }\n");
      out.write("            .logo {\n");
      out.write("                width: 1.5em;\n");
      out.write("                height: 1.5em;\n");
      out.write("                vertical-align: middle;\n");
      out.write("            }\n");
      out.write("            h2 {\n");
      out.write("                font-family: 'Agrandir', sans-serif;\n");
      out.write("                font-size: 2.2rem;\n");
      out.write("                margin-bottom: 1rem;\n");
      out.write("            }\n");
      out.write("            .form-label {\n");
      out.write("                font-weight: bold;\n");
      out.write("                margin-top: 1em;\n");
      out.write("            }\n");
      out.write("            input[type=\"text\"],\n");
      out.write("            input[type=\"email\"],\n");
      out.write("            input[type=\"password\"] {\n");
      out.write("                width: 100%;\n");
      out.write("                padding: 0.6em;\n");
      out.write("                margin-top: 0.3em;\n");
      out.write("                border-radius: 8px;\n");
      out.write("                border: 1px solid #ccc;\n");
      out.write("            }\n");
      out.write("            #gMap {\n");
      out.write("                width: 100%;\n");
      out.write("                height: 12em;\n");
      out.write("                border-radius: 10px;\n");
      out.write("                margin-bottom: 1em;\n");
      out.write("                border: 1px solid #198754;\n");
      out.write("            }\n");
      out.write("            .btn-green {\n");
      out.write("                background-color: #198754;\n");
      out.write("                color: white;\n");
      out.write("                font-weight: bold;\n");
      out.write("                border-radius: 10px;\n");
      out.write("                padding: 0.8em 1.5em;\n");
      out.write("                border: none;\n");
      out.write("            }\n");
      out.write("            .btn-green:hover {\n");
      out.write("                background-color: #157347;\n");
      out.write("            }\n");
      out.write("            .divider {\n");
      out.write("                display: flex;\n");
      out.write("                align-items: center;\n");
      out.write("                text-align: center;\n");
      out.write("                margin-top: 2em;\n");
      out.write("                margin-bottom: 1em;\n");
      out.write("                color: #666;\n");
      out.write("                font-weight: bold;\n");
      out.write("            }\n");
      out.write("            .divider::before,\n");
      out.write("            .divider::after {\n");
      out.write("                content: \"\";\n");
      out.write("                flex: 1;\n");
      out.write("                border-bottom: 1px solid #bbb;\n");
      out.write("            }\n");
      out.write("            .divider::before {\n");
      out.write("                margin-right: .75em;\n");
      out.write("            }\n");
      out.write("            .divider::after {\n");
      out.write("                margin-left: .75em;\n");
      out.write("            }\n");
      out.write("            .text-link {\n");
      out.write("                display: block;\n");
      out.write("                text-align: center;\n");
      out.write("                font-weight: bold;\n");
      out.write("                color: #198754;\n");
      out.write("                text-decoration: none;\n");
      out.write("                font-size: 1rem;\n");
      out.write("                transition: color 0.3s ease;\n");
      out.write("            }\n");
      out.write("            .text-link:hover {\n");
      out.write("                text-decoration: underline;\n");
      out.write("                color: #145c38;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("        <script src=\"https://maps.googleapis.com/maps/api/js?key=");
      out.print( Llavero.getApiGoogleMaps() );
      out.write("&callback=initMap&v=weekly\" defer></script>\n");
      out.write("        <script>\n");
      out.write("            document.addEventListener('DOMContentLoaded', function () {\n");
      out.write("                window.location.hash = \"no-back-button\";\n");
      out.write("                window.location.hash = \"Again-No-back-button\";\n");
      out.write("                window.onhashchange = function () {\n");
      out.write("                    window.location.hash = \"\";\n");
      out.write("                };\n");
      out.write("            });\n");
      out.write("            window.initMap = function () {\n");
      out.write("                (new google.maps.Map(document.getElementById('gMap'), {\n");
      out.write("                    center: {\n");
      out.write("                        lat: 19.4326077,\n");
      out.write("                        lng: -99.133208\n");
      out.write("                    },\n");
      out.write("                    zoom: 8,\n");
      out.write("                    mapTypeControl: false\n");
      out.write("                })).addListener('click', function (ev) {\n");
      out.write("                    (new google.maps.Geocoder()).geocode({ location: ev.latLng }).then(\n");
      out.write("                        function (r) {\n");
      out.write("                            document.getElementById('i7').value = r.results[0].formatted_address;\n");
      out.write("                        },\n");
      out.write("                        function (er) {\n");
      out.write("                            alert('Lo sentimos, se produjo un ERROR:\\n'+er);\n");
      out.write("                        }\n");
      out.write("                    );\n");
      out.write("                });\n");
      out.write("            };\n");
      out.write("        </script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div class=\"text-center\">\n");
      out.write("            <h1><img src=\"imgs/logo.png\" alt=\"Logo\" class=\"logo\">&nbsp;PlantiSHOP</h1>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"register-card\">\n");
      out.write("            <h2 class=\"text-center\"><strong>Registro</strong></h2>\n");
      out.write("            <form action=\"Interfaz.jsp\" method=\"post\">\n");
      out.write("                <input type=\"hidden\" name=\"x\" value=\"C\">\n");
      out.write("                <label for=\"i1\" class=\"form-label\">Correo Electrónico:</label>\n");
      out.write("                <input id=\"i1\" name=\"ce\" type=\"email\" required>\n");
      out.write("                <label for=\"i2\" class=\"form-label\">Contraseña:</label>\n");
      out.write("                <input id=\"i2\" name=\"c1\" type=\"password\"\n");
      out.write("                       pattern=\"[A-Z]+[a-z]+[0-9]+[+-*/%$._!?]+\"\n");
      out.write("                       minlength=\"12\" maxlength=\"20\"\n");
      out.write("                       title=\"Debe contener Mayúsculas, Minúsculas, Números y Símbolos (+-*/%$._!?)\">\n");
      out.write("                <label for=\"i3\" class=\"form-label\">Contraseña de Respaldo:</label>\n");
      out.write("                <input id=\"i3\" name=\"c2\" type=\"password\"\n");
      out.write("                       pattern=\"[A-Z]+[a-z]+[0-9]+[+-*/%$._!?]+\"\n");
      out.write("                       minlength=\"12\" maxlength=\"20\"\n");
      out.write("                       title=\"Debe contener Mayúsculas, Minúsculas, Números y Símbolos (+-*/%$._!?)\">\n");
      out.write("                <label for=\"i4\" class=\"form-label\">Nombre(s):</label>\n");
      out.write("                <input id=\"i4\" name=\"n\" type=\"text\" pattern=\"[A-Za-z\\s']+\" maxlength=\"25\" required>\n");
      out.write("                <label for=\"i5\" class=\"form-label\">Apellido Paterno:</label>\n");
      out.write("                <input id=\"i5\" name=\"ap\" type=\"text\" pattern=\"[A-Za-z\\s']+\" maxlength=\"15\" required>\n");
      out.write("                <label for=\"i6\" class=\"form-label\">Apellido Materno:</label>\n");
      out.write("                <input id=\"i6\" name=\"am\" type=\"text\" pattern=\"[A-Za-z\\s']+\" maxlength=\"15\" required>\n");
      out.write("                <label for=\"i7\" class=\"form-label\">Ubicación:</label>\n");
      out.write("                <div id=\"gMap\"></div>\n");
      out.write("                <input id=\"i7\" name=\"u\" type=\"text\" readonly title=\"Selecciona en el Mapa la ubicación de tu Huerto o Jardín :)\" value=\"Ciudad de Mexico, Mexico\" required>\n");
      out.write("                <div class=\"divider\">¿Ya tienes una Cuenta?&nbsp;<a href=\"Sesion.html\" class=\"text-link\">Inicia Sesión AQUÍ</a></div>\n");
      out.write("                <div class=\"text-center\">\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-green mt-2 w-50\">REGISTRAR</button>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
