/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-07-02 18:00:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;

public final class Ventas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


    Connection c;
    Statement s;
    ResultSet r;
    String na;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/imgs/navbar.jsp", Long.valueOf(1751388600522L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');

    try {
        if (session.getAttribute("msg") != null) {
            out.print("<script>alert('"+session.getAttribute("msg")+"');</script>");
            session.removeAttribute("msg");
        }
        Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
        c = DriverManager.getConnection("jdbc:mysql://localhost/PSHOP", "root", "n0m3l0");
        s = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        r = s.executeQuery("SELECT N,AP,AM FROM Usuario WHERE CE='"+session.getAttribute("u")+"'");
        r.next();
        na = r.getString(1) + " " + r.getString(2) + " " + r.getString(3);
        r.close();
        r = null;
    } catch (Exception e) {
        out.print("<script>alert('Lo sentimos, se produjo un ERROR... intentalo de NUEVO...');</script>");
        out.print("<script>history.back();</script>");
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es-MX\">\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Ventas del Usuario</title>\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"imgs/logo.png\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" rel=\"stylesheet\">\n");
      out.write("        <style>\n");
      out.write("            :root {\n");
      out.write("                --primary-green: #2d5a27;\n");
      out.write("                --secondary-green: #4a7c59;\n");
      out.write("                --accent-green: #7fb069;\n");
      out.write("                --light-green: #a7c957;\n");
      out.write("                --bg-color: #f0f0f0;\n");
      out.write("                --card-bg: #ffffff;\n");
      out.write("                --text-dark: #2c3e50;\n");
      out.write("            }\n");
      out.write("            body {\n");
      out.write("                background-color: var(--bg-color);\n");
      out.write("                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("                color: var(--text-dark);\n");
      out.write("            }\n");
      out.write("            .header-section {\n");
      out.write("                background: linear-gradient(135deg, var(--primary-green), var(--secondary-green));\n");
      out.write("                color: white;\n");
      out.write("                padding: 2rem 0;\n");
      out.write("                box-shadow: 0 4px 6px rgba(0,0,0,0.1);\n");
      out.write("                margin-bottom: 2rem;\n");
      out.write("            }\n");
      out.write("            .header-section h1 {\n");
      out.write("                margin: 0;\n");
      out.write("                font-weight: 600;\n");
      out.write("                font-size: 2.2rem;\n");
      out.write("            }\n");
      out.write("            .register-form {\n");
      out.write("                background: var(--card-bg);\n");
      out.write("                border-radius: 15px;\n");
      out.write("                padding: 2rem;\n");
      out.write("                box-shadow: 0 5px 15px rgba(0,0,0,0.1);\n");
      out.write("                margin-bottom: 2rem;\n");
      out.write("                border-left: 5px solid var(--accent-green);\n");
      out.write("            }\n");
      out.write("            .register-form h2 {\n");
      out.write("                color: var(--primary-green);\n");
      out.write("                margin-bottom: 1.5rem;\n");
      out.write("                font-weight: 600;\n");
      out.write("            }\n");
      out.write("            .form-control, .form-select {\n");
      out.write("                border: 2px solid #e9ecef;\n");
      out.write("                border-radius: 8px;\n");
      out.write("                padding: 0.75rem;\n");
      out.write("                transition: all 0.3s ease;\n");
      out.write("            }\n");
      out.write("            .form-control:focus, .form-select:focus {\n");
      out.write("                border-color: var(--accent-green);\n");
      out.write("                box-shadow: 0 0 0 0.2rem rgba(127, 176, 105, 0.25);\n");
      out.write("            }\n");
      out.write("            .btn-register {\n");
      out.write("                background: linear-gradient(135deg, var(--primary-green), var(--secondary-green));\n");
      out.write("                border: none;\n");
      out.write("                color: white;\n");
      out.write("                padding: 0.75rem 2rem;\n");
      out.write("                border-radius: 8px;\n");
      out.write("                font-weight: 600;\n");
      out.write("                transition: all 0.3s ease;\n");
      out.write("                text-transform: uppercase;\n");
      out.write("                letter-spacing: 0.5px;\n");
      out.write("            }\n");
      out.write("            .btn-register:hover {\n");
      out.write("                transform: translateY(-2px);\n");
      out.write("                box-shadow: 0 4px 8px rgba(0,0,0,0.2);\n");
      out.write("                background: linear-gradient(135deg, var(--secondary-green), var(--primary-green));\n");
      out.write("            }\n");
      out.write("            .product-section {\n");
      out.write("                margin-bottom: 2rem;\n");
      out.write("            }\n");
      out.write("            .section-header {\n");
      out.write("                background: linear-gradient(135deg, var(--accent-green), var(--light-green));\n");
      out.write("                color: white;\n");
      out.write("                padding: 1rem 1.5rem;\n");
      out.write("                border-radius: 10px 10px 0 0;\n");
      out.write("                margin-bottom: 0;\n");
      out.write("                font-weight: 600;\n");
      out.write("                text-align: center;\n");
      out.write("            }\n");
      out.write("            .product-card {\n");
      out.write("                background: var(--card-bg);\n");
      out.write("                border-radius: 0 0 15px 15px;\n");
      out.write("                overflow: hidden;\n");
      out.write("                box-shadow: 0 5px 15px rgba(0,0,0,0.1);\n");
      out.write("                margin-bottom: 1.5rem;\n");
      out.write("                transition: transform 0.3s ease;\n");
      out.write("            }\n");
      out.write("            .product-card:hover {\n");
      out.write("                transform: translateY(-5px);\n");
      out.write("            }\n");
      out.write("            .product-row {\n");
      out.write("                display: flex;\n");
      out.write("                align-items: stretch;\n");
      out.write("                min-height: 200px;\n");
      out.write("            }\n");
      out.write("            .product-image-section {\n");
      out.write("                flex: 0 0 250px;\n");
      out.write("                padding: 1rem;\n");
      out.write("                background: linear-gradient(135deg, #f8f9fa, #e9ecef);\n");
      out.write("                display: flex;\n");
      out.write("                flex-direction: column;\n");
      out.write("                align-items: center;\n");
      out.write("                gap: 0.5rem;\n");
      out.write("            }\n");
      out.write("            .product-image {\n");
      out.write("                width: 100%;\n");
      out.write("                height: 120px;\n");
      out.write("                object-fit: cover;\n");
      out.write("                border-radius: 8px;\n");
      out.write("                box-shadow: 0 2px 8px rgba(0,0,0,0.1);\n");
      out.write("            }\n");
      out.write("            .product-details {\n");
      out.write("                flex: 1;\n");
      out.write("                padding: 1.5rem;\n");
      out.write("            }\n");
      out.write("            .product-title {\n");
      out.write("                color: var(--primary-green);\n");
      out.write("                font-size: 1.5rem;\n");
      out.write("                font-weight: 600;\n");
      out.write("                margin-bottom: 1rem;\n");
      out.write("                border-bottom: 2px solid var(--light-green);\n");
      out.write("                padding-bottom: 0.5rem;\n");
      out.write("            }\n");
      out.write("            .btn-action {\n");
      out.write("                border-radius: 6px;\n");
      out.write("                font-size: 0.85rem;\n");
      out.write("                padding: 0.4rem 1rem;\n");
      out.write("                margin: 0.25rem;\n");
      out.write("                transition: all 0.3s ease;\n");
      out.write("                font-weight: 500;\n");
      out.write("            }\n");
      out.write("            .btn-update {\n");
      out.write("                background-color: var(--secondary-green);\n");
      out.write("                border-color: var(--secondary-green);\n");
      out.write("                color: white;\n");
      out.write("            }\n");
      out.write("            .btn-update:hover {\n");
      out.write("                background-color: var(--primary-green);\n");
      out.write("                border-color: var(--primary-green);\n");
      out.write("                transform: translateY(-1px);\n");
      out.write("            }\n");
      out.write("            .btn-delete {\n");
      out.write("                background-color: #dc3545;\n");
      out.write("                border-color: #dc3545;\n");
      out.write("                color: white;\n");
      out.write("            }\n");
      out.write("            .btn-delete:hover {\n");
      out.write("                background-color: #c82333;\n");
      out.write("                border-color: #bd2130;\n");
      out.write("                transform: translateY(-1px);\n");
      out.write("            }\n");
      out.write("            .btn-change-image {\n");
      out.write("                background-color: var(--accent-green);\n");
      out.write("                border-color: var(--accent-green);\n");
      out.write("                color: white;\n");
      out.write("                font-size: 0.8rem;\n");
      out.write("            }\n");
      out.write("            .btn-change-image:hover {\n");
      out.write("                background-color: var(--secondary-green);\n");
      out.write("                border-color: var(--secondary-green);\n");
      out.write("            }\n");
      out.write("            .input-group-sm .form-control {\n");
      out.write("                padding: 0.5rem;\n");
      out.write("            }\n");
      out.write("            .form-floating textarea {\n");
      out.write("                min-height: 80px;\n");
      out.write("            }\n");
      out.write("            .pD .section-header { background: linear-gradient(135deg, #e8f5e8, #d4edda); color: var(--primary-green); }\n");
      out.write("            .pH .section-header { background: linear-gradient(135deg, #fff3cd, #ffeaa7); color: #856404; }\n");
      out.write("            .pA .section-header { background: linear-gradient(135deg, #d1ecf1, #bee5eb); color: #0c5460; }\n");
      out.write("            .A .section-header { background: linear-gradient(135deg, #d4edda, #c3e6cb); color: var(--primary-green); }\n");
      out.write("            .aH .section-header { background: linear-gradient(135deg, #f8d7da, #f5c6cb); color: #721c24; }\n");
      out.write("            .F .section-header { background: linear-gradient(135deg, #ffeaa7, #fdcb6e); color: #856404; }\n");
      out.write("            .H .section-header { background: linear-gradient(135deg, #e2e3e5, #d6d8db); color: #383d41; }\n");
      out.write("            @media (max-width: 768px) {\n");
      out.write("                .product-row {\n");
      out.write("                    flex-direction: column;\n");
      out.write("                }\n");
      out.write("                .product-image-section {\n");
      out.write("                    flex: none;\n");
      out.write("                }\n");
      out.write("                .header-section h1 {\n");
      out.write("                    font-size: 1.8rem;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("        <script>\n");
      out.write("            document.addEventListener('DOMContentLoaded', function () {\n");
      out.write("                window.location.hash = \"no-back-button\";\n");
      out.write("                window.location.hash = \"Again-No-back-button\";\n");
      out.write("                window.onhashchange = function () {\n");
      out.write("                    window.location.hash = \"\";\n");
      out.write("                };\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
      out.write("<style>\n");
      out.write("    body {\n");
      out.write("        font-family: 'Inter', sans-serif;\n");
      out.write("        margin: 0;\n");
      out.write("        padding-top: 120px;\n");
      out.write("        background-color: #f8f9fa;\n");
      out.write("    }\n");
      out.write("    iframe {\n");
      out.write("        width: 100%;\n");
      out.write("        height: calc(100vh - 120px);\n");
      out.write("        border: none;\n");
      out.write("    }\n");
      out.write("    .navbar-top {\n");
      out.write("        background-color: #198754;\n");
      out.write("    }\n");
      out.write("    .navbar-bottom {\n");
      out.write("        background-color: #000;\n");
      out.write("        z-index: 0;\n");
      out.write("    }\n");
      out.write("    .navbar-brand img {\n");
      out.write("        width: 2em;\n");
      out.write("        height: 2em;\n");
      out.write("        margin-right: 0.5rem;\n");
      out.write("    }\n");
      out.write("    .nav-link {\n");
      out.write("        color: white !important;\n");
      out.write("    }\n");
      out.write("    .nav-link:hover {\n");
      out.write("        color: #a4f3b5 !important;\n");
      out.write("    }\n");
      out.write("    .dropdown-menu a:hover {\n");
      out.write("        background-color: #198754;\n");
      out.write("        color: white !important;\n");
      out.write("    }\n");
      out.write("    .dropdown-toggle::after {\n");
      out.write("        margin-left: 0.4em;\n");
      out.write("    }\n");
      out.write("    @media (max-width: 768px) {\n");
      out.write("        body {\n");
      out.write("            padding-top: 170px;\n");
      out.write("        }\n");
      out.write("        iframe {\n");
      out.write("            height: calc(100vh - 170px);\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("    .navbar-bottom .navbar-nav {\n");
      out.write("        display: flex;\n");
      out.write("        justify-content: space-between;\n");
      out.write("        width: 100%;\n");
      out.write("    }\n");
      out.write("    .navbar-bottom .nav-item {\n");
      out.write("        flex-grow: 1;\n");
      out.write("        text-align: center;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("<script>\n");
      out.write("    document.addEventListener('DOMContentLoaded', function () {\n");
      out.write("        window.location.hash = \"no-back-button\";\n");
      out.write("        window.location.hash = \"Again-No-back-button\";\n");
      out.write("        window.onhashchange = function () {\n");
      out.write("            window.location.hash = \"\";\n");
      out.write("        };\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("<body style='background-color: #e9e9e9;'>\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark navbar-top fixed-top shadow-sm\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <a class=\"navbar-brand d-flex align-items-center\" href=\"#\">\n");
      out.write("            <img src=\"imgs/logo.png\" alt=\"Logo\">\n");
      out.write("            <span class=\"fw\">PlantiSHOP</span>\n");
      out.write("        </a>\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#topNavbar\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <ul class=\"navbar-nav ms-auto\">\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"Ventas.jsp\">Tus Ventas</a></li>\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mensajeria.jsp\">Tus Compras y Pedidos</a></li>\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"FAQ.html\">FAQ</a></li>\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"Premium.jsp\">PREMIUM</a></li>\n");
      out.write("        </ul>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"topNavbar\">\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\n");
      out.write("                <li class=\"nav-item dropdown\">\n");
      out.write("                    <a class=\"nav-link dropdown-toggle d-flex align-items-center\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\">\n");
      out.write("                        <img src=\"imgs/perfil.jpg\" alt=\"Perfil\" class=\"rounded-circle me-2\" style=\"width: 2em; height: 2em;\">\n");
      out.write("                        Perfil\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-end\">\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"Perfil.jsp\">Tu Perfil</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"Jardin.jsp\">Tu Jardín</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"Interfaz.jsp?x=E\">Cerrar Sesión</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark navbar-bottom fixed-top shadow-sm\" style=\"top: 56px;\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#bottomNavbar\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"bottomNavbar\">\n");
      out.write("            <ul class=\"navbar-nav\">\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#PD\">Plantas Decorativas</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#PH\">Plantas de Huerto</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#PA\">Plantas Acuáticas</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#A\">Árboles</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#AH\">Algas y Hongos</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#F\">Fertilizantes</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"Mercado.jsp#H\">Herramientas</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>");
      out.write("\n");
      out.write("        \n");
      out.write("        <div class=\"header-section\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row align-items-center\">\n");
      out.write("                    <div class=\"col\">\n");
      out.write("                        <h1><i class=\"fas fa-leaf me-3\"></i>Ventas de ");
      out.print( na );
      out.write("</h1>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"register-form\">\n");
      out.write("                <h2><i class=\"fas fa-plus-circle me-2\"></i>Registro de Productos en el Sistema</h2>\n");
      out.write("                <form action=\"UpVentas\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("                    <input name=\"x\" type=\"hidden\" value=\"true\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-6 mb-3\">\n");
      out.write("                            <div class=\"form-floating\">\n");
      out.write("                                <input id=\"i1\" name=\"n\" type=\"text\" class=\"form-control\" pattern=\"[A-Za-z0-9\\s,']+\" maxlength=\"80\" placeholder=\"Nombre del Producto\" required>\n");
      out.write("                                <label for=\"i1\"><i class=\"fas fa-seedling me-2\"></i>Nombre del Producto</label>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-6 mb-3\">\n");
      out.write("                            <div class=\"form-floating\">\n");
      out.write("                                <select id=\"i3\" name=\"t\" class=\"form-select\" required>\n");
      out.write("                                    <optgroup label=\"Plantaciones\">\n");
      out.write("                                        <option value=\"PD\" selected>Planta Decorativa</option>\n");
      out.write("                                        <option value=\"PH\">Planta de Huerto</option>\n");
      out.write("                                        <option value=\"PA\">Planta Acuática</option>\n");
      out.write("                                        <option value=\"A\">Árbol</option>\n");
      out.write("                                        <option value=\"AH\">Alga / Hongo</option>\n");
      out.write("                                    </optgroup>\n");
      out.write("                                    <option value=\"F\">Fertilizante</option>\n");
      out.write("                                    <option value=\"H\">Herramienta</option>\n");
      out.write("                                </select>\n");
      out.write("                                <label for=\"i3\"><i class=\"fas fa-tags me-2\"></i>Tipo</label>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-4 mb-3\">\n");
      out.write("                            <div class=\"form-floating\">\n");
      out.write("                                <input id=\"i4\" name=\"p\" type=\"number\" class=\"form-control\" min=\"1\" max=\"5000000\" placeholder=\"Precio ($1.00 - $5,000,000)\" required>\n");
      out.write("                                <label for=\"i4\"><i class=\"fas fa-dollar-sign me-2\"></i>Precio del Producto</label>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-4 mb-3\">\n");
      out.write("                            <div class=\"form-floating\">\n");
      out.write("                                <input id=\"i5\" name=\"c\" type=\"number\" class=\"form-control\" min=\"1\" max=\"1000000\" step=\"1\" placeholder=\"Cantidad (1 - 1,000,000)\" required>\n");
      out.write("                                <label for=\"i5\"><i class=\"fas fa-boxes me-2\"></i>Cantidad del Producto</label>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-4 mb-3\">\n");
      out.write("                            <label for=\"i6\" class=\"form-label\"><i class=\"fas fa-image me-2\"></i>Imagen del Producto</label>\n");
      out.write("                            <input id=\"i6\" name=\"i\" type=\"file\" class=\"form-control\" accept=\"image/*\" required>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mb-3\">\n");
      out.write("                        <div class=\"form-floating\">\n");
      out.write("                            <textarea id=\"i2\" name=\"txt\" class=\"form-control\" pattern=\"[A-Za-z0-9\\s,';.]+\" maxlength=\"800\" placeholder=\"Descripción\" style=\"height: 100px;\"></textarea>\n");
      out.write("                            <label for=\"i2\"><i class=\"fas fa-align-left me-2\"></i>Descripción del Producto</label>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"text-center\">\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-register\">\n");
      out.write("                            <i class=\"fas fa-save me-2\"></i>REGISTRAR\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("            <hr>\n");
      out.write("            ");

                try {
                    r = s.executeQuery("SELECT Img,Id,N,P,D,Cupo FROM Producto WHERE CE='"+session.getAttribute("u")+"' AND T='PD' ORDER BY Pop DESC, Cupo ASC");
                    if (r.next()) {
                        out.print("<div class='product-section pD'>");
                            out.print("<div class='section-header'><i class='fas fa-leaf me-2'></i>Plantas Decorativas</div>");
                            r.beforeFirst();
                            while (r.next()) {
                                out.print("<div class='product-card'>");
                                    out.print("<div class='product-row'>");
                                        out.print("<div class='product-image-section'>");
                                            out.print("<img src='imgs/prods/"+r.getString(1)+"' alt='Planta Decorativa' class='product-image'/>");
                                            out.print("<form action='UpVentas' method='post' enctype='multipart/form-data' class='w-100'>");
                                                out.print("<input name='x' type='hidden' value='false'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                out.print("<input name='i' type='file' class='form-control form-control-sm mb-2' accept='image/*' required>");
                                                out.print("<button type='submit' class='btn btn-change-image btn-sm w-100'>CAMBIAR Imagen</button>");
                                            out.print("</form>");
                                            out.print("<button class='btn btn-delete btn-sm w-100' onclick=\"location.assign('Interfaz.jsp?x=D2&t=Producto&id="+r.getLong(2)+"')\"><i class='fas fa-trash me-1'></i>ELIMINAR</button>");
                                        out.print("</div>");
                                    out.print("</div>");
                                    out.print("<div class='product-details'>");
                                        out.print("<h3 class='product-title'>"+r.getString(3)+"</h3>");
                                        out.print("<div class='row mb-3'>");
                                            out.print("<div class='col-md-6'>");
                                                out.print("<form action='Interfaz.jsp' method='post' class='d-flex align-items-center'>");
                                                    out.print("<input name='x' type='hidden' value='Upv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                    out.print("<div class='input-group input-group-sm'><span class='input-group-text'><i class='fas fa-dollar-sign'></i>Precio:</span><input name='p' type='number' min='1' max='5000000' class='form-control' value='"+r.getFloat(4)+"' required><button class='btn btn-update btn-action' type='submit'>CAMBIAR</button></div>");
                                                out.print("</form>");
                                            out.print("</div>");
                                            out.print("<div class='col-md-6'>");
                                                out.print("<form action='Interfaz.jsp' method='post' class='d-flex align-items-center'>");
                                                    out.print("<input name='x' type='hidden' value='Ucv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                    out.print("<div class='input-group input-group-sm'><span class='input-group-text'><i class='fas fa-boxes'></i>Cantidad:</span><input name='c' type='number' min='1' max='1000000' step='1' class='form-control' value='"+r.getInt(6)+"' required><button class='btn btn-update btn-action' type='submit'>CAMBIAR</button></div>");
                                                out.print("</form>");
                                            out.print("</div>");
                                            out.print("<form action='Interfaz.jsp' method='post'>");
                                                out.print("<input name='x' type='hidden' value='Utxtv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                out.print("<div class='input-group'>");
                                                    out.print("<textarea name='txt' class='form-control' pattern='[A-Za-z0-9\\s]+' maxlength='800' placeholder='Descripción del Producto'>"+r.getString(5)+"</textarea>");
                                                    out.print("<button class='btn btn-update btn-action' type='submit'><i class='fas fa-edit me-1'></i>CAMBIAR Descripción</button>");
                                                out.print("</div>");
                                            out.print("</form>");
                                        out.print("</div>");
                                    out.print("</div>");
                                out.print("</div>");
                            }
                        out.print("</div>");
                    }
                    r.close();
                    r = null;
                    r = s.executeQuery("SELECT Img,Id,N,P,D,Cupo FROM Producto WHERE CE='"+session.getAttribute("u")+"' AND T='PH' ORDER BY Pop DESC, Cupo ASC");
                    if (r.next()) {
                        out.print("<div class='product-section pH'>");
                            out.print("<div class='section-header'><i class='fas fa-leaf me-2'></i>Plantas de Huerto</div>");
                            r.beforeFirst();
                            while (r.next()) {
                                out.print("<div class='product-card'>");
                                    out.print("<div class='product-row'>");
                                        out.print("<div class='product-image-section'>");
                                            out.print("<img src='imgs/prods/"+r.getString(1)+"' alt='Planta de Huerto' class='product-image'/>");
                                            out.print("<form action='UpVentas' method='post' enctype='multipart/form-data' class='w-100'>");
                                                out.print("<input name='x' type='hidden' value='false'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                out.print("<input name='i' type='file' class='form-control form-control-sm mb-2' accept='image/*' required>");
                                                out.print("<button type='submit' class='btn btn-change-image btn-sm w-100'>CAMBIAR Imagen</button>");
                                            out.print("</form>");
                                            out.print("<button class='btn btn-delete btn-sm w-100' onclick=\"location.assign('Interfaz.jsp?x=D2&t=Producto&id="+r.getLong(2)+"')\"><i class='fas fa-trash me-1'></i>ELIMINAR</button>");
                                        out.print("</div>");
                                    out.print("</div>");
                                    out.print("<div class='product-details'>");
                                        out.print("<h3 class='product-title'>"+r.getString(3)+"</h3>");
                                        out.print("<div class='row mb-3'>");
                                            out.print("<div class='col-md-6'>");
                                                out.print("<form action='Interfaz.jsp' method='post' class='d-flex align-items-center'>");
                                                    out.print("<input name='x' type='hidden' value='Upv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                    out.print("<div class='input-group input-group-sm'><span class='input-group-text'><i class='fas fa-dollar-sign'></i>Precio:</span><input name='p' type='number' min='1' max='5000000' class='form-control' value='"+r.getFloat(4)+"' required><button class='btn btn-update btn-action' type='submit'>CAMBIAR</button></div>");
                                                out.print("</form>");
                                            out.print("</div>");
                                            out.print("<div class='col-md-6'>");
                                                out.print("<form action='Interfaz.jsp' method='post' class='d-flex align-items-center'>");
                                                    out.print("<input name='x' type='hidden' value='Ucv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                    out.print("<div class='input-group input-group-sm'><span class='input-group-text'><i class='fas fa-boxes'></i>Cantidad:</span><input name='c' type='number' min='1' max='1000000' step='1' class='form-control' value='"+r.getInt(6)+"' required><button class='btn btn-update btn-action' type='submit'>CAMBIAR</button></div>");
                                                out.print("</form>");
                                            out.print("</div>");
                                            out.print("<form action='Interfaz.jsp' method='post'>");
                                                out.print("<input name='x' type='hidden' value='Utxtv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                out.print("<div class='input-group'>");
                                                    out.print("<textarea name='txt' class='form-control' pattern='[A-Za-z0-9\\s]+' maxlength='800' placeholder='Descripción del Producto'>"+r.getString(5)+"</textarea>");
                                                    out.print("<button class='btn btn-update btn-action' type='submit'><i class='fas fa-edit me-1'></i>CAMBIAR Descripción</button>");
                                                out.print("</div>");
                                            out.print("</form>");
                                        out.print("</div>");
                                    out.print("</div>");
                                out.print("</div>");
                            }
                        out.print("</div>");
                    }
                    r.close();
                    r = null;
                    r = s.executeQuery("SELECT Img,Id,N,P,D,Cupo FROM Producto WHERE CE='"+session.getAttribute("u")+"' AND T='PA' ORDER BY Pop DESC, Cupo ASC");
                    if (r.next()) {
                        out.print("<div class='product-section pA'>");
                            out.print("<div class='section-header'><i class='fas fa-leaf me-2'></i>Plantas Acuaticas</div>");
                            r.beforeFirst();
                            while (r.next()) {
                                out.print("<div class='product-card'>");
                                    out.print("<div class='product-row'>");
                                        out.print("<div class='product-image-section'>");
                                            out.print("<img src='imgs/prods/"+r.getString(1)+"' alt='Planta Acuatica' class='product-image'/>");
                                            out.print("<form action='UpVentas' method='post' enctype='multipart/form-data' class='w-100'>");
                                                out.print("<input name='x' type='hidden' value='false'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                out.print("<input name='i' type='file' class='form-control form-control-sm mb-2' accept='image/*' required>");
                                                out.print("<button type='submit' class='btn btn-change-image btn-sm w-100'>CAMBIAR Imagen</button>");
                                            out.print("</form>");
                                            out.print("<button class='btn btn-delete btn-sm w-100' onclick=\"location.assign('Interfaz.jsp?x=D2&t=Producto&id="+r.getLong(2)+"')\"><i class='fas fa-trash me-1'></i>ELIMINAR</button>");
                                        out.print("</div>");
                                    out.print("</div>");
                                    out.print("<div class='product-details'>");
                                        out.print("<h3 class='product-title'>"+r.getString(3)+"</h3>");
                                        out.print("<div class='row mb-3'>");
                                            out.print("<div class='col-md-6'>");
                                                out.print("<form action='Interfaz.jsp' method='post' class='d-flex align-items-center'>");
                                                    out.print("<input name='x' type='hidden' value='Upv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                    out.print("<div class='input-group input-group-sm'><span class='input-group-text'><i class='fas fa-dollar-sign'></i>Precio:</span><input name='p' type='number' min='1' max='5000000' class='form-control' value='"+r.getFloat(4)+"' required><button class='btn btn-update btn-action' type='submit'>CAMBIAR</button></div>");
                                                out.print("</form>");
                                            out.print("</div>");
                                            out.print("<div class='col-md-6'>");
                                                out.print("<form action='Interfaz.jsp' method='post' class='d-flex align-items-center'>");
                                                    out.print("<input name='x' type='hidden' value='Ucv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                    out.print("<div class='input-group input-group-sm'><span class='input-group-text'><i class='fas fa-boxes'></i>Cantidad:</span><input name='c' type='number' min='1' max='1000000' step='1' class='form-control' value='"+r.getInt(6)+"' required><button class='btn btn-update btn-action' type='submit'>CAMBIAR</button></div>");
                                                out.print("</form>");
                                            out.print("</div>");
                                            out.print("<form action='Interfaz.jsp' method='post'>");
                                                out.print("<input name='x' type='hidden' value='Utxtv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                out.print("<div class='input-group'>");
                                                    out.print("<textarea name='txt' class='form-control' pattern='[A-Za-z0-9\\s]+' maxlength='800' placeholder='Descripción del Producto'>"+r.getString(5)+"</textarea>");
                                                    out.print("<button class='btn btn-update btn-action' type='submit'><i class='fas fa-edit me-1'></i>CAMBIAR Descripción</button>");
                                                out.print("</div>");
                                            out.print("</form>");
                                        out.print("</div>");
                                    out.print("</div>");
                                out.print("</div>");
                            }
                        out.print("</div>");
                    }
                    r.close();
                    r = null;
                    r = s.executeQuery("SELECT Img,Id,N,P,D,Cupo FROM Producto WHERE CE='"+session.getAttribute("u")+"' AND T='A' ORDER BY Pop DESC, Cupo ASC");
                    if (r.next()) {
                        out.print("<div class='product-section A'>");
                            out.print("<div class='section-header'><i class='fas fa-leaf me-2'></i>Arboles</div>");
                            r.beforeFirst();
                            while (r.next()) {
                                out.print("<div class='product-card'>");
                                    out.print("<div class='product-row'>");
                                        out.print("<div class='product-image-section'>");
                                            out.print("<img src='imgs/prods/"+r.getString(1)+"' alt='Arbol' class='product-image'/>");
                                            out.print("<form action='UpVentas' method='post' enctype='multipart/form-data' class='w-100'>");
                                                out.print("<input name='x' type='hidden' value='false'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                out.print("<input name='i' type='file' class='form-control form-control-sm mb-2' accept='image/*' required>");
                                                out.print("<button type='submit' class='btn btn-change-image btn-sm w-100'>CAMBIAR Imagen</button>");
                                            out.print("</form>");
                                            out.print("<button class='btn btn-delete btn-sm w-100' onclick=\"location.assign('Interfaz.jsp?x=D2&t=Producto&id="+r.getLong(2)+"')\"><i class='fas fa-trash me-1'></i>ELIMINAR</button>");
                                        out.print("</div>");
                                    out.print("</div>");
                                    out.print("<div class='product-details'>");
                                        out.print("<h3 class='product-title'>"+r.getString(3)+"</h3>");
                                        out.print("<div class='row mb-3'>");
                                            out.print("<div class='col-md-6'>");
                                                out.print("<form action='Interfaz.jsp' method='post' class='d-flex align-items-center'>");
                                                    out.print("<input name='x' type='hidden' value='Upv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                    out.print("<div class='input-group input-group-sm'><span class='input-group-text'><i class='fas fa-dollar-sign'></i>Precio:</span><input name='p' type='number' min='1' max='5000000' class='form-control' value='"+r.getFloat(4)+"' required><button class='btn btn-update btn-action' type='submit'>CAMBIAR</button></div>");
                                                out.print("</form>");
                                            out.print("</div>");
                                            out.print("<div class='col-md-6'>");
                                                out.print("<form action='Interfaz.jsp' method='post' class='d-flex align-items-center'>");
                                                    out.print("<input name='x' type='hidden' value='Ucv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                    out.print("<div class='input-group input-group-sm'><span class='input-group-text'><i class='fas fa-boxes'></i>Cantidad:</span><input name='c' type='number' min='1' max='1000000' step='1' class='form-control' value='"+r.getInt(6)+"' required><button class='btn btn-update btn-action' type='submit'>CAMBIAR</button></div>");
                                                out.print("</form>");
                                            out.print("</div>");
                                            out.print("<form action='Interfaz.jsp' method='post'>");
                                                out.print("<input name='x' type='hidden' value='Utxtv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                out.print("<div class='input-group'>");
                                                    out.print("<textarea name='txt' class='form-control' pattern='[A-Za-z0-9\\s]+' maxlength='800' placeholder='Descripción del Producto'>"+r.getString(5)+"</textarea>");
                                                    out.print("<button class='btn btn-update btn-action' type='submit'><i class='fas fa-edit me-1'></i>CAMBIAR Descripción</button>");
                                                out.print("</div>");
                                            out.print("</form>");
                                        out.print("</div>");
                                    out.print("</div>");
                                out.print("</div>");
                            }
                        out.print("</div>");
                    }
                    r.close();
                    r = null;
                    r = s.executeQuery("SELECT Img,Id,N,P,D,Cupo FROM Producto WHERE CE='"+session.getAttribute("u")+"' AND T='AH' ORDER BY Pop DESC, Cupo ASC");
                    if (r.next()) {
                        out.print("<div class='product-section aH'>");
                            out.print("<div class='section-header'><i class='fas fa-leaf me-2'></i>Algas y/u Hongos</div>");
                            r.beforeFirst();
                            while (r.next()) {
                                out.print("<div class='product-card'>");
                                    out.print("<div class='product-row'>");
                                        out.print("<div class='product-image-section'>");
                                            out.print("<img src='imgs/prods/"+r.getString(1)+"' alt='Alga u Hongo' class='product-image'/>");
                                            out.print("<form action='UpVentas' method='post' enctype='multipart/form-data' class='w-100'>");
                                                out.print("<input name='x' type='hidden' value='false'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                out.print("<input name='i' type='file' class='form-control form-control-sm mb-2' accept='image/*' required>");
                                                out.print("<button type='submit' class='btn btn-change-image btn-sm w-100'>CAMBIAR Imagen</button>");
                                            out.print("</form>");
                                            out.print("<button class='btn btn-delete btn-sm w-100' onclick=\"location.assign('Interfaz.jsp?x=D2&t=Producto&id="+r.getLong(2)+"')\"><i class='fas fa-trash me-1'></i>ELIMINAR</button>");
                                        out.print("</div>");
                                    out.print("</div>");
                                    out.print("<div class='product-details'>");
                                        out.print("<h3 class='product-title'>"+r.getString(3)+"</h3>");
                                        out.print("<div class='row mb-3'>");
                                            out.print("<div class='col-md-6'>");
                                                out.print("<form action='Interfaz.jsp' method='post' class='d-flex align-items-center'>");
                                                    out.print("<input name='x' type='hidden' value='Upv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                    out.print("<div class='input-group input-group-sm'><span class='input-group-text'><i class='fas fa-dollar-sign'></i>Precio:</span><input name='p' type='number' min='1' max='5000000' class='form-control' value='"+r.getFloat(4)+"' required><button class='btn btn-update btn-action' type='submit'>CAMBIAR</button></div>");
                                                out.print("</form>");
                                            out.print("</div>");
                                            out.print("<div class='col-md-6'>");
                                                out.print("<form action='Interfaz.jsp' method='post' class='d-flex align-items-center'>");
                                                    out.print("<input name='x' type='hidden' value='Ucv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                    out.print("<div class='input-group input-group-sm'><span class='input-group-text'><i class='fas fa-boxes'></i>Cantidad:</span><input name='c' type='number' min='1' max='1000000' step='1' class='form-control' value='"+r.getInt(6)+"' required><button class='btn btn-update btn-action' type='submit'>CAMBIAR</button></div>");
                                                out.print("</form>");
                                            out.print("</div>");
                                            out.print("<form action='Interfaz.jsp' method='post'>");
                                                out.print("<input name='x' type='hidden' value='Utxtv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                out.print("<div class='input-group'>");
                                                    out.print("<textarea name='txt' class='form-control' pattern='[A-Za-z0-9\\s]+' maxlength='800' placeholder='Descripción del Producto'>"+r.getString(5)+"</textarea>");
                                                    out.print("<button class='btn btn-update btn-action' type='submit'><i class='fas fa-edit me-1'></i>CAMBIAR Descripción</button>");
                                                out.print("</div>");
                                            out.print("</form>");
                                        out.print("</div>");
                                    out.print("</div>");
                                out.print("</div>");
                            }
                        out.print("</div>");
                    }
                    r.close();
                    r = null;
                    r = s.executeQuery("SELECT Img,Id,N,P,D,Cupo FROM Producto WHERE CE='"+session.getAttribute("u")+"' AND T='F' ORDER BY Pop DESC, Cupo ASC");
                    if (r.next()) {
                        out.print("<div class='product-section F'>");
                            out.print("<div class='section-header'><i class='fas fa-leaf me-2'></i>Fertilizantes</div>");
                            r.beforeFirst();
                            while (r.next()) {
                                out.print("<div class='product-card'>");
                                    out.print("<div class='product-row'>");
                                        out.print("<div class='product-image-section'>");
                                            out.print("<img src='imgs/prods/"+r.getString(1)+"' alt='Fertilizante' class='product-image'/>");
                                            out.print("<form action='UpVentas' method='post' enctype='multipart/form-data' class='w-100'>");
                                                out.print("<input name='x' type='hidden' value='false'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                out.print("<input name='i' type='file' class='form-control form-control-sm mb-2' accept='image/*' required>");
                                                out.print("<button type='submit' class='btn btn-change-image btn-sm w-100'>CAMBIAR Imagen</button>");
                                            out.print("</form>");
                                            out.print("<button class='btn btn-delete btn-sm w-100' onclick=\"location.assign('Interfaz.jsp?x=D2&t=Producto&id="+r.getLong(2)+"')\"><i class='fas fa-trash me-1'></i>ELIMINAR</button>");
                                        out.print("</div>");
                                    out.print("</div>");
                                    out.print("<div class='product-details'>");
                                        out.print("<h3 class='product-title'>"+r.getString(3)+"</h3>");
                                        out.print("<div class='row mb-3'>");
                                            out.print("<div class='col-md-6'>");
                                                out.print("<form action='Interfaz.jsp' method='post' class='d-flex align-items-center'>");
                                                    out.print("<input name='x' type='hidden' value='Upv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                    out.print("<div class='input-group input-group-sm'><span class='input-group-text'><i class='fas fa-dollar-sign'></i>Precio:</span><input name='p' type='number' min='1' max='5000000' class='form-control' value='"+r.getFloat(4)+"' required><button class='btn btn-update btn-action' type='submit'>CAMBIAR</button></div>");
                                                out.print("</form>");
                                            out.print("</div>");
                                            out.print("<div class='col-md-6'>");
                                                out.print("<form action='Interfaz.jsp' method='post' class='d-flex align-items-center'>");
                                                    out.print("<input name='x' type='hidden' value='Ucv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                    out.print("<div class='input-group input-group-sm'><span class='input-group-text'><i class='fas fa-boxes'></i>Cantidad:</span><input name='c' type='number' min='1' max='1000000' step='1' class='form-control' value='"+r.getInt(6)+"' required><button class='btn btn-update btn-action' type='submit'>CAMBIAR</button></div>");
                                                out.print("</form>");
                                            out.print("</div>");
                                            out.print("<form action='Interfaz.jsp' method='post'>");
                                                out.print("<input name='x' type='hidden' value='Utxtv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                out.print("<div class='input-group'>");
                                                    out.print("<textarea name='txt' class='form-control' pattern='[A-Za-z0-9\\s]+' maxlength='800' placeholder='Descripción del Producto'>"+r.getString(5)+"</textarea>");
                                                    out.print("<button class='btn btn-update btn-action' type='submit'><i class='fas fa-edit me-1'></i>CAMBIAR Descripción</button>");
                                                out.print("</div>");
                                            out.print("</form>");
                                        out.print("</div>");
                                    out.print("</div>");
                                out.print("</div>");
                            }
                        out.print("</div>");
                    }
                    r.close();
                    r = null;
                    r = s.executeQuery("SELECT Img,Id,N,P,D,Cupo FROM Producto WHERE CE='"+session.getAttribute("u")+"' AND T='H' ORDER BY Pop DESC, Cupo ASC");
                    if (r.next()) {
                        out.print("<div class='product-section H'>");
                            out.print("<div class='section-header'><i class='fas fa-leaf me-2'></i>Herramientas</div>");
                            r.beforeFirst();
                            while (r.next()) {
                                out.print("<div class='product-card'>");
                                    out.print("<div class='product-row'>");
                                        out.print("<div class='product-image-section'>");
                                            out.print("<img src='imgs/prods/"+r.getString(1)+"' alt='Herramienta' class='product-image'/>");
                                            out.print("<form action='UpVentas' method='post' enctype='multipart/form-data' class='w-100'>");
                                                out.print("<input name='x' type='hidden' value='false'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                out.print("<input name='i' type='file' class='form-control form-control-sm mb-2' accept='image/*' required>");
                                                out.print("<button type='submit' class='btn btn-change-image btn-sm w-100'>CAMBIAR Imagen</button>");
                                            out.print("</form>");
                                            out.print("<button class='btn btn-delete btn-sm w-100' onclick=\"location.assign('Interfaz.jsp?x=D2&t=Producto&id="+r.getLong(2)+"')\"><i class='fas fa-trash me-1'></i>ELIMINAR</button>");
                                        out.print("</div>");
                                    out.print("</div>");
                                    out.print("<div class='product-details'>");
                                        out.print("<h3 class='product-title'>"+r.getString(3)+"</h3>");
                                        out.print("<div class='row mb-3'>");
                                            out.print("<div class='col-md-6'>");
                                                out.print("<form action='Interfaz.jsp' method='post' class='d-flex align-items-center'>");
                                                    out.print("<input name='x' type='hidden' value='Upv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                    out.print("<div class='input-group input-group-sm'><span class='input-group-text'><i class='fas fa-dollar-sign'></i>Precio:</span><input name='p' type='number' min='1' max='5000000' class='form-control' value='"+r.getFloat(4)+"' required><button class='btn btn-update btn-action' type='submit'>CAMBIAR</button></div>");
                                                out.print("</form>");
                                            out.print("</div>");
                                            out.print("<div class='col-md-6'>");
                                                out.print("<form action='Interfaz.jsp' method='post' class='d-flex align-items-center'>");
                                                    out.print("<input name='x' type='hidden' value='Ucv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                    out.print("<div class='input-group input-group-sm'><span class='input-group-text'><i class='fas fa-boxes'></i>Cantidad:</span><input name='c' type='number' min='1' max='1000000' step='1' class='form-control' value='"+r.getInt(6)+"' required><button class='btn btn-update btn-action' type='submit'>CAMBIAR</button></div>");
                                                out.print("</form>");
                                            out.print("</div>");
                                            out.print("<form action='Interfaz.jsp' method='post'>");
                                                out.print("<input name='x' type='hidden' value='Utxtv'><input name='id' type='hidden' value='"+r.getLong(2)+"'>");
                                                out.print("<div class='input-group'>");
                                                    out.print("<textarea name='txt' class='form-control' pattern='[A-Za-z0-9\\s]+' maxlength='800' placeholder='Descripción del Producto'>"+r.getString(5)+"</textarea>");
                                                    out.print("<button class='btn btn-update btn-action' type='submit'><i class='fas fa-edit me-1'></i>CAMBIAR Descripción</button>");
                                                out.print("</div>");
                                            out.print("</form>");
                                        out.print("</div>");
                                    out.print("</div>");
                                out.print("</div>");
                            }
                        out.print("</div>");
                    }
                    r.close();
                    s.close();
                    c.close();
                } catch (Exception e) {
                    out.print("<script>alert('Lo sentimos, se produjo un ERROR... intentalo de NUEVO...');</script>");
                    out.print("<script>history.back();</script>");
                }
            
      out.write("\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
